CNAME
The CNAME file on the `gh-pages` branch is relevant and this one isn't needed.
=> :bug: (repo) Remove CNAME file

.ci/github/_dep_gomplate.sh, .ci/github/_dep_helm-docs.sh, .ci/github/install-releaser-deps.sh, .ci/github/update-pages-site.sh, .github/workflows/release.yaml, README.md, hack/README.tpl.md, hack/update-readme.sh, hack/update-readme/indexpage.yaml, hack/update-readme/readme.yaml
* fixes some issues with the existing template
* exposes current versions of charts and apps in README
* uses gomplate to update the GitHub Pages site
* adds matomo campaign trackers for links to adfinis.com
* adds some marketing speak and a contact link to the readme
* cleans up `.ci/github` for more reuseability
=> root README: fix template, add Geschwurbel, publish to gh-pages

charts/argoconfig/Chart.yaml, charts/argoconfig/README.md, charts/argoconfig/ci/default.yaml, charts/argoconfig/templates/secret-cluster.yaml, charts/argoconfig/values.yaml
This new template helps you create the [cluster parts of a declarative argoconfig setup](https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#clusters).
=> argoconfig: helper for creating cluster secrets

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/clusterrole.yaml, charts/barman/templates/rolebinding.yaml, charts/barman/values.yaml
This let's a user create a ClusterRole to automatically restore postgresql database if a backup is available.
Example initContainer for use in the `bitnami/postgresql` chart:
```yaml
barman:
containerName: barman-barman-0
namespace: backup-barman
master:
extraInitContainers:
- name: barman-restore
image: bitnami/kubectl
command:
- /bin/bash
- -cx
- |
set -euf
[ "$(ls -A /data/data)" ] && exit 0 || echo "data dir is empty. trying to restore latest backup"
[ "$(kubectl --namespace {{ .Values.barman.namespace }} get pod {{ .Values.barman.containerName }})" ] || exit 0
[ "$(kubectl --namespace {{ .Values.barman.namespace }} exec {{ .Values.barman.containerName }} -- barman check-backup {{ template "postgresql.name" . }} last)" ] || exit 0
kubectl --namespace {{ .Values.barman.namespace }} …
```
=> implement rbac for automatic restore of postgresql databases

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/ci/default-values.yaml, charts/barman/templates/statefulset.yaml, charts/barman/values.yaml
The `persistentVolumeReclaimPolicy` can only be set on a PV (or defaulted on the StorageClass itself). I'm not sure how to properly fix this, but this revert at least make the latest version of the chart not fail. I'll have a look at the possibility of setting this through an annotation or with a dedicated StorageClass but I don't think either of those solutions are the way to go (see https://github.com/kubernetes/kubernetes/issues/30606 for some discussion about this).
This reverts commit 1379c2f0fc60d17ef1e25e696d1c6daf8a97fc5e.
=> :rewind: (barman) default Retain policy for data volume

README.md, charts/sentry-apps/Chart.yaml, charts/sentry-apps/README.md, charts/sentry-apps/templates/application.yaml, charts/sentry-apps/values.yaml
- 5.0.0 (Sentry 20.7.2) adds Relay to the mix.
- enables NGINX by default, which has to be disabled when using Ingress.
=> feat(sentry-apps): bump Sentry Helm chart to 5.0.0

README.md, charts/sentry-apps/Chart.yaml, charts/sentry-apps/README.md
Upgrades Sentry to 20.8.1 which adds the snuba-transactions-consumer container.
=> :arrow_up: (sentry-apps) bump sentry-kubernetes/sentry to 5.1.1

README.md, charts/kasperleyn/Chart.yaml, charts/kasperleyn/README.md, charts/kasperleyn/values.yaml
This will be the last Caasperli available for testing Helm v2 charts in isolation, thus I'm deprecating it as 1.0 (feature complete).
Once we merge this and get it through CD I'll get rid of the `charts/kasperleyn` folder as well.
=> :boom: (kasperleyn) deprecate chart

README.md, charts/misc-apps/.helmignore, charts/misc-apps/Chart.lock, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/ci/default-values.yaml, charts/misc-apps/examples/kube-downscaler.yaml, charts/misc-apps/examples/signalilo.yaml, charts/misc-apps/templates/NOTES.txt, charts/misc-apps/templates/downscaler.yaml, charts/misc-apps/templates/signalilo.yaml, charts/misc-apps/values.yaml
Similar to #36 (infra-apps) but with things not needed on every cluster and maybe more experimental things as well.
Browse the chart here: https://github.com/hairmare/helm-charts/tree/feat/misc-apps/charts/misc-apps
=> :sparkles: (misc-apps) init misc-apps

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/examples/sentry-kubernetes.yaml, charts/misc-apps/templates/NOTES.txt, charts/misc-apps/templates/sentry-kubernetes.yaml, charts/misc-apps/values.yaml
This prepares the misc-apps chart so we can use it to deploy [sentry-kubernetes](https://github.com/getsentry/sentry-kubernetes) which will ship kubernetes events to sentry.
=> feat(misc-apps): add sentry-kubernetes app

hack/ci/github/setup/pre-commit.sh, hack/ci/github/setup/release.sh
Stomps this warning and a similiar one about env vars:
* [add-path docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path)
* [set env docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable)
=> chore(ci): replace deprecated add-path command

.czrc
As a lot of us are already using it we might as well configure it as the default.
=> chore: configure cz-conventional-changelog in .czrc

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
No special upgrade steps required according to the cert-manager documentation: https://cert-manager.io/docs/installation/upgrading/upgrading-1.0-1.1/
=> chore(infra-apps): bump cert-manager version to 1.1.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
infra-certManager isn't a valid namespace
```
~ kubectl create ns infra-certManager
The Namespace "infra-certManager" is invalid: metadata.name: Invalid value: "infra-certManager": a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?')
```
=> fix(values.yaml): lowercase namespace

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Had the strange issue, that fullnameOverride wasn't working as expected (got
`infra-infra-downscaler` as name).
This is my output without and with setting `name` inside `values.yaml`:
```
…/charts/misc-apps helm template . --set downscaler.enabled=true --set fullnameOverride=infra | grep "name: "
name: infra-downscaler
…/charts/misc-apps helm template . --set downscaler.enabled=true --set fullnameOverride=infra | grep "name: "
name: infra-infra-downscaler
```
=> fix(misc-apps): add name into values

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Error in argocd if project sourceRepos do not have the trailing slash.
=> fix(values.yaml): remove trailing slash from repoURL

charts/back8sup/Chart.yaml, charts/back8sup/README.md, charts/back8sup/values.yaml
As `adfinissygroup/back8sup` moved to `ghcr.io/adfinis-sygroup/back8sup` this makes sure the charts uses the correct image
=> chore(ghcr.io): move image repo

.github/workflows/release.yaml
Adds the https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/master/charts repo to chart-releaser.
Can we put these inside a config file?
=> fix(chart-releaser): add dependency repo

charts/caasperli/Chart.yaml, charts/caasperli/README.md, charts/caasperli/templates/grafana/configmap-dashboard.yaml
I'm not sure why this is happening. But adding a `name:` to the configMapList, solves the issue.
I removed everything beneith (keeping a very simple configmap with hard coded names) and it was still failing. This is when I realized the configMapList is in the eyes of helm also just a Object, but has no name defined (does not need it to work!).
We could migrate away from using `ConfigMapList` and just use good old `---\nobject...\n---\nobject`.
I'll let the decision to you @hairmare
=> fix(caasperli): templates / configmapList, add name for ci

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Contains mostly small low risk changes:
* 3.20.1
* Do not create KEDA in case of DaemonSets.
* Fix KEDA v2 definition
* 3.20.0
* Do not create HPA for defaultBackend if not enabled.
* 3.19.0
* Update ingress-nginx v0.43.0
* 3.18.0
* Allow volume-type emptyDir in controller podsecuritypolicy
* Improve parsing of helm parameters
=> chore(infra-apps): bump nginx-ingress chart to 3.20.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Changes:
* 12.x to 13.x
*  Version 13 upgrades prometheus-operator from 0.43.x to 0.44.x (Add schema validations to AlertmanagerConfig CRD).
* 11.x to 12.x
* The chart was migrated to support only helm v3 and later.
* 10.x to 11.x
* Version 11 upgrades prometheus-operator from 0.42.x to 0.43.x. Starting with 0.43.x an additional `AlertmanagerConfigs` CRD is introduced. Helm does not automatically upgrade or install new CRDs on a chart upgrade, so you have to install the CRD manually before updating.
* Version 11 removes the deprecated tlsProxy via ghostunnel in favor of native TLS support the prometheus-operator gained with v0.39.0.
The following change needs to be applied manually when upgrading a cluster to this new release:
```console
kubectl apply -f …
```
=> chore(infra-apps): bump kube-prmetheus-stack chart to 13.0.*

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Changes:
* 3.3.0
* add means to configurate liveness and readiness endpoints for forwarder and aggregator
* 3.4.0 
* add missing features from stable/fluentd
=> chore(logging-apps): bump fluentd chart to 3.4.x

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Changes:
* 2.1.0
* Allow overrding secret key name in speaker secret when using an external speaker secret.
=> chore(misc-apps): bump metallb chart version to 2.1.x

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Changes:
* 1.7
* bump to falco 0.27 (contains updated ruleset)
* 1.6
* allow adding additional volumes and volumeMounts to falco daemonset
=> chore(security-apps): bump falco chart to 1.7.x

charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/ci/default-values.yaml, charts/vault-monitoring/templates/servicemonitor.yaml
This was a wrong doing in our initial Chart, never tested, as default values is "no labels"
=> fix(quickfix/vault-monitoring): labeling issue on template of serviceMonitor

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Changes:
* Add `Kubeless` output
* Add `PagerDuty` output
* Add option to use an existing secret
* Add option to add extra environment variables
* Add `Stan` output
* Use the Existing secret resource and add all possible variables to there, and make it simpler to read and less error-prone in the deployment resource
=> chore(security-apps): bump falcosidekick chart version to 0.2.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates kube-prometheus-stack to the latest 13.3.* version
* Allow override of prometheus and alertmanager default base images
* Remove configmapReloadImage reference in values.yaml
=> chore(kube-prometheus-stack): update to version 13.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml, charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml, charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml, charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
* ingress-nginx :arrow_up_small: `3.22.*`
* kube-prometheus-stack :arrow_up_small: `13.4.*`
* fluentd :arrow_up_small: `3.5.*`
* metallb :arrow_up_small: `2.2.*`
* dex :arrow_up_small: `2.15.*`
* vault :arrow_up_small: `0.9.*`
* falco-exporter :arrow_up_small: `0.5.*`
* ceph-csi-rbd :arrow_up_small: `3.2.*`
* ceph-csi-cephfs :arrow_up_small: `3.2.*`
=> chore(updates): switch to latest tergetRevision

charts/csi-secret-provider-class/Chart.lock, charts/csi-secret-provider-class/Chart.yaml, charts/csi-secret-provider-class/README.md, charts/csi-secret-provider-class/ci/default-values.yaml, charts/csi-secret-provider-class/templates/_helpers.tpl, charts/csi-secret-provider-class/templates/deployment.yaml, charts/csi-secret-provider-class/values.yaml
Adds a dummyDeployment Option to be able to make the vault-secret-store provider create the secret if extraVolumes can't be used inside the Chart/App.
=> feat(dummyDeployment): addition

charts/cert-manager-issuers/Chart.yaml, charts/cert-manager-issuers/README.md, charts/cert-manager-issuers/examples/disable-issuers.yaml, charts/cert-manager-issuers/templates/clusterissuers.yaml, charts/cert-manager-issuers/templates/issuers.yaml
So we can conveniently disable single issuers without having to comment the whole issuer.
=> feat(cert-manager-issuers): enabled flag for issuers

CODEOWNERS, charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/_helpers.tpl
Fixes the nameOverride by not creating 
`barman-barman-config` if `$name` is contained in the `$releaseName`
=> fix(barman): templates/_helpers.tpl fullNameOverride addition + release name contains

charts/huawei-csi-plugin/Chart.yaml, charts/huawei-csi-plugin/README.md
A version `0.0.1` does not make sense.
We bump the version to `0.1.0` to start
=> feat(huawei-csi-plugin): chart verison to minor instead of patchfixing a `0.0.0.`

charts/vault-csi-provider/Chart.lock, charts/vault-csi-provider/Chart.yaml, charts/vault-csi-provider/README.md, charts/vault-csi-provider/templates/daemonset.yaml, charts/vault-csi-provider/values.yaml
* Updates our vault-csi-provider to use image tag 0.0.7 and adds default resources, as in the deployment example [changelog](https://github.com/hashicorp/secrets-store-csi-driver-provider-vault/releases/tag/0.0.7)
* Updates the dependency of secrets-store-csi-driver to 0.0.20 [changelog](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.0.20)
n/a
=> chore(vault-csi-provider): update provider to 0.0.7 and dep to 0.0.20

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/examples/secrets-store-csi-driver.yaml, charts/security-apps/templates/secrets-store-csi-driver.yaml, charts/security-apps/values.yaml
Adds the secrets-store-csi-driver application to the security-apps.
First step needed for deprecating `vaultAuth` and `vaultCsiProvider` in favor of just using `vault` official helm chart.
as the secrets-store-csi-driver doesn't get installed with the official helm chart of hashicorp, we need to add this as an additional application.
n/a
=> feat(security-apps): secrets-store-csi-driver addition)

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update cert-manager in infra-apps to v1.3
No relevant changes for our use-cases.
* `CertificateRequests` are now immutable
* Breaking changes in Venafi Cloud issuer: https://cert-manager.io/docs/release-notes/release-notes-1.3/#venafi-cloud-issuer
Link to the upstream release notes: https://cert-manager.io/docs/release-notes/release-notes-1.3/
=> chore(infra-apps): update cert-manager to v1.3

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/deployment-backend.yaml, charts/timed/templates/deployment-frontend.yaml, charts/timed/templates/prometheus/podmonitor.yaml, charts/timed/templates/service-backend.yaml, charts/timed/templates/service-frontend.yaml
Fixes this error:
> PodMonitor.monitoring.coreos.com "timed-backend" is invalid: spec.podMetricsEndpoints.port: Invalid value: "integer": spec.podMetricsEndpoints.port in body must be of type string: "integer"
=> fix(timed): use named ports instead of repeating number

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/templates/cronjob-backend.yaml, charts/timed/templates/deployment-backend.yaml, charts/timed/templates/job-dbmigrate.yaml
We need to set ALLOWED_HOSTS to the pods IP to allow it to get scraped by Prometheus and @sbor23 found [this gem](https://github.com/korfuri/django-prometheus/issues/81#issuecomment-456210855).
=> fix(timed): use podIP from status for allowed hosts

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/kured.yaml
The `beta.kubernetes.io/os` label has been deprecated since v1.14 so we should replace it with the correct `kubernetes.io/os` label in the kured configuration example.
n/a
=> docs(infra-apps): remove deprecated beta.kubernetes.io/os label from kured example

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
- https://github.com/kubernetes/ingress-nginx/pull/7117 Add annotations for HPA
- https://github.com/kubernetes/ingress-nginx/pull/7137 Add support for custom probes
- [#7092](https://github.com/kubernetes/ingress-nginx/pull/7092) Removes the possibility of using localhost in ExternalNames as endpoints
=> feat(infra-apps): bump nginx-ingress chart to 3.32

charts/caasperli/Chart.yaml, charts/caasperli/README.md, charts/caasperli/templates/NOTES.txt, charts/caasperli/templates/_helpers.tpl, charts/caasperli/templates/deployment.yaml, charts/caasperli/templates/hpa.yaml, charts/caasperli/templates/ingress.yaml, charts/caasperli/templates/tests/test-connection.yaml, charts/caasperli/values.yaml
This change introduces support for `networking.k8s.io/v1` Ingress configuration and some other changes to align with helm create from Helm v3.6.
BREAKING CHANGE: Ingress configuration in `values.yaml` has changed and `deploymentAnnotations` has been removed from `values.yaml`.
This PR supersedes #259.
=> feat(caasperli): add support for networking.k8s.io/v1 Ingress

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Contains heaps of changes from upstream (but none should be bc breaking)
* specify env variables for deployment via extraEnv value
* update jaeger-operator to 1.22.1
* fix NodePort services
* Fix CRD schema
* update jaeger-operator to 1.21.2
* Add preserve unknown fields annotation to FreeForm and Options fields 
* Migrate remaining flags and some env vars to 1.22 
* Fix override storage and ingress values when upgrade to 1.22 
* Add agent dnsPolicy option 
* Allow configure custom certificates to collector 
* Add support for NodePort in Jaeger Query Service 
* Add ability to indicate PriorityClass for collector and query 
* simplest example file should be as simplest 
* Add ability to indicate PriorityClass for agent 
* Migrate jaeger.tags in existing CRs 
* Remove support for the …
=> feat(tracing-apps): bump jaeger-operator to 2.21

charts/caasperli/Chart.yaml, charts/caasperli/README.md, charts/caasperli/values.yaml
Change the default repository for the Caasperli image to GitHub container registry
=> Configure GitHub container registry as default repository for Caasperli

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrades Chart Version to 3.4.*
> Upgrading from < v3.4.0 Chart 3.4.0 deprecates support for Helm 2 and also removes the creation of the gatekeeper-system Namespace from within the chart. This follows Helm 3 Best Practices.
> 
> Option 1:
> A simple way to upgrade is to uninstall first and re-install with 3.4.0 or greater.
> 
> $ helm uninstall gatekeeper
> $ helm install -n gatekeeper-system [RELEASE_NAME] gatekeeper/gatekeeper --create-namespace
> 
> Option 2:
> Run the helm_migrate.sh script before installing the 3.4.0 or greater chart. This will remove the Helm secret for the original release, while keeping all of the resources. It then updates the annotations of the resources so that the new chart can import and manage them.
> 
> $ helm_migrate.sh
> $ helm install -n …
=> chore(gatekeeper): Upgrade to 3.4.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update cert-manager to v1.4
None of the urgent upgrade notes are relevant for us:
* The CA issuer now attempts to store the root CA instead of the issuing CA into the ca.crt field for issued certificates; this is a change of behavior. All of the information which was previously available is still available: the intermediate should appear as part of the chain in tls.crt.
* RunAsNonRoot is now enabled by default in the securityContext values. If you're using custom containers with the chart that run as root, you will need to set this back to false.
=> chore(infra-apps): update cert-manager to v1.4

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
bump nginx-ingress chart to 0.34.*:
- Add namespace field in the namespace scoped resource templates (https://github.com/kubernetes/ingress-nginx/pull/7256)
=> fix(infra-apps): bump nginx-ingress to 0.34.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update dex Helm chart to 0.5.0 to update dex to v2.29.0.
Helm Chart:
* 0.4.0: Add support for configuring `priorityClassName`
* 0.5.0: Update dex to v2.29.0
Dex:
* [v2.29.0](https://github.com/dexidp/dex/releases/tag/v2.29.0): No relevant changes for us, but [#1846](https://github.com/dexidp/dex/pull/1846) add some features regarding refresh token handling.
=> feat(security-apps): upgrade dex Helm chart to 0.5.0

charts/huawei-csi-plugin/Chart.yaml, charts/huawei-csi-plugin/README.md, charts/huawei-csi-plugin/templates/daemonset-node.yaml, charts/huawei-csi-plugin/templates/deployment-controller.yaml, charts/huawei-csi-plugin/values.yaml
Because the huawei-csi-driver image doesn't log to stdout I've added a tail container that will make the logs available via `kubectl logs`.
=> Add tail container and move securityContext configuration in huawei-csi-plugin

charts/huawei-csi-plugin/Chart.yaml, charts/huawei-csi-plugin/README.md, charts/huawei-csi-plugin/templates/daemonset-node.yaml, charts/huawei-csi-plugin/templates/deployment-controller.yaml
Add checksum/config annotation to controller deployment and node daemonset to trigger a restart when the configuration changes.
=> fix(huawei-csi-plugin): use checksum/config annotation to automatically rollout config changes

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/templates/cronjob.yaml
Fix duplicate key name, which causes problems for: https://github.com/fluxcd/flux2/issues/1522
N/A
=> drop duplicate key name

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/templates/cronjob.yaml
For every CronJob, the CronJob Controller checks how many schedules it missed in the duration from its last scheduled time until now. If there are more than 100 missed schedules, then it does not start the job and logs the error. If the value is set, the cronjob will survive a cluster downtime.
See: https://access.redhat.com/solutions/3667021 and kubernetes/kubernetes#42649 for details
=> Fix for openshift-etcd-backup cronjob

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrade from v0.1 to v0.3
Release notes:
https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.3.0
https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.2.0
BREAKING CHANGES new helm chart repo URL and more stuff linked above!
Closes https://github.com/adfinis-sygroup/helm-charts/issues/345
Manual upgrade procedure in case of failure:
https://secrets-store-csi-driver.sigs.k8s.io/getting-started/upgrades.html#upgrades
=> feat(security-apps): upgrade secrets-store-csi-driver to 0.3.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrade from v17.1 to v18.0
Release notes:
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-17x-to-18x
Closes https://github.com/adfinis-sygroup/helm-charts/issues/335
As mentioned in [release notes](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-17x-to-18x), we need to update the CRDs manually before the upgrade
```bash
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.50.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.50.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
kubectl apply -f …
```
=> feat(infra-apps): upgrade kubePrometheusStack to 18.0.*

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/examples/metallb.yaml, charts/misc-apps/values.yaml
Updates `misc-apps/metallb` to use the official helm repo with chart version `0.10.*`
According to the [release notes](https://metallb.universe.tf/release-notes/#version-0-10-0) 
`You should be able to migrate from Bitnami Charts to MetalLB Charts by just changing the repo and upgrading.` 
But the values between the [bitnami chart](https://github.com/bitnami/charts/tree/master/bitnami/metallb) and the [official chart
](https://github.com/metallb/metallb/tree/main/charts/metallb) differs slightly so I suggest you review your own values before upgrading.
Fixes #341 
Fixes #365
=> chore(misc-apps): metallb use official helm repo

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/_helpers.tpl, charts/timed/values.yaml
Removes a duplicate `app.kubernetes.io/managed-by` label from _helpers.tpl and regenrates the docs with some small consistency fixes.
=> fix(timed): remove duplicate label and cleanup docs

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/cronjob-backend.yaml, charts/timed/templates/deployment-backend.yaml, charts/timed/templates/deployment-frontend.yaml, charts/timed/templates/job-dbmigrate.yaml
Sync timed in waves when using Argo CD:
* first wave deploys the database, secrets, configmaps, services and similar things
* second wave runs db migrations (as a `Sync` hook so they get run on each sync)
* third wave deploys (or updates) the backend and frontend Deployments as well as CronJobs (after the db has been created/migrated)
Fixes #12
=> fix(timed): use sync waves for db migrations

charts/cert-manager-monitoring/Chart.yaml, charts/cert-manager-monitoring/README.md, charts/cert-manager-monitoring/templates/prometheus/prometheusrule.yaml, charts/cert-manager-monitoring/values.yaml
Allow us to configure the `job` in the `CertManagerAbsent` alert to use something that is not `cert-manager`.
=> fix(cert-manager-monitoring): configurable job label for CertManagerAbsent

README.md, docs/README.md, docs/argocd-app-of-apps.md, hack/config/update-readme/README.md.gotmpl
This is the first part of the overarching changeset needed to properly document our `-apps` suffixed Argo CD app-of-apps charts as requested in #84. 
- Splits Argo CD app-of-apps charts into their own main README section ([demo](https://github.com/hairmare/helm-charts/tree/docs/app-of-apps#argo-cd-app-of-apps-charts))
- Adds initial docs/argocd-app-of-apps.md file ([demo](https://github.com/hairmare/helm-charts/blob/docs/app-of-apps/docs/argocd-app-of-apps.md))
- cleanup README to make all tables look nice when view through github ([demo](https://github.com/hairmare/helm-charts/tree/docs/app-of-apps))
After merging this, the `docs/argocd-app-of-apps.md` file can be collaboratively edited to adress the remaining tasks in #84, some of which will need further refinement before we are ready …
=> docs: initialise Argo CD app of apps documentation

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
We bumped by mistake the `appVersion` of this chart in this [commit](https://github.com/adfinis-sygroup/helm-charts/commit/bf617fc8f985566dfda9ad53abb0b18fd21ff35c#diff-c89b3823e7eba09ba99808c297e564d3acb63e3a775bbdcb36c743d5901ed4f7).
But there are no such image available which provides an error while deploying the chart.
Please see Dockerhub links:
* https://hub.docker.com/r/adfinissygroup/openshift-etcd-backup/tags?page=1&name=1.5.3
* https://hub.docker.com/r/adfinissygroup/openshift-etcd-backup/tags?page=1&name=1.5.2 (which is the latest)
* https://github.com/adfinis-sygroup/openshift-etcd-backup/releases
=> fix(openshift-etcd-backup): app-version should be 1.5.2

README.md, charts/sentry-apps/Chart.yaml, charts/sentry-apps/README.md
Deprecate the `sentry-apps` app of apps wrapper chart. Users can either use the [wrapped charts](https://github.com/sentry-kubernetes/charts) directly, Sentry SaaS or GitLab.
I will do a policy bypass to get this merged once approved, we do not want to put any effort into making CI green for this deprecation.
=> chore: mark sentry-apps as deprecated

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update kubernetes-event-exporter to 1.2.*
- Remove monitoring namespace from rbac-leader-election.yaml https://github.com/bitnami/charts/pull/8019
- Support multiple replicas https://github.com/bitnami/charts/pull/7917
- Bumps kubernetes-event-exporter to [release v0.11](https://github.com/opsgenie/kubernetes-event-exporter/releases/tag/v0.11)
=> feat(infra-apps): bump kubernetes-event-exporter to 1.2.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
- separate values for config reloader limit and request https://github.com/prometheus-community/helm-charts/pull/1375
- bump alertmanager to 0.23.0 https://github.com/prometheus-community/helm-charts/pull/1397
- bump thanos to 0.23.1 https://github.com/prometheus-community/helm-charts/pull/1397
- bump prometheus to 2.31.1 https://github.com/prometheus-community/helm-charts/pull/1397
- bump prometheus-operator to 0.52.0 https://github.com/prometheus-community/helm-charts/pull/1485
- bump promehtues-config-reloader to 0.52.0 https://github.com/prometheus-community/helm-charts/pull/1485
The prometheus-operator change contains a CRD update which argo cd
should sync where this is used.
=> feat(infra-apps): kube-prometheus-stack 21.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/dex-k8s-authenticator.yaml, charts/security-apps/templates/dex-k8s-authenticator.yaml, charts/security-apps/values.yaml
Due to gangway deprecation
FFI: https://github.com/heptiolabs/gangway#vmware-has-ended-active-development-of-this-project-this-repository-will-no-longer-be-updated
Gangway deprecation
=> feat(security-apps): Add dex-k8s-authenticator

.github/pull_request_template.md
Update the PR commit template to hint at running `pre-commit run` rather than `pre-commit run -a`.
=> docs: fix pre-commit command in pr template

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/backup-apps/Chart.yaml, charts/backup-apps/README.md, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md
This gets rid of the weirdly cargoculted `appVersion` in all `*-apps` charts. It's part of my "working towards infra-apps-1.0" series of recent refactors.
Sorry for the "size" of this PR, at least the change should not lead to any visible diffs for end users.
=> chore(*-apps): get rid of redundant version info

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/prometheus.yaml
Fixes the ingress annotation examples that i almost cargo-culted into the docs.
- https://github.com/adfinis-sygroup/helm-charts/pull/499#discussion_r777345794
=> fix(infra-apps): nginx annotation in ingress examples

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrade to [cert-manager 1.7](https://github.com/jetstack/cert-manager/releases/tag/v1.7.0)
Following their deprecation in version 1.4, the cert-manager API versions v1alpha2, v1alpha3, and v1beta1 have been removed.
Since release 1.7, `cmctl` can automatically migrate any deprecated API resources. See [Migrating Deprecated API Resources](https://cert-manager.io/docs/installation/upgrading/remove-deprecated-apis/). Basically you need to grab `cmctl` v1.7 and run `cmctl upgrade migrate-api-version` before the upgrade.
Special care most likely only needs to be taken when upgrading from <1.5. In any case you should also check that your pieline doesn't try to create any removed apis or it will fail.
=> feat(infra-apps): cert-manager 1.7

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
- Bump argo-cd to v2.2.3 and Redis to v6.2.6 https://github.com/argoproj/argo-helm/pull/1102
- Add custom volume as Helm working dir https://github.com/argoproj/argo-helm/pull/1103
=> feat(infra-apps): bump argocd from 3.31 to 3.32

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update kube-prometheus-stack to 31.0.*
This version removes the built-in grafana ServiceMonitor and instead relies on the ServiceMonitor of the sub-chart. `grafana.serviceMonitor.enabled` must be set instead of `grafana.serviceMonitor.selfMonitor` and the old ServiceMonitor may need to be manually cleaned up after deploying the new release.
- https://github.com/prometheus-community/helm-charts/pull/1652
=> feat(infra-apps): kube-prom-stack 31.0.*

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update to otel-collector chart 0.9:
- expose metrics for use with *monitor https://github.com/open-telemetry/opentelemetry-helm-charts/pull/99
- disable `minAvailable` and `maxUnavailable` in pdb by default https://github.com/open-telemetry/opentelemetry-helm-charts/pull/121
- add ingress for making collector available outside of cluster https://github.com/open-telemetry/opentelemetry-helm-charts/pull/92
if you already exposed the metrics on port 8888 manually then you need to take that into account when updating.
- Fixes #568
=> feat(tracing-apps): opentelemetry-collector 0.9

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update Vault Helm chart in security-apps to v0.19
* Vault image defaults to 1.9.2
* Vault K8s image defaults to 0.14.2
* Added configurable podDisruptionBudget for injector [GH-653](https://github.com/hashicorp/vault-helm/pull/653)
* Make terminationGracePeriodSeconds configurable for server [GH-659](https://github.com/hashicorp/vault-helm/pull/659)
* Added configurable update strategy for injector [GH-661](https://github.com/hashicorp/vault-helm/pull/661)
* csi: ability to set priorityClassName for CSI daemonset pods [GH-670](https://github.com/hashicorp/vault-helm/pull/670)
* Set the namespace on the OpenShift Route [GH-679](https://github.com/hashicorp/vault-helm/pull/679)
* Add volumes and env vars to helm hook test pod [GH-673](https://github.com/hashicorp/vault-helm/pull/673)
* Make …
=> chore(security-apps): update vault to v0.19

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Update chartmuseum Helm chart to v3.6
* Chartmuseum image updated to v0.14.0: https://github.com/chartmuseum/charts/pull/33
* Details about the v0.14.0 release can be found on the release page: https://github.com/helm/chartmuseum/releases/tag/v0.14.0
* `--enforce-semver2` flag has been deprecated: https://github.com/helm/chartmuseum/pull/522
* Schemes can be configured for liveness and readiness checks: https://github.com/chartmuseum/charts/pull/32
Fixes #563
=> chore(misc-apps): update chartmuseum to v3.6

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Bump to jaeger-operator 1.31.0
* https://github.com/jaegertracing/helm-charts/pull/342
* Fix panic caused by an invalid type assertion ([#1738](https://github.com/jaegertracing/jaeger-operator/pull/1738))
* Add ES autoprovisioning CR metric ([#1728](https://github.com/jaegertracing/jaeger-operator/pull/1728))
* Use Elasticsearch provisioning from OpenShift Elasticsearch operator ([#1708](https://github.com/jaegertracing/jaeger-operator/pull/1708))
=> feat(infra-apps): bump jaeger-operator to 2.29 (operator version 1.31)

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/examples/prom2teams.yaml, charts/misc-apps/examples/prometheus-msteams.yaml, charts/misc-apps/values.yaml
Add chart for prom2teams to forward Prometheus Alerts to Microsoft Teams using defined connectors
=> feature(misc-apps): Add prom2teams to send alerts to Microsoft Teams

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates velero to use version `2.28.*`
* https://github.com/vmware-tanzu/helm-charts/pull/347
Also adds minimum k8s v1.16+ restriction: https://github.com/vmware-tanzu/helm-charts/commit/abca6a9b38f8039135311c193a2fa680dc470d57
[upgrade-to-1.8](https://velero.io/docs/v1.8/upgrade-to-1.8/)
> Default backup storage location
> We have deprecated the way to indicate the default backup storage location. Previously, that was indicated according to the backup storage location name set on the velero server-side via the flag velero server --default-backup-storage-location. Now we configure the default backup storage location on the velero client-side. Please refer to the [About locations](https://velero.io/docs/v1.8/locations) on how to indicate which backup storage location is the default one.
> …
=> chore(velero): update to 2.28.*

.github/pull_request_template.md
This makes the PR template's wording about adding a description less ambiguous.
=> docs: make wording in pr template more clear

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates `infra-apps` to use [argocd chart](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd) version `4.0.*`
With the 4.0 release of the chart `controller.enableStatefulSet` is true per default to enable HA mode. If you want to keep using a deploymet you need to set it to false. 
Also both the ApplicationSet and Notifications controller are now deployed as part of Argo CD, this will need additional resources in the cluster. 
Please tune `applicationSet.metrics` and `applicationSet.resources` as well as `notifications.metrics`, `notifications.resources`, and (maybe) `notifications.argocdUrl` during this upgrade at the very least.
n/a
https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd#400-and-above
> The Argo CD Notifications and ApplicationSet are part of Argo …
=> chore(infra-apps): update argocd to 4.0.*

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/configmap-barman-backups.yaml, charts/barman/templates/deployment.yaml, charts/barman/values.yaml
Add additional Values for configuring container `volumeMounts` and deployment `volumes`.
This will be useful if you want to have pre/post scripts in Barman (configmaps).  
It templates the whole thing with toYaml. 
Furthermore I added `additionalConfiguration` to make all parameters from https://docs.pgbarman.org/release/2.19/barman.5.html available for configuring your barman instance. 
This will take a string + multiline string. So configuration would look like:
````
backups:
additionalConfiguration: |
pre_backup_script = "/path/to/your/script.py"
minimum_redundancy = 2
backups:
additionalConfiguration: "minimum_redundancy = 2"
````
=> feature(barman): Add additional conf options

charts/barman/Chart.yaml, charts/barman/README.md
Update barman to 2.19 after the upstream docker image was landed in https://github.com/ubc/barman-docker/commit/59f38742b9550b7f1466bff33e20a1632041d825.
Barman itself contains these changes from [2.19](https://pgbarman.org/barman-2-19-released/) and [2.18](https://pgbarman.org/barman-2-18-released/):
* Change `barman diagnose` output date format to ISO8601.
* Add Google Cloud Storage (GCS) support to barman cloud.
* Support `current` and `latest` recovery targets for the `--target-tli` option of `barman recover`.
* Add documentation for installation on SLES.
* Add snappy compression algorithm support in barman cloud (requires the optional python-snappy dependency).
* Allow Azure client concurrency parameters to be set when uploading WALs with `barman-cloud-wal-archive`.
* Add `--tags` …
=> feat(barman): update from 2.17 to 2.19

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/configmap-barman-cron.yaml, charts/barman/templates/deployment.yaml, charts/barman/values.yaml
Hello, creating a slot failed on our side because `ERROR: Unknown server 'pg'`.
I found it hardcoded in the cronjob. 
Wouldn't it be better to use the `postgres.host` value for creating the db slot?
Let me know what you think!
Best
````bash
barman.server ERROR: Check 'replication slot' failed for server 'xxxxxxx'
replication slot: FAILED (replication slot 'barman' doesn't exist. Please execute 'barman receive-wal --create-slot xxxxxxx')
directories: OK
retention policy settings: OK
````
=> fix(barman): Adjust slot-creation

charts/huawei-csi-plugin/.helmignore, charts/huawei-csi-plugin/Chart.yaml, charts/huawei-csi-plugin/README.md, charts/huawei-csi-plugin/ci/defaults-values.yaml, charts/huawei-csi-plugin/docs/INSTALL.md, charts/huawei-csi-plugin/templates/_helpers.tpl, charts/huawei-csi-plugin/templates/configmap.yaml, charts/huawei-csi-plugin/templates/daemonset-node.yaml, charts/huawei-csi-plugin/templates/deployment-controller.yaml, charts/huawei-csi-plugin/templates/rbac.yaml, charts/huawei-csi-plugin/templates/serviceaccount.yaml, charts/huawei-csi-plugin/values.yaml, hack/chart-testing/ct-install.yaml
Readds the `huawei-csi-plugin` so we can add an annotation to stop artifacthub from sending us trivy mails. I'll remove it once again when trivy stops sending us security reports for the outdated, unscannable csi-attacher image.
* https://github.com/artifacthub/hub/issues/1882
=> chore(huawei-csi-plugin): annotate image to disable security scanning

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap, charts/mopsos/values.yaml
The database password needs to be in `secureJson` for it to get picked up and the datasources apiVersion is an int and not a string.
=> fix(mopsos): use secureJson for the datasource

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Update filebeat to 7.17.*
- https://github.com/elastic/helm-charts/pull/1610 (https://github.com/elastic/helm-charts/commit/33a2829a181889a740e5afde46d1cba10124f89a)
- https://github.com/elastic/helm-charts/pull/1632
- https://github.com/elastic/helm-charts/pull/1602
- https://github.com/elastic/helm-charts/pull/1604
FFI: https://github.com/elastic/helm-charts/blob/main/CHANGELOG.md
Closes https://github.com/adfinis-sygroup/helm-charts/issues/664
n/a
=> feat(logging-apps): Bump filebeat to 7.17

charts/argoconfig/Chart.yaml, charts/argoconfig/README.md, charts/argoconfig/templates/_appProject.yaml
The `argoconfig.appProject` template currently defaults to allowing way to much. It should allow starting from a minimal set of allowlist and other rights. This removes most of the insane defaults while forcing downstream users to explicitly configure all the things.
=> fix(argoconfig): no defaults in appProject resources

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/pvc.yaml, charts/barman/values.yaml
Allow specifying annotations on both the backup and recovery PVC. 
This can be used to set any annotations on the PVC (ie. a resource policy as described in #644
```yaml
persistence:
data:
annotations:
helm.sh/resource-policy: keep
```
* Fixes #644
=> feat(barman): add optional annotations to PVCs

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Removes the trailing slash in the NeuVector Helm chart repos since those always clash with appprojects.
=> fix(security-apps): remove trailing slash in neuvector chart repo

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update `kube-promtheus-stack` from `v35.0` to `v36.0`
- Updates `kube-state-metrics` from v4.7 to v4.9
- Updates `prometheus-node-exporter` from v3.1 to v3.3
- Updates `prometheus-operator` and `prometheus-config-reloader` image from v0.56.3 to v0.57.0
- Updates `prometheus` image from v2.35.0 to v2.36.1
- Updates `prometheis-exporter` from v4.12 to v4.13
In order to upgrade `kube-prometheus-stack` from `v35.0` to `v36.0` we need to do this before triggering the upgrade:
FFI: https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-35x-to-36x
```
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.57.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl apply …
```
=> chore(infra-apps): Update kube-prometheus-stack to v36.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
With this release kured will retry to cordon and uncordon a node in case it fails.
This should prevent nodes from being "Unschedulable" forever. Also kured will hold the node-lock until uncordoning
and the lock-release succeeded to avoid reproducing the same issue everywhere. See [#486](https://github.com/weaveworks/kured/pull/486)
for more details.
* https://github.com/weaveworks/kured/pull/496
* https://github.com/weaveworks/kured/pull/486
* https://github.com/weaveworks/kured/pull/541
* https://github.com/weaveworks/kured/issues/553
* https://github.com/weaveworks/kured/pull/550
* https://github.com/weaveworks/kured/pull/539
* https://github.com/weaveworks/kured/pull/543
* https://github.com/weaveworks/kured/pull/562
* …
=> feat(infra-apps): update kured from 2.14 to 2.15

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update vault from `0.19.*` to `0.20.1`
* Fixes https://github.com/adfinis-sygroup/helm-charts/issues/717
* vault-k8s updated to 0.16.1 https://github.com/hashicorp/vault-k8s/releases [GH-739](https://github.com/hashicorp/vault-helm/pull/739)
* Vault default image to 1.10.3 https://github.com/hashicorp/vault/blob/main/CHANGELOG.md 
* CSI provider default image to 1.1.0 https://github.com/hashicorp/vault-csi-provider/releases/tag/v1.1.0
* Earliest Kubernetes version tested is now 1.16
* Helm 3.6+ now required
* global.enabled now works as documented, that is, setting global.enabled to false will disable everything, with individual components able to be turned on individually [GH-703](https://github.com/hashicorp/vault-helm/pull/703)
* Default value of - used for injector and server to …
=> feat(security-apps): update vault from 0.19.* to 0.20.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
The 2.16.0 update to the **kured** chart adds support for passing the `--message-template-uncordon` flag that can be used to override the message being used to report sucess after a reboot and uncordon.
* https://github.com/weaveworks/kured/pull/589
=> feat(infra-apps): upgrade kured from 2.15 to 2.16

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
'''opentelemetry-collector''' 0.20.2 adds support for both `policy/v1` and `policy/v1beta1` in PodDisruptionBudget resources.
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/241
=> fix(tracing-apps): upgrade opentelemetry-collector from 0.20.1 to 0.20.2

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/stackrox.yaml, charts/security-apps/values.yaml
The 70.0.0 version that is commited to the stackrox helm repo isn't what is actually published to the chart repo so we  update our deployment to use the published version. Also updates the examples with what i've learned about stackrox so far.
=> fix(security-apps): use existing stackrox chart version

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
The 4.10 chart truncates labels if they are too long for K8s. I'm tagging this as a fix and not a feat since adding support for sha sums in images IMHO isn't a new feature but rather a fix for a bug.
The change shouldn't affect our envs since we haven't tried to use sha sums so far.
* https://github.com/argoproj/argo-helm/pull/1368
=> fix(infra-apps): update argo-cd from 4.9 to 4.10

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Updates tzdata, curl, libcurl, and systemd-libs.
* [CVE-2022-32206](https://access.redhat.com/security/cve/CVE-2022-32206)
* [CVE-2022-2526](https://access.redhat.com/security/cve/CVE-2022-2526)
The linked CVEs are about fixing the recent use-after-free in systemd. The curl patches are apotential  malloc bomb that probably doesn't affect this image. The use-after-free in systemd has been classfied as important by Red Hat scoring a 8.8 on the CVSS v3 scale.
* https://github.com/adfinis/openshift-etcd-backup/pull/36
=> fix: update openshift etcd backup from 1.6.4 to 1.6.5

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Updates the Argo Rollout chart and gives us more control over cluster-role creation as well as the ability to manage secrets in an initContainer.
* https://github.com/argoproj/argo-helm/pull/1410
* [Added]: initContainer option to controller pod, updated secrets roles
* https://github.com/argoproj/argo-helm/pull/1388
* [Added]: flags to disable the creation of ClusterRoles/ClusterRoleBindings when run in cluster mode
=> feat(argo-apps): update argo-rollouts from 2.18 to 2.20

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrade Dex Helm chart to the newest version
* Dex now provides a fallback when groups is a string instead of a list: https://github.com/dexidp/dex/pull/2639
=> feat(security-apps): upgrade dex to 2.34

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates the Argo CD Helm chart from 4.10 to 5.4. The changes are summarized below.
The most important change that affects us is the one leading to the 5.x release. YOu can check if you need to do anything with the following steps:
* Check if `kubectl -n infra-argocd get deployments` returns `argocd-server`, if it does this deployment will change it to a StatefulSet for HA purposes.
* Check if `configs.repositories` is set, if it is, some manual intervention will be needed
* Check if `configs.repositoryCredentials` is set, if it is, some manual intervention will be needed
* Check if `server.additionalApplications` or `server.additionalProjects` are used, if they are, intervention is needed.  I will prepare a follow-up PR that prepares to use `argocd-apps` in cases where we are affected.
A …
=> feat(infra-apps): update argo-cd from 4.10 to 5.4

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates KubePrometheuStack to `40.1.*`
Fixes [CVE-2021-39226](https://github.com/grafana/grafana/security/advisories/GHSA-69j6-29vr-p3j9)
* Several bugfixes
* No breaking changes
* https://github.com/prometheus-operator/prometheus-operator/pull/4962
* https://github.com/prometheus-operator/prometheus-operator/pull/4898
* https://github.com/prometheus-operator/prometheus-operator/pull/4622
* https://github.com/prometheus-operator/prometheus-operator/pull/4863
* https://github.com/prometheus-operator/prometheus-operator/pull/4881
* https://github.com/prometheus-operator/prometheus-operator/pull/4834
* https://github.com/prometheus-operator/prometheus-operator/pull/4868
* https://github.com/prometheus-operator/prometheus-operator/pull/4840
* …
=> chore(kps): update to 40.1.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrade dex to 2.35
* Dex 2.35 fixes a security vulnerability in dex: https://github.com/dexidp/dex/security/advisories/GHSA-vh7g-p26c-j2cw
* When using the Google connector, you need to upgrade to 2.35.1 (included in version 0.12.0 of the Helm chart)
=> feat(security-apps): update dex chart to 0.12.0

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/deployment-backend.yaml, charts/timed/values.yaml
Overwrite the default failureThreshold to give the timed-backend app some time to come up and prevent
it from startup-loop
=> fix(timed-backend): increase startup probe failture threshold

charts/security-apps/Chart.lock, charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
updates vault chart version to 0.22.0
#800
* https://github.com/hashicorp/vault-helm/pull/771
* https://github.com/hashicorp/vault-helm/pull/744
* https://github.com/hashicorp/vault-helm/pull/745
* https://github.com/hashicorp/vault-helm/pull/767
* https://github.com/hashicorp/vault-helm/pull/750
* https://github.com/hashicorp/vault-helm/pull/610
* https://github.com/hashicorp/vault-helm/pull/753
* https://github.com/hashicorp/vault-helm/pull/784
* https://github.com/hashicorp/vault-helm/pull/785
=> chore(security/vault): update to 0.22.0

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
updates ceph-csi applications to use 3.7.x version of the chart
#803
#804
* NFS
* Added support for volume expansion, snapshot, restore and clone.
* Added NFS nodeserver within CephCSI with support for pod networking with nsenter.
* Support enabling PV and snapshot metadata on the RBD images and CephFS subvolumes
* For persistent volumes, clones and volume restores we support adding PVName/PVCName/PVCNamespace and ClusterName details
* For snapshot volumes we support adding snapshot-name/snapshot-namespace/snapshotcontent-name and ClusterName details
* Shallow Read Only support for Ceph CSI driver:
* cephfs-csi expose CephFS snapshots as shallow, read-only volumes, without needing to clone the underlying snapshot data (https://github.com/ceph/ceph-csi/blob/devel/docs/design/proposals/cephf …
=> chore(storage/ceph-csi): update to 3.7.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update cert-manager to 1.10.0
Nothing spectacular has been included in this release: https://github.com/cert-manager/cert-manager/releases/tag/v1.10.0
The new metrics introduced in https://github.com/cert-manager/cert-manager/pull/5461 could potentially be relevant for environments where multiple issuer are being used.
=> chore(infra-apps): update cert-manager to 1.10.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Update Argo CD from 2.4 to 2.5
* Move argocd-cm and argocd-rbac-cm to config section
* https://github.com/argoproj/argo-helm/pull/1568
* https://github.com/argoproj/argo-helm/pull/1582
* https://github.com/argoproj/argo-helm/pull/1528
=> feat(infra-apps): Update Argo CD chart from 5.6 to 5.8

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/templates/deployment-backend.yaml, charts/timed/values.yaml
This adds the `HURRICANE_REQ_QUEUE_LEN`  environment variable to timed-backend's deployment
=> feat(timed-backend): add env vars to configure hurricane

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update the ubi8 base image used for openshift-etcd-backup from 8.6-902.1661794353 to 8.6-994.
* https://github.com/adfinis/openshift-etcd-backup/pull/37
* https://github.com/adfinis/openshift-etcd-backup/releases/tag/v1.6.6
=> fix(openshift-etcd-backup): update from 1.6.5 to 1.6.6

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Most contains a bunch of low-level fixed and updates to components like grafana, kube-state-metrics, prometheus-node-exporter, and helm.
This version upgrades Prometheus-Operator to v0.60.1, Prometheus to v2.39.1 and Thanos to v0.28.1.
This version also upgrades the Helm charts of kube-state-metrics to 4.20.2, prometheus-node-exporter to 4.3.0 and Grafana to 6.40.4.
Run these commands to update the CRDs before applying the upgrade.
```console
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.60.1/example/prometheus-operator-crd/monitoring.coreo …
```
=> feat(infra-apps): upgrade kube-prometheus-stack from 40.1 to 41.7.4

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update otel-collector to the latest version. Bumps actual collector version from 0.53.0 to 0.63.1 and chart has a buch of changes described below. The main change is that the config needs updating to use the new `mode` value.
See otel-collector's [UPGRADING.md](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md) for up2date data.
The chart now supports templating in `.Values.config`.  If you are currently using any `{{ }}` syntax in `.Values.yaml` it will now be rendered.  To escape existing instances of `{{ }}`, use ``` {{` <original content> `}} ```.  For example, `{{ REDACTED_EMAIL }}` becomes ``` {{` {{ REDACTED_EMAIL }} `}} ```.
Resource `limits` have been reduced. Upgrades/installs of chart 0.29.0 will now use fewer …
=> feat(logging-apps): update otel-collector from 0.20.2 to 0.38.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update kubeEventExporter to  v1.5.*
- Replace [upstream repo](https://github.com/bitnami/charts/commit/a8dde0bbfc671c3677cef027bd9c8fd13d1ec714)
- Add support for [image digest apart from tag](https://github.com/bitnami/charts/commit/2c50c5d75095dc0332caead87154d852febeff11)
n/a
Closes https://github.com/adfinis/helm-charts/issues/794
=> chore(kube-event-exporter): Update to 1.5.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Upgrade NGINX to 1.21.6
* Upgrade Golang 1.19.2
* Fix Service Name length Bug [9245](https://github.com/kubernetes/ingress-nginx/pull/9245)
* CVE fixes CVE-2022-32149, CVE-2022-27664, CVE-2022-1996
updates ingress-nginx to use Endpointslices instead of Endpoints. Thank you, @tombokombo, for your work in
[8890](https://github.com/kubernetes/ingress-nginx/pull/8890)
* Update to Prometheus metric names, more information [available here]( https://github.com/kubernetes/ingress-nginx/pull/8728
)
* Deprecated Kubernetes versions 1.20-1.21, Added support for, 1.25, currently supported versions v1.22, v1.23, v1.24, v1.25  
ADDED
* `_request_duration_seconds` Histogram
* `_connect_duration_seconds` Histogram
* `_header_duration_seconds` Histogram
* `_response_duration_seconds` Histogram
Updated
* …
=> feat(infra-apps): upgrade ingress from 4.2.* to 4.4.0

.github/pull_request_template.md
We agreed on creating a `artifacthub.io/changes` style changelog when updating the helm charts. So we want to reflect this in the PR template checklist.
No issue was created for this, since it’s a veeeery small change.
=> Update PR template adding the changelog as todo

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update gatekeeper to version 3.10.0
- https://github.com/open-policy-agent/gatekeeper/pull/2305
- https://github.com/open-policy-agent/gatekeeper/pull/2249
- https://github.com/open-policy-agent/gatekeeper/pull/2062
- https://github.com/open-policy-agent/gatekeeper/pull/2198
- https://github.com/open-policy-agent/gatekeeper/pull/2289
- https://github.com/open-policy-agent/gatekeeper/pull/2276
- https://github.com/open-policy-agent/gatekeeper/pull/2277
- https://github.com/open-policy-agent/gatekeeper/pull/2206
- https://github.com/open-policy-agent/gatekeeper/pull/2205
- https://github.com/open-policy-agent/gatekeeper/pull/2202
- https://github.com/open-policy-agent/gatekeeper/pull/2220
- https://github.com/open-policy-agent/gatekeeper/pull/2231
- …
=> chore(gatekeeper): update to 3.10.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
This version upgrades Prometheus-Operator to v0.62.0, Prometheus to v2.41.0 and Thanos to v0.30.1.
Run these commands to update the CRDs before applying the upgrade.
```console
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.62.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.62.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.62.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
kubectl apply --server-side -f …
```
=> feat(infra-apps): update kube-prometheus-stack from 42.1.0 to 44.2.1

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
The main reason for this change is various security patches that i've linked in the issues section below.
* https://github.com/argoproj/argo-cd/security/advisories/GHSA-q9hr-j4rf-8fjc
* https://github.com/argoproj/argo-cd/security/advisories/GHSA-6p4m-hw2h-6gmw
* CVE-2022-3996: https://github.com/argoproj/argo-helm/pull/1803
=> feat(infra-apps): Update argo-cd chart from 5.17.4 to 5.19.12 (contains argo-cd security patches!)

CODEOWNERS
Make GitHub assign members of the newly created dev-devops team for review on timed and osschallenge Helm charts.
=> chore: add dev-devops group to CODEOWNERS for timed and osschallenge charts

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Switches to registry.k8s.io instead of k8s.gcr.io and also fixes a tiny URL validation issue in the helm URL among other small changes described in the releasenotes.
* https://github.com/argoproj/argo-cd/releases/tag/v2.6.3
=> feat(infra-apps): update argo cd from 2.6.2 to 2.6.3

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Mainly adds official 2.24 support by bumping the operator after the chart having missed a couple of version bumps.
=> feat(tracing-apps): update jaeger-operator from 1.39.0 to 1.42.0

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Update ceph-csi in storage-apps to 3.8.0
This release provides the following new features:
- fscrypt support for [RBD](https://github.com/ceph/ceph-csi/pull/3310) and [CephFS](https://github.com/ceph/ceph-csi/pull/3460)
A potential issue for one of our customers, which is still running Octopus could be that ceph-csi is following the upstream support for Ceph releases and because of that they officially removed support for Octopus in this release of ceph-csi. As this is the only customer were we're using ceph-csi we could also potentially remove it from storage-apps?
=> chore(storage-apps): update ceph-csi to 3.8.0

.github/workflows/test.yaml, docs/development.md, hack/chart-testing/ct.yaml, hack/update-snapshots.sh
Gets rid of the no `--helm3` arg error.
* https://github.com/quintush/helm-unittest/issues/124
=> fix(ci): move to new (old) home of helm-unittest and get rid of helm2 support

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrades Prometheus-Operator to v0.63.0, Prometheus to v2.43.0 and Thanos to v0.30.2.
The main feature is alpha support for the new `PrometheusAgent` CRD + a  bunch of bugfixes and updates to several bundled components.
=> feat(infra-apps): update kube-prometheus-stack from 44.3.0 to 45.9.1

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Adds a bunch of features to the chart, starts supporting workload identities on google, and allows templating the oauth2-proxy config through helm templating.
=> feat(security-apps): update oauth2-proxy chart from 6.5.0 to 6.10.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update cert-manager from 1.11.1 to 1.12.0: https://github.com/cert-manager/cert-manager/releases/tag/v1.12.0
New features:
- Add imagePullSecrets for AMCE http01 solver pod: https://github.com/cert-manager/cert-manager/pull/5801
- Vault issuer can now use a serviceAccountRef instead of relying on static service account tokens: https://github.com/cert-manager/cert-manager/pull/5502
=> feat(infra-apps): update cert-manager from 1.11.1 to 1.12.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml
Updates mimir-distributed Helm chart to the most recent release
Check if your setup requires [zone aware replication[(https://grafana.com/docs/mimir/latest/configure/configure-zone-aware-replication/) and disable it if not required (`ingester.zoneAwareReplication.enabled=false`, `store_gateway.zoneAwareReplication.enabled=false`).
Additionally verify that your Mimir deployment used `structuredConfig` instead of `config`, otherwise the upgrade might fail.
=> infra-apps: update mimir-distributed

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
I forgot to actually update mimir-distributed in the previous PR #1060. This is the follow-up to bump
Check if your setup requires [zone aware replication[(https://grafana.com/docs/mimir/latest/configure/configure-zone-aware-replication/) and disable it if not required (`ingester.zoneAwareReplication.enabled=false`, `store_gateway.zoneAwareReplication.enabled=false`).
Additionally verify that your Mimir deployment used structuredConfig instead of config, otherwise the upgrade might fail.
=> infra-apps: actually update mimir-distributed

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml, hack/update-snapshots.sh
Bump nginx-ingress to 4.7.1 (latest at the time of writing this)
=> Bump nginx ingress to 4.7.1

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
We bump secrets-store-csi-driver to 1.3.4.
Refers to [CVE-2023-2878](https://discuss.kubernetes.io/t/security-advisory-cve-2023-2878-secrets-store-csi-driver-discloses-service-account-tokens-in-logs/24336).
=> feat(security-apps): bump secrets-store-csi-driver to 1.3.3

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.2.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
I'm housekeeping cert-manager. The patch release fixes a memory leak that doesn't have much impact based on our current usage patterns but still wants stomping.
=> feat(infra-apps): update cert-manager from 1.12.2 to 1.12.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump infra-apps to 0.173.0 for KPS to 49.2.0 and use `ServerSideApply` for Argo CD Sync Policy in KPS.
=> feat(infra-apps): bump infra-apps to 0.173.0 to upgrade KPS to 49.2.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD from 2.8.3 to 2.8.4, fixes some small issues like making managed namespaces more 'prune-proof' and supporting `:` in annotations.
=> feat(infra-apps): Update Argo CD from 2.8.3 to 2.8.4

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Contains a bunch of bugfixes and quite some refactoring
=> feat(misc-apps): Update OpenCost from 1.103.1 to 1.105.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes a name collision bug in StableCertificateRequestName feature for CertificateRequests.
=> feat(infra-apps): Update cert-manager from 1.13.0 to 1.13.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update kured from 4.2.0 to 5.2.0
https://github.com/adfinis/helm-charts/issues/1113
=> feat(infra-apps): Update kured from 4.2.0 to 5.2.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrade ingress-nginx chart to 4.8.3 to update the `ingress-nginx` image to 1.9.4 to fix CVEs CVE-2023-5043 & CVE-2023-5044.
=> fix(infra-apps): upgrade ingress-nginx chart to 4.8.3

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
List of changes: https://github.com/stackrox/stackrox/blob/master/CHANGELOG.md#420
* None
=> Feat/security apps/update stackrox 4.2.2

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Pin metallb to a version instead of wildcarding it's patch version.
=> chore(misc-apps): pin metallb to 1.13.11 instead of wildcarding the patch version

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Bump openshift-etcd-backup image to v1.6.17, which uses the newly released RHEL 8.9 base image.
=> chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.6.17

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Velero to 5.1.4 Helm Chart
Fixes #1112
=> feat(velero): bump helm chart from 4.0.2 to 5.1.0

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/ci/default-values.yaml, charts/azure-apps/examples/azure-workload-identity-webhook.yaml, charts/azure-apps/templates/azure-workload-identity-webhook.yaml, charts/azure-apps/values.yaml
Also deploying the `azure-workload-identity-webhook` via `azure-apps`.
https://azure.github.io/azure-workload-identity
=> feat(azure-apps): introduce azure-workload-identity-webhook deployment

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Prometheus and Grafana and contains several fixes to ServiceMonitors and included dashboards. Some of the countless fixes are also security relevant, mainly because they patch dependencies.
=> feat(infra-apps): Update kube-prometheus-stack chart from 51.2.0 to 54.2.2

.github/workflows/release.yaml
Add `skip_existing` to chart-releaser action to allow us to re-run the release action.
=> ci(release): add skip_existing to chart-releaser action

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
- Update Loki to 2.9.3
- Update Loki Helm chart to 5.41.4
=> chore(logging-apps): update Loki to 2.9.3 / Loki chart to 5.41.4

charts/argoconfig/Chart.yaml, charts/argoconfig/README.md, charts/argoconfig/templates/_application.yaml
This PR removes the empty syncPolicy from the application template. This change is needed because when you don't specify a syncPolicy in one of the helm-charts which use argoconfig, it will put just the empty syncPolicy in it. It seems like argoCD removes the empty value, which can be seen here:
```bash
time="2024-01-11T17:04:51Z" level=info msg="Refreshing app status (comparison expired, requesting refresh. reconciledAt: 2024-01-11 16:58:51 +0000 UTC, expiry: 3m0s), level (2)" application=infra-argocd/app-stackrox-secured-cluster-services
time="2024-01-11T17:04:51Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: infra-stackrox)" application=infra-argocd/app-stackrox-secured-cluster-services
time="2024-01-11T17:04:51Z" level=info msg="getRepoObjs …
```
=> fix(argoconfig): Remove empty syncPolicy from application template

charts/argo-apps/Chart.lock, charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/azure-apps/Chart.lock, charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/backup-apps/Chart.lock, charts/backup-apps/Chart.yaml, charts/backup-apps/README.md, charts/infra-apps/Chart.lock, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/logging-apps/Chart.lock, charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/misc-apps/Chart.lock, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/security-apps/Chart.lock, charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/storage-apps/Chart.lock, charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/tracing-apps/Chart.lock, charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md
This PR updates the dependencies of argoconfig to argoconfig 0.9.1. This change is needed because when no syncPolicy is defined, it will be set to null what argoCD removes but because of this the application goes out-of-sync. For more informations about this take a look at https://github.com/adfinis/helm-charts/pull/1172.
=> fix(*-apps): Update argoconfig dependency

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes CVE-2023-44487 (Rapid Reset).
=> feat(infra-apps): Update ingress-nginx from 1.9.4 to 1.9.5

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
=> feat(logging-apps): Update loki chart from 5.41.4 to 5.41.8

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Security patches to prevent DOS and rate limiting bypasses.
* GHSA-x32m-mvfj-52xv
* GHSA-6v85-wr92-q4p7
* GHSA-2vgg-9h6w-m454
=> feat(infra-apps): Update Argo CD from 2.10.3 to 2.10.4

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update backend to v3.0.15

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Better sharding, multi-source apps, more HA possibilities... Have a look at the [RC blog post](https://blog.argoproj.io/argo-cd-v2-11-release-candidate-b83ba3008ba5).
No breaking changes apart from maybe this:
> The application controller is now available as a StatefulSet when the controller.enableStatefulSet flag is set to true. Depending on your Helm deployment this may be a downtime or breaking change if enabled when using HA and will become the default in 3.x.
=> feat(infra-apps): Update Argo CD from 2.10.9 to 2.11.0

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Update azureKvCsiProvider from 1.4.1 to 1.5.4
- [fix: Handles the case where the optional leaf SKI is missing](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.5.2)
- [chore: bump golang.org/x/net from 0.17.0 to 0.24.0](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.5.2)
- [security: CVE-2024-24786: bump google.golang.org/protobuf to v1.33.0](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.5.2)
- [chore: bump golang.org/x/crypto from 0.14.0 to 0.18.0](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.5.1)
- [bump from v1.4.1 to v1.5.0](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.5.0)
* fixes #1237
=> chore(azure-apps): Bump azureKvCsiProvider to v1.5.4

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Update fluentbit chart to 0.46.7
* Update fluent-bit from 2.1.10 to 3.0.4
=> This fixes [CVE-2024-4323](https://github.com/fluent/fluent-bit/security/advisories/GHSA-5rjf-prwh-pp7q) (Critical 9.8, Memory Corruption, can be triggered via network)
* Updated the ServiceMonitor path to use the v2 metrics
* Support setting Service's externalIPs.
* Support setting extraContainers to a string value to enable full templating.
* Added support for ingress.annotations tpl rendering
* Added local internalTrafficPolicy for daemonsets
* Create unqiue uid for grafana fluent-bit dashboard.
* Changed default image pull policy to IfNotPresent in values.yaml
* Fixed helm tests.
* Replaced statically configured datasource with placeholder in grafana dashboard json
#1253
=> chore(fluentbit): update fluentbit to 0.46.7

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes #1248
Updates Grafana Mimir Helm Chart to 5.3.0 and Mimir to version 2.12.0
* https://github.com/grafana/mimir/pull/5327
* https://github.com/grafana/mimir/pull/5357
* https://github.com/grafana/mimir/pull/6673
* https://github.com/grafana/mimir/pull/5666
* https://github.com/grafana/mimir/pull/6389
* https://github.com/grafana/mimir/pull/6786
* https://github.com/grafana/mimir/pull/7559
* https://github.com/grafana/mimir/pull/7125
* https://github.com/grafana/mimir/pull/6860
* https://github.com/grafana/mimir/pull/7143
* https://github.com/grafana/mimir/pull/7269
* https://github.com/grafana/mimir/pull/7298
* https://github.com/grafana/mimir/pull/7361
* https://github.com/grafana/mimir/pull/7778
Rest are features, enhancements or bugfixes, …
=> chore(mimir): update to 5.3.0

README.md, charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/ci/default-values.yaml, charts/keycloak-operator/ci/operand-values.yaml, charts/keycloak-operator/templates/NOTES.txt, charts/keycloak-operator/templates/operator/clusterrole.yaml, charts/keycloak-operator/templates/operator/deployment.yaml, charts/keycloak-operator/templates/operator/rolebinding.yaml, charts/keycloak-operator/templates/operator/roles.yaml, charts/keycloak-operator/templates/operator/service.yaml, charts/keycloak-operator/templates/operator/serviceaccount.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Included property for disabling operator templates generation, same procedure as the one already available for enabling/disabling keycloak templates.
https://github.com/adfinis/helm-charts/issues/1270
=> [issue 1270] Feature: disable operator templates generation

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/templates/operator/deployment.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
fix: change from operator. to kc.operator. keys
Keycloak Operator change:
https://github.com/keycloak/keycloak/commit/77581d25278b6819a5cbc802943764557a366c2f
https://github.com/keycloak/keycloak/pull/26414
Source code:
https://github.com/keycloak/keycloak/blob/release/24.0/operator/src/main/resources/application.properties#L8
Operator use  be default keycloak nightly version, because environment variable `OPERATOR_KEYCLOAK_IMAGE` was renamed to `KC_OPERATOR_KEYCLOAK_IMAGE`.
* [ X] I am ready to test changes after they are applied and released
=> fix: change from operator. to kc.operator. keys

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
A ton of updates to otel-collector.
=> feat(tracing-apps): Update otel-collector from 0.82.0 to 0.101.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates Mimir Chart to version 5.4.0, Mimir to version 2.13.0
* A number of timeout settings are improved:
* Fine-tuned termination grace periods for all components. This helps to ensure that components can shut down gracefully, without interrupting queries or write requests.
* Continuous test and smoke test containers now use the Mimir image, as the continuous test code is now part of Mimir. As a result, the image section in the values file now replaces smoke_test.image and continuous_test.image, and the latter two are removed.
* Notable enhancements are as follows:
* Experimental support for a dedicated ruler query path. With a dedicated set of queriers, query-frontends, and query-schedulers, outages and slow-downs on the main query path don’t affect rule evaluations.
* In Grafana Mimir …
=> chore(mimir): update chart/5.4.0 / app/2.13.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Bump security-apps to integrate vaultMonitoring latest changes
=> chore(vaultMonitoring): Bump vaultMonitoring to add alertrules

charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/values.yaml
fix vault monitoring prometheusrules, remove labels
=> fix(vault-monitoring): Remove labels

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Updates to the latest keycloak patch release and makes the backchannelDynamic flag truly optional.
=> fix: optional backchannelDynamic and update to 25.0.4

.github/pull_request_template.md
Fix link to Changelog-docs in PR template.
This checklist is not really applicable for this PR.
=> chore: fix link in PR template

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/templates/operator/deployment.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap, charts/keycloak-operator/values.yaml
Allows for setting annotations like `argocd.argoproj.io/sync-wave` on the operator deployment.
=> feat: Add operator.deploymentAnnotation value

charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/templates/service.yaml, hack/chart-testing/ct.yaml
Only create the service when `serviceMonitor.create` is set. The service is useless otherwise.
Background: I have a project where I can only use the `prometheusRules.enabled=true` but only want to use the prometheus rules, not the service monitor. Also, it creates a conflict in our deployment, because we already have a similar service with that name `vault-monitoring`.
=> Only create service with serviceMonitor

charts/hedgedoc/Chart.yaml, charts/hedgedoc/README.md, charts/hedgedoc/templates/deployment.yaml, charts/hedgedoc/values.yaml
This PR adds an option to customize the liveness and readiness probes in the hedgedoc chart.
=> feat(hedgedoc): customize liveness and readiness probes

charts/kubernetes-etcd-backup/Chart.yaml, charts/kubernetes-etcd-backup/README.md
v1.2.0 previous tag did not exist, we now use the correct one.
=> chore(kubernetes-etcd-backup): bump appVersion to 1.2.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Feature update for cert-manager. Adds a JSON schema for cert-manager's values and more.
=> feat(infra-apps): Update cert-manager from 1.15.1 to 1.16.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Dot 1 release for cert-manager 1.16.0, fixes. Makes cert-manager's ACME ClusterIssuer to look in the right namespace for resources required for the issuance (e.g. credential Secrets) again.
=> fix(infra-apps): Update cert-manager from 1.16.0 to 1.16.1

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Update the chart to the recently released [26.0.1](https://www.keycloak.org/2024/10/keycloak-2601-released) version of Keycloak and the operator.
=> fix(keycloak-operator): Update from 26.0.0 to 26.0.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update mimir chart from 5.4.0 to 5.5.1 and mimir from 2.13.0 to 2.14.0
Possibly relevant changes for Mimir 2.14.0
- Compactor adds a new `cortex_compactor_disk_out_of_space_errors_total` counter metric that tracks how many times a compaction fails due to the compactor being out of disk.
- The streaming of chunks from store-gateways to queriers is now enabled by default.
- The distributor now replies with the `Retry-After` header on retriable errors by default.
- Incoming OTLP requests were previously size-limited with the distributor's `-distributor.max-recv-msg-size` configuration.
The distributor has a new `-distributor.max-otlp-request-size` configuration for limiting OTLP requests. The default value is 100 MiB.
- Ingesters can be marked as read-only as part of their downscaling …
=> chore(infra-apps): update mimir chart from 5.4.0 to 5.5.1

charts/kubernetes-etcd-backup/Chart.yaml, charts/kubernetes-etcd-backup/README.md, charts/kubernetes-etcd-backup/templates/cronjob.yaml
This PR sets the `concurrencyPolicy` for the `CronJob` in `kubernetes-etcd-backup` to `Forbid`, meaning we don't try to start a new Job while the old one is still running. In case it is, the new Job is skipped.
=> fix(etcd-backup): disallow concurrent job runs

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
=> fix(keycloak): don't quote poolMinSize value

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
FFI: https://git.adfinis.com/ch-cloudnative/team-coordination/-/issues/519
=> chore(storage-apps): Bump minio due to CVE-2024-55949

charts/cert-manager-monitoring/Chart.yaml, charts/cert-manager-monitoring/README.md, charts/cert-manager-monitoring/templates/prometheus/prometheusrule.yaml
Introduce critical severity for CertManagerCertExpirySoon when cert will expire in less then 10 days
=> feat(cert-manager-monitoring): introduce critical severity for CertManagerCertExpirySoon alert

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/templates/argocd-notifications.yaml, charts/argo-apps/values.yaml
The feture was merged into the main Argo CD application and we deprecated the component more than 12 months ago.
=> chore(argo-apps): Remove deprecated argocd-notifications component

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/templates/gangway.yaml
Gangway has been marked as deprecated for more than 6 months and now is the time to make it fail.
=> chore(security-apps): Fail deprecated gangway installations

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/templates/loki-stack.yaml
The loki-stack installation has been marked as deprecated for more than 6 months and it gets to fail now.
=> chore(logging-apps): Fail deprecated loki-stack installations

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update kube-prometheus-stack to get prometheus-operator v0.82, which includes a fix for `metric_name_validation_scheme` not being rendered.
- https://github.com/prometheus-operator/prometheus-operator/pull/7414
=> feat(infra-apps): update kube-prometheus-stack from 70.7.0 to 72.5.0

charts/kubernetes-etcd-backup/Chart.yaml, charts/kubernetes-etcd-backup/README.md
Upgrade kubernetes-etcd-backup to 1.4.6, which moves ubi9-minimal from 9.5 to 9.6
=> chore: upgrade kubernetes-etcd-backup to 1.4.6

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Upgrade openshift-etcd-backup to 1.9.5, which upgrades ubi9-minimal from 9.5 to 9.6
=> chore: upgrade openshift-etcd-backup to 1.9.5

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md, charts/openshift-etcd-backup/templates/cronjob.yaml
This changes sets the pod DNS policy to `ClusterFirstWithHostNet`
Pod runs with DNS policy set to `ClusterFirst`. Pods running with hostNetwork  should explicitly set its DNS policy to `ClusterFirstWithHostNet` ([doc](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy))
=> openshift etcd backup: set pod dns policy to ClusterFirstWithHostNet

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Update kube-prom-stack Helm chart from 75.3.0 to 76.4.1
* Fixes https://github.com/adfinis/helm-charts/issues/1435
=> chore: Update kube-prom-stack from 75.3.0 to 76.4.1

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updated kyverno-policies form 3.4.1 to 3.5.1 in line with the main kyverno Chart.
No links to the changes were provided, since kyverno does not properly publish a changelog for its charts.
I tested the upgrade on a local dev cluster, since we do not use kyvernoPolicies on AKS INT prod or test.
Changes:
- Removed the deprecated top-level field spec.validationFailureAction.
- Added the new per-rule field spec.validate[*].failureAction as its replacement. Please update your policies to use the new field.
- Added the spec.validate[*].allowExistingViolations field to policies, which allows existing resources to be exempt from validation rules.
- Fixed a bug in the merging logic for policyExclude customizations to prevent incorrect overrides.
https://github.com/adfinis/helm-charts/issues/1464
=> chore(security-apps): bumping kyvernoPolicies chart version
