adfinis/helm-charts

.ci/prepare-lint-cluster.sh, .github/workflows/pre-commit.yaml, .pre-commit-config.yaml, charts/timed/.helmignore, charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/NOTES.txt, charts/timed/templates/_helpers.tpl, charts/timed/templates/configmap-backend.yaml, charts/timed/templates/deployment-backend.yaml, charts/timed/templates/deployment-frontend.yaml, charts/timed/templates/ingress.yaml, charts/timed/templates/job-dbmigrate.yaml, charts/timed/templates/pre-install-secret-backend.yaml, charts/timed/templates/service-backend.yaml, charts/timed/templates/service-frontend.yaml, charts/timed/templates/tests/test-connection.yaml, charts/timed/values.yaml, ct.yaml
This contains the timed chart with it's complete history from https://github.com/adfinis-sygroup/helm-charts. The chart itself was reviewed in the old repository and I didn't touch it.
I'm moving it to this repo since this will be the new canonical chart hosting repo for all our chart needs.
Once this is merged I'll update the README on the timed-charts repo to point here, recreate any open issues from there over here and archive the timed-chart repo.
=> Integrate timed chart

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/templates/pre-install-secret-backend.yaml, charts/timed/values.yaml
Add redmine integration configuration values according to:
https://github.com/adfinis-sygroup/timed-backend/blob/master/timed/settings.py#L244
=> Timed redmine config

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/deployment-backend.yaml, charts/timed/templates/job-dbmigrate.yaml, charts/timed/templates/secret-backend.yaml
A regular secret makes more sense since Argo CD will be able to manage it properly.
=> :bug: (timed) create regular secret instead of pre-commit hook

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/cronjob-backend.yaml, charts/timed/values.yaml
=> timed: Add cronjobs

.ci/github/install-pre-commit-deps.sh, .github/workflows/pre-commit.yaml, .pre-commit-config.yaml, hack/README.tpl.md, hack/update-readme.sh
Use [gomplate](https://gomplate.ca/) to automate the listing of charts on the main readme.
=> ✨ (root README) automate chart listing

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/prometheus/service-barman-exporter.yaml, charts/barman/templates/prometheus/servicemonitor.yaml, charts/barman/templates/statefulset.yaml, charts/barman/values.yaml
Add barman prom exporter service and service monitor
=> Barman prometheus exporter

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/cronjob-backend.yaml
Seems like we missed that in https://github.com/adfinis-sygroup/helm-charts/pull/19.
=> Timed cronjob backend secret

charts/argoconfig/Chart.yaml, charts/argoconfig/README.md, charts/argoconfig/ci/default-values.yaml, charts/argoconfig/ci/default.yaml, charts/argoconfig/templates/NOTES.txt, charts/argoconfig/templates/application.yaml, charts/argoconfig/templates/appproject.yaml, charts/argoconfig/templates/secret-cluster.yaml, charts/argoconfig/values.yaml
* chart: https://github.com/hairmare/helm-charts/tree/feat/multiple-apps-in-argoconfig/charts/argoconfig
=> :recycle: (argoconfig) allow configuring multiple apps

charts/argoconfig/Chart.yaml, charts/argoconfig/README.md, charts/argoconfig/ci/default-values.yaml, charts/argoconfig/templates/NOTES.txt, charts/argoconfig/templates/secret-cluster.yaml, charts/argoconfig/values.yaml
Same things as #34 did for apps but for clusters.
Fixes #37
=> :recycle: (argoconfig) allow multiple clusters

README.md, charts/argoconfig/Chart.yaml, charts/argoconfig/README.md, charts/back8sup/Chart.yaml, charts/back8sup/README.md, charts/barman/Chart.yaml, charts/barman/README.md, charts/caasperli/Chart.yaml, charts/caasperli/README.md, charts/common/Chart.yaml, charts/common/README.md, charts/kasperleyn/Chart.yaml, charts/kasperleyn/README.md, charts/timed/Chart.yaml, charts/timed/README.md, hack/config/helm-docs/README.md.gotmpl, hack/config/update-readme/README.md.gotmpl
=> readme: fix typo

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/values.yaml
Add Django admins to configmap
=> Timed django admins

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/ci/default-values.yaml, charts/timed/templates/configmap-frontend.yaml, charts/timed/templates/deployment-frontend.yaml, charts/timed/templates/secret-backend.yaml, charts/timed/values.yaml
Depends on:
https://github.com/adfinis-sygroup/timed-frontend/commit/95a144197365d42af8bc3858aca2bdab86b25929
=> Timed frontend oidc config

charts/sentry-apps/Chart.yaml, charts/sentry-apps/README.md, charts/sentry-apps/values.yaml
Using values from _bitnami/kafka_ https://github.com/bitnami/charts/blob/master/bitnami/kafka/values.yaml
=> feat: scale down the kafka cluster

charts/sentry-apps/Chart.yaml, charts/sentry-apps/README.md
=> :bug: (sentry-apps) bump with pullable version from upstream

.github/CODEOWNERS, CODEOWNERS
This is a first draft to see how this impacts future workflows.
=> feat: introduce codeowners

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
https://github.com/adfinis-sygroup/helm-charts/issues/101
=> Timed cronjobs english

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/templates/NOTES.txt
Adds filebeat & fluentd to the `NOTES.txt`
=> fix(notes.txt): add filebeat/fluentd to NOTES

CONTRIBUTING.md
=> fix(contributing.md)

charts/back8sup/Chart.yaml, charts/back8sup/README.md, charts/back8sup/values.yaml
see https://github.com/adfinis-sygroup/back8sup/pull/24
BREAKING CHANGE: EXPIRE won't work anymore
This will work once https://github.com/adfinis-sygroup/back8sup/pull/24 is merged
=> feat(values.yaml): GENERATIONS instead of EXPIRE days

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
=> fix(values.yaml): typo in chart repo reference

.github/workflows/release.yaml
After adding the repo first with helm, the chart can be packaged.
=> fix(release.yaml): adding our repo fixes the issue with ci

charts/infra-apps/Chart.lock, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/logging-apps/Chart.lock, charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/misc-apps/Chart.lock, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/security-apps/Chart.lock, charts/security-apps/Chart.yaml, charts/security-apps/README.md
Uses argoconfig 0.7.0 for logging-apps
=> chore(*-apps): bump argoconfig to 0.7.2

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/templates/falcosidekick.yaml
Fixes falcosidekick template values, not generating the app at all.
This was a TYPO in the initial PR: https://github.com/adfinis-sygroup/helm-charts/pull/130
=> fix(templates/falcosidekick.yaml): Template values

.github/workflows/test.yaml, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml, charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml, charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml, charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
* velero
* rbacManager
* argocd
* ingress-nginx
* downscaler
* metallb
* filebeat
* fluentd
* fix Version of jaeger-operator
* fix repoURL of gatekeeper
=> chore(Upgrades): several upgrades

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/examples/falco-exporter.yaml, charts/security-apps/templates/falco-exporter.yaml, charts/security-apps/values.yaml
Addition of falco-exporter. Can be used to export falco metrics to prometheus, and adding a grafana dashboard
=> feat(falco-exporter): addition of new app

charts/barman/Chart.yaml, charts/barman/README.md
Fixes barman validation by making the "unused" `appVersion` in `Chart.yaml` a String.
=> fix(barman): make appVersion string to validate

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Changes:
* 2.3.x
* lots, like a bump to loki 2.1.x
----
=> chore(logging-apps): bump loki-stack chart to 2.3.x

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates kube-prometheus-Stack to 13.2.*
=> chore(kube-prometheus-stack): update to 13.2.*

charts/vault-csi-provider/Chart.lock, charts/vault-csi-provider/Chart.yaml, charts/vault-csi-provider/README.md
Updates secrets-store-csi-driver to newer version.
=> feat(secrets-store-csi-driver): update to 0.0.19

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates to 13.7.*
Only new features / values addes
=> chore(kps): update to 13.7.*

charts/csi-secret-provider-class/Chart.yaml, charts/csi-secret-provider-class/README.md, charts/csi-secret-provider-class/templates/deployment.yaml
In fact it needs a volumeMount to work. I don't know what I was talking about last week.
=> fix(templates/deployment.yaml): needs a volumeMount to work

charts/osschallenge/Chart.yaml, charts/osschallenge/README.md, charts/osschallenge/ci/default-values.yaml, charts/osschallenge/templates/deployment.yaml, charts/osschallenge/templates/pvc.yaml, charts/osschallenge/values.yaml
the volume is need for uploading images for the oss-challenge
=> fix(oss-challenge): add persistent volume claim

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/examples/vault-monitoring.yaml, charts/security-apps/templates/vault-monitoring.yaml, charts/security-apps/values.yaml
* adds vault-monitoring to security-apps
=> feat(security-apps): add vault-monitoring

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/examples/vault-auth.yaml, charts/security-apps/templates/vault-auth.yaml, charts/security-apps/values.yaml
* adds vault-auth to our security-apps. 
PS: vault-monitoring and vault-csi-provider will follow in a separate PR
Also fixes a copy paste error in the values description of  `gatekeeper`
=> feat(security-apps): add vault-auth

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/examples/vault-csi-provider.yaml, charts/security-apps/templates/vault-csi-provider.yaml, charts/security-apps/values.yaml
* adds vault-csi-provider to security-apps
=> feat(security-apps): add vault-csi-provider

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
fixes the root path of our adfinis charts taken in the security-apps
n/a
=> fix(repoURL): root path

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/examples/cert-manager-issuers.yaml, charts/infra-apps/templates/certmgr-issuers.yaml, charts/infra-apps/values.yaml
Adds the cert-manager-issuers chart in the infra-apps app of apps app.
=> feat(infra-apps): add cert-manager-issuers deployment

charts/cert-manager-issuers/Chart.yaml, charts/cert-manager-issuers/README.md, charts/cert-manager-issuers/examples/letsencrypt-clusterissuers.yaml, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/cert-manager-issuers.yaml
Add `privateKeySecretRef` to the Let's Encrypt ACME examples since it is no longer optional.
=> docs(cert-manager-issuers): fix let's encrypt examples

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/cert-manager-on-aks.yaml, charts/infra-apps/examples/nginx-ingress-on-aks.yaml, charts/infra-apps/examples/nginx-ingress.yaml
Update existing examples and add examples specific to using nginx-ingress and cert-manager on AKS.
=> chore(infra-apps): cleanup AKS examples for nginx and cert-manager

charts/back8sup/Chart.yaml, charts/back8sup/README.md
bump back8sup version to latest
=> chore(appVersion): bump to latest

.github/workflows/release.yaml
Fixes the repo missing in the Chart Releaser action.
We should really think about having this managed somewhere else.
release fails with: `Error: no repository definition for https://charts.bitnami.com/bitnami, https://charts.bitnami.com/bitnami`
=> fix(chart-releaser): add bitnami repo to deps

CODEOWNERS
Updates the CODEOWNERS with the respective mantainers of our charts.
n/a
=> chore(CODEOWNERS): update

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update to an Argo CD chart version that contains Arrgo CD 1.8.4.
Below are the changes to the chart, please see the [release notes](https://github.com/argoproj/argo-cd/releases) for details on the content of the Argo CD update.
* enable support for lifecycle hooks on ArgoCD Server
* conditionally create the rbac configmap
* update to 1.8.4
* support for readOnlyRootFilesystem in dex
* Mount ephemeral emptyDir on repoServer for /tmp and /app/config/gpg/keys
* add self-heal-timeout as a template variable
* adds configEnabled flag to allow parent chart to own CM
* upgrade redis-ha to v4.10.4
* add spec for the status field of AppProject CRD
* add possibility for change NodePort if this is type of Service
* add annotations to the dex service account
* create roles instead of rolebindings when …
=> chore(infra-apps): bump Argo CD chart to 1.17.*

.github/workflows/release.yaml
Typo inside PR #201
ruun instead of run, release does not run.
=> QUICKFIX / fix(release.yaml): s/ruun/run/

hack/sh/deps/yq.sh
fixes the check for the binary in `yq.sh`
Release was not starting
=> QUICKFIX // fix(yq.sh): check for binary

.github/workflows/release.yaml
fixes the wrong path
forgot about `hack/` dir
=> QUICKFIX // fix(release.yaml): path wrong.

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
bump cert-manager version to 1.2.*
=> chore(cert-manager): update to 1.2.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update nginx-ingress to version 3.25.*
=> chore(nginx-ingress): update to 3.25.*

.github/pull_request_template.md
Add a "If I updated a dependency tool, or app, this PR contains a short summary of the changes I'm pulling" to the PR template since this seems to be a discussion we often have on PRs.
=> ci: ask for change docs in pr template

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates vault to version `0.10.*`
Needs #207 first to be merged!
n/a
=> chore(vault): update to 0.10.*

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/prometheus/prometheusrules.yaml, charts/barman/values.yaml
Add the option to configure `PrometheusRule`.
=> chore(barman): add values for prometheusrules

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/examples/thanos.yaml, charts/infra-apps/templates/thanos.yaml, charts/infra-apps/values.yaml
Adds `thanos` to the `infra-apps`
=> feat(thanos): Addition

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates to latest argo-helm release using argocd version 2.0
Upgrade info: https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd#upgrading
```
3.0.0 and above
Helm apiVersion switched to v2. Requires Helm 3.0.0 or above to install. Read More on how to migrate your release from Helm 2 to Helm 3.
```
ArgoCD 2.0.0: Changelog with changes.
https://github.com/argoproj/argo-cd/releases/tag/v2.0.0
n/a
=> chore(argocd): update to v3.0.* | argocd version 2.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Add option to specify job label for ServiceMonitor
* Support existing PSPs using `controller.admissionWebhooks.existingPsp`
* Update ingress-nginx v0.45.0
* Update the Ingress Controller Image to correct OpenSSL CVEs
* Add support for Jaeger Endpoint
* Allow Multiple Publish Status Addresses
* complete changes: [here](https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md)
* Changed servicePort value for metrics (bugfix)
=> chore(infra-apps): bump ingress-nginx to 3.29.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/nginx-ingress-on-aks.yaml
=> docs(infra-apps): fix typo in example

.github/dependabot.yml
=> feat(ci): enable dependabot for github actions

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/examples/argocd-notifications.yaml, charts/infra-apps/templates/NOTES.txt, charts/infra-apps/templates/argocdNotifications.yaml, charts/infra-apps/values.yaml
Adds [ArgoCD Notifications](https://argocd-notifications.readthedocs.io/) to infra-apps. The notifications component can do a lot of different notifications the one I'm currently most interested in is annotating deployments in the kube-prometheus-stack's Grafana.
=> feat(infra-apps): add argocd-notifications

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Fixes some trailing slashes issues in the repoURLs
n/a
=> fix(security-apps): trailing slash in several repoURL

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/ci/default-values.yaml, charts/timed/grafana/dashboards/timed.json, charts/timed/templates/grafana/configmap-dashboard.yaml, charts/timed/values.yaml
Deploy a dashboard for timed that shows a simple overview of most metrics we are scraping in prometheus.
=> feat(timed): grafana dashboard for metrics

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
bumps thanos to version `3.16.*`
This includes extraVolume/Mounts as introduced in [6169](https://github.com/bitnami/charts/pull/6169)
n/a
=> chore(thanos): bump to 3.16.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump argo-cd chart to 3.1 which introduces the possibilty to configure cluster ctredentials via `configs.clusterCredentials` and fixes the redis ha version used to match what argo-cd actually supports.
=> chore(infra-apps): bump argo-cd chart to 3.1.*

charts/timed/Chart.yaml, charts/timed/README.md
Due to issues with GitHub Pages timed-0.6.0 was never added to the index. Instead of debugging how to fix the index i'm tagging a new version so i can get 0.6.0 onto test asap.
=> fix(timed): bump version to trigger publishing of package

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/velero.yaml, charts/infra-apps/values.yaml
bumps velero to version `2.18.*` which is appVersion `1.6.0`
We were on appVersion `1.5.3`
[Upgrading docs from 1.5 > 1.6](https://velero.io/docs/v1.6/upgrade-to-1.6/) 
[Changelog 1.6.0](https://github.com/vmware-tanzu/velero/blob/main/changelogs/CHANGELOG-1.6.md)
As per [3067](https://github.com/vmware-tanzu/velero/pull/3067) annotations get passed to the backups, and enables us to ignorediff them from argoCD.
n/a
=> chore(velero): bump to version 2.18.* -> AppVersion 1.6.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/dex.yaml, charts/security-apps/examples/gangway.yaml, charts/security-apps/values.yaml
Migrates the gangway chart to gabibbo97 charts, which are actively mantained.
get rid of `charts.helm.sh/stable`
=> feat(gangway): migration to gabibbo97 charts

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Mistake by me in taking the App Version istead of Chart Version
Fixing the dex chart inside security-apps
=> fix(dex/values.yaml): right version

charts/customer-center/Chart.lock, charts/customer-center/Chart.yaml, charts/customer-center/README.md, charts/customer-center/templates/secret-backend.yaml, charts/customer-center/values.yaml
- feat(customer-center): bump postgres and redis dependencies
=> feat(customer-center): bump dependencies and remove unnecessary postgresql replication setup

charts/osschallenge/Chart.lock, charts/osschallenge/Chart.yaml, charts/osschallenge/README.md, charts/rmd/Chart.lock, charts/rmd/Chart.yaml, charts/rmd/README.md
Adds some Chart.lock files that we forgot to add previously.
/cc @trowik
=> fix: add missing lockfiles for osschallenge and rmd

charts/customer-center/Chart.yaml, charts/customer-center/README.md, charts/customer-center/templates/secret-backend.yaml
* fix backend-secret templating after redis upgrade
=> fix(backend-secret): update redis auth password path

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/templates/secret-backend.yaml, charts/timed/values.yaml
=> chore(timed): bump v1.1.4 and add new flags

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/examples/kured.yaml, charts/infra-apps/templates/kured.yaml, charts/infra-apps/values.yaml
Add [kured](https://github.com/weaveworks/kured) to infra-apps
=> feat(infra-apps): add kured

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/secret-backend.yaml
b64enc the SENTRY_DSN secret so we don't have to specifiy an encoded string in values.
=> fix(timed): b64enc sentry dsn secret

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/deployment.yaml, charts/barman/values.yaml
Allow specifying a DeploymentStrategy. This allows us to use a Recreate strategy on clusters where we would get a multi-attach deadlock because the underlying volume is ReadWriteOnce.
=> feat(barman): allow specifying DeploymentStrategy

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump Argo CD chart to 3.3.3:
* bump Argo CD to 2.0.1
* v1 Ingress compatibility
* add labels for appSet cluster selector
* update bundled redis and redis-ha versions
* update CRDs to match upstream
* allow overriding clusterrole rules
* allow specifying custom CSS via values
* fix volume and volumeMounts in application controller
If you want to deploy this to a cluster that does not support v1 Ingresses you will need to replace the bundled helm with a version specific to your cluster [as documented by upstream](https://argoproj.github.io/argo-cd/operator-manual/custom_tools/).
* [Argo CD 2.0.1 Release](https://github.com/argoproj/argo-cd/releases/tag/v2.0.1)
=> chore(infra-apps): Bump Argo CD chart to 3.3.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/kured.yaml
=> fix(infra-apps): typo in kured example

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update all the falco bits.
* Falco to 0.28.1 and rules to match
=> chore(security-apps): bump falco tooling

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
upgrades to argocd helm chart version 3.6.*
Solves issues like: 
https://github.com/argoproj/argo-helm/issues/703
updates Dex to 2.27.0 and argocd version to 2.0.3
n/a
=> chore(argo-cd Chart): update to 3.6.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates argocd-notifications chart version to 1.4
uses image tag version 1.1.1 and adds some features.
=> chore(argo-cd-notifications Chart): update to 1.4.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates to chart version 3.33.* and image tag version 0.47.0
=> chore(ingress-nginx Chart): update to 3.33.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Make CRDS Installation optional + serviceMonitor.additionalLabels added.
=> chore(rbac-manager Chart): update to 1.8.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates Velero Chart from 2.18.* to 2.22.* 
```
79e3308 Merge branch 'main' into feature/velero_add_containerSecurityContext
ee1d7b5 Bump chart version
a750692 Fix scratch volume mount
5bacc34 Merge branch 'main' into feature/velero_add_containerSecurityContext
50c46a8 Merge pull request #266 from carlisia/c-add-reviewers
c0822af Revert chart bump
c6d0bfb Reset number of reviewers
2046916 Bump chart
236df89 Update auto assign of reviewers
daa10dd Merge branch 'main' into feature/velero_add_containerSecurityContext
4181fa7 Bump chart version
599cd39 Update CI test values.yaml
ecf1fd7 Allow to configure default BSL
86b72a5 Merge pull request #252 from jenting/remove-helm2
e002057 Merge branch 'main' into remove-helm2
20ed150 Merge branch 'main' into remove-helm2
3afcc75 Remove helm2 from …
```
=> chore(velero Chart): update to 2.22.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates kured chart to 2.6.
* Add documentation for lockReleaseDelay parameter
* Add lockReleaseDelay parameter to helm chart
* doc: update image-version
* Add prometheus export metrics functional testing 
* update chart definition to include --notify-url
* feat: use chart appVersion as default image-tag 
* update chart definition to include --annotate-nodes
=> chore(kured Chart): update to 2.6.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates thanos chart to 3.17.*
* Release 3.17.8 updating components versions
* fix securityContext for Receive (#6509) 
* Release 3.17.5 updating components versions 
* Release 3.17.3 updating components versions 
* Release 3.17.2 updating components versions 
* Put /api/v1/receive at the first of rules (thanos-re… 
* Adding sidecars to services with ingress (#6259)
=> chore(thanos Chart): update to 3.17.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Added missing upgrade command for alertmanager to do before 13.13.x (#… 
* Upgrade to latest kube-state-metrics chart wi… 
* add Prometheus and Alertmanager topologySpreadConstraints (#702)
* Upgrade grafana dependency to 6.4 (#685) 
* Ability for custom dnsConfig (#639) 
* hack: fix syncing dashboards and alerting rul…
* update node exporter chart to 1.14.* (#677)
=> chore(kps Chart): update to 14.0.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrades dex chart version to 0.3.*
```
chore: globally ignore values.test.yaml
fix(charts/dex): add missing https service values
chore: added newline at end of poddisruptionbudget.yaml 
chore: updated artifact changelog in Chart.yaml
chore: updated pdb and values after request to change
feat: added support for podDisruptionBudget
add support for hostAliases 
feat: add external secret support 
chore(charts/dex): bump chart version 
refactor(charts/dex)!: use full name as config secret name
```
=> chore(dex): Upgrade to 0.3.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrades vault chart version to 0.12.*
https://github.com/hashicorp/vault-helm/blob/master/CHANGELOG.md
=> chore(vault): Upgrade to 0.12.*

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Upgrades both ceph-csi charts to version 3.3.*
```
deploy: update templates for v3.3.1
build: update required files for release-v3.3 
```
=> chore(ceph-csi): upgrade to version 3.3.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgraes chart version to 1.13.*
```
falco: fix port for livenessProbe and readinessProbe
falco: add liveness and readiness probes 
fix(falco/values.yaml): removing trailing spaces 
release(falco): 1.12.0
falco: update falco to use release 0.28.1
update chart to v1.10.0
```
=> chore(falco): Upgrade to 1.13.*

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Upgrades filebeat chart version to 7.13.*
```
Bump version to 7.13.1 (#1236)
Bump version to 7.13.1-SNAPSHOT (#1228)
Bump version to 7.13.0 (#1222)
[meta] Initiate 7.13 branch (#1197) 
[meta] bump 7.x branch to 7.13.0-SNAPSHOT (#1114) 
[meta] bump 7.x branch to 7.12.0-SNAPSHOT (#1094)
[elasticsearch][kibana] remove oss examples (#1046) (#1052)
[filebeat] variable maxUnavailable updateStrategy (#809)
[meta] add build status and artifact hub badges (#1033)
[filebeat] fix documentation
NIT Update backport config and small doc fixes (#1017)
[filebeat][metricbeat] Update documentation on port collisions for mu… 
[filebeat] Configurable ClusterRole (#978) (#1007) 
Filebeat deployment support feature (#964) (#1005)
[7.x] [all] add hostaliases (#970) (#985) 
[7.x] [meta] stabilize CI tests (#935) …
```
=> chore(filebeat): update to 7.13.*

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Upgrades fluentd chart versiont to 3.7.*
```
[bitnami/fluentd] Release 3.7.5 updating components versions
[bitnami/fluentd] Release 3.7.4 updating components versions 
[bitnami/fluentd] Add terminationGracePeriodSeconds values (#6330)
[bitnami/fluentd] Release 3.7.2 updating components versions 
[bitnami/fluentd] Release 3.7.1 updating components versions 
[bitnami/fluentd] Add 'extraDeploy' parameter (#6224)
[bitnami/fluentd] Release 3.6.8 updating components versions
[bitnami/fluentd] Release 3.6.7 updating components versions 
[bitnami/fluentd] (#6097) 
[bitnami/fluentd] Release 3.6.5 updating components versions 
[bitnami/fluentd] Release 3.6.4 updating components versions 
[bitnami/fluentd] Release 3.6.3 updating components versions 
[bitnami/*] Use common macro to define RBAC …
```
=> chore(fluentd): update to 3.7.*

charts/infra-apps/Chart.yaml, charts/infra-apps/values.yaml
Updates `kube-prometheus-stack` to version 16.0.*
* https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-15.0.0...kube-prometheus-stack-16.0.0
* kube-pstate-metrics Chart Version 3.1.0 from official charts
* grafana Chart Version 6.9.1
* prometheus-node-exporter Chart Version 1.18.0
* prom-operator version 0.47.1
> Version 16 upgrades kube-state-metrics to v2.0.0. This includes changed command-line arguments and removed metrics, see this [blog post](https://kubernetes.io/blog/2021/04/13/kube-state-metrics-v-2-0/). This version also removes Grafana dashboards that supported Kubernetes 1.14 or earlier.
=> chore(kps): update to 16.0.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/prometheus.yaml, charts/infra-apps/values.yaml
Upgrades kps to 16.6.*
* https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-16.0.1...kube-prometheus-stack-16.6.2
* kube-state-metrics Chart version 3.1.1
* prom-node-exporter Chart version 1.18.1
* grafana Chart Version 6.12.0
* prom-operator 0.48.1
* alertmanger 0.22.2
* prometheus 2.27.1
=> chore(kps): update to 16.6.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates KPS to 16.7.*
Remove old rulesets and sync new ([#1066](https://github.com/prometheus-community/helm-charts/pull/1066)) 
=> chore(kps): update to 16.7.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrades kps to use version 16.12.*
* kube-state-metrics Chart version 3.1.1 -> 3.3.1
* prom-node-exporter Chart Version 1.18.1 -> 1.18.2
* grafana chart version 6.12.1 -> 6.13.5
* uses now prom-operator main branch
* fixes on alerts
=> feat(kps): update to 16.12.*

charts/back8sup/Chart.yaml, charts/back8sup/README.md
updates the back8sup AppVersion accordingly
=> chore(back8sup): update appVersion

charts/infra-apps/Chart.lock, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/logging-apps/Chart.lock, charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/misc-apps/Chart.lock, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/storage-apps/Chart.lock, charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/tracing-apps/Chart.lock, charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md
makes our `*-apps` use the newest argoconfig version
Fixes #291
=> chore(*-apps): use newest argoconfig

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Fixes some links in the chart README.
=> docs(misc-apps): fix signalilo chart links

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update jaeger-operator to 1.24 and chart to 1.23
* Synchronize cluster role template with jaeger operator
* Jaeger update updates Badger backend, supports much more archs + a bunch more: 
* https://github.com/jaegertracing/jaeger/releases/tag/v1.24.0 
* https://github.com/jaegertracing/jaeger/releases/tag/v1.23.0
=> feat(tracing-apps): jaeger-operator 2.23/1.24

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Gatekeeper 3.5:
* Compatibility with Kubernetes v1.22 and later.
* If you are using Helm to upgrade your Gatekeeper deployments and have mutation enabled, make sure to install MutatorPodStatus CRD as Helm does not install new CRDs with an upgrade. (this is us!)
=> feat(security-apps): bump gatekeeper to 3.5

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* add ability to manage gpg keys
* add pathType in Ingress
* add ability to override API version
* add service account for redis
* add ability to create network policies
=> feat(infra-apps): bump argo-cd chart to 3.9

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
=> chore(openshift-etcd-backup): bump appVersion to 1.3.1 to use latest image

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Patch level update after adding `yum update` in upstream image.
=> chore(openshift-etcd-backup): bump chart after updating upstream image with `yum update`

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Bump default Argo CD version to v2.0.5
* Support AWS ALB Ingress with gRPC3
* Deprecate the static assets flag passed to argocd-server
=> feat(infra-apps): bump argocd chart to 3.10

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* update all deps
* fix staticAssets arg
=> fix(infra-apps): bump argocd chart to 3.11

.github/workflows/pr-sizing.yaml
Adds k8s style PR sizing labels to help with review
=> ci: add pr-sizing workflow

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump kube-prometheus-stack to `17.1.*`:
* Bump prometheus-operator to 0.49.0 (tls for prom and proxy_url for probes)
* Allow generating an extra secret that can be used for i.e. basic auth in ingress
* Various bugfixes
=> feat(infra-apps): bump kube-prometheus-stack to 17.1.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Bump falco chart to `1.15.*`:
* v1.15.7: Removed `maxSurge` reference from comment in Falco's `values.yaml` file.
* v1.15.6: Update `Falcosidekick` chart to 0.3.13
* v1.15.4: Update `Falcosidekick` chart to 0.3.12
* v1.15.3
* Upgrade to Falco 0.29.1 (see the [Falco changelog](https://github.com/falcosecurity/falco/blob/0.29.1/CHANGELOG.md))
* Update rulesets from Falco 0.29.1
* v1.15.2: Add ability to use an existing secret of key, cert, ca as well as pem bundle instead of creating it from files
* v1.15.1: Fixed liveness and readiness probes schema when ssl is enabled
* v1.15.0: Update `Falcosidekick` chart to 0.3.8
* v1.14.1: Update image tag to 0.29.0 in values.yaml
* v1.14.0:
* Upgrade to Falco 0.29.0 (see the [Falco changelog](https://github.com/falcosecurity/falco/blob/0.29.0/CHANGELO …
=> feat(security-apps): bump falco to 1.15.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/secrets-store-csi-driver.yaml, charts/security-apps/values.yaml
contains lots of [upstream changes](https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/tag/v0.1.0).
please have a look at the upstream changelog before upddating any environment due to the release containing a bunch of breaking changes.
=> feat(security-apps): secrets-store-csi-drive 0.1.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
bump argocd chart to 3.12.*:
* Add support for aggregation clusterroles
* Fix (full)nameOverride redis-ha sub-chart
=> feat(infra-apps): bump argocd chart to 3.12.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/examples/kubernetes-event-exporter.yaml, charts/infra-apps/templates/kubernetes-event-exporter.yaml, charts/infra-apps/values.yaml
like, for events...
The [kubernetes-event-exporter](https://github.com/opsgenie/kubernetes-event-exporter) consumes kubernetes audit events and can ship them to a variety of targets.
=> feat(infra-apps): introduce kubernetes-event-exporter

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update kured chart to 2.9.*
- Fix updating by setting default value for updateStrategy to RollingUpdate
- Added possibility to mount volumes
Patch version bumped since the updateStrategy change fixes properly updating kured and should have been the default already.
Fixes #337
=> fix(infra-apps): update kured to chart to 2.9.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes the issue of me referencing an invalid chart version in #323.
=> fix(infra-apps): valid kube-event-exporter chart version

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Updates `logging-apps/filebeat` to use the chart version `7.14.*`
Fixes #339
Only [meta] changes
* [meta] add tests for k8s 1.19 
* [meta] remove gke 1.17 tests 
* [meta] update support matrix
* [meta] Initiate 7.14 branch
=> chore(filebeat): update to 7.14.*

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
=> fix(azure-apps): Change Azure chart name

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Updates cephFS & cephRBD Csi Charts to version `3.4.*`
Closes #346 #347
=> chore(storage-apps): update cephfs & rbd

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump cert-manager from 1.4 to 1.5. See [Release Notes](https://cert-manager.io/docs/release-notes/release-notes-1.5/) for a readable overview of the changes.
The recent Kubernetes 1.22 release has removed a number of deprecated APIs. You can read the official blog post Kubernetes API and Feature Removals In 1.22 to learn more about it. If you intend to upgrade to Kubernetes 1.22, you must upgrade to cert-manager 1.5.
To keep compatibility with older Kubernetes versions (down to 1.16), cert-manager 1.5 is now compatible with both Ingress v1 and v1beta1. cert-manager will default to using v1 Ingress, and fall back to v1beta1 when v1 is not available.
Additionally, the cert-manager API versions v1alpha2, v1alpha3 and v1beta1 are now …
=> chore(infra-apps): Update certMgr

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
[Gatekeeper](https://open-policy-agent.github.io/gatekeeper/) 3.6.0
- ConstraintTemplate CRD moves to v1 tada
- Reduce System.Mutate runtime by 87% hammer
- Fix race conditions in watch manager and constraint controllers racehorse
- Remove non-specific webhook request metrics bar_chart
- Add prefix-based matching for namespaces and excludedNamespaces abcd
- Add integer keyValue support to mutation path parser / mutators 1234
- Helm enable to config controller manager & audit port confetti_ball
- Add helm hooks to upgrade CRDs up
- Add metrics reporting for mutation chart_with_upwards_trend
#344
=> feat(security-apps): gatekeeper 3.6.0

charts/caasperli/Chart.yaml, charts/caasperli/README.md, charts/caasperli/templates/grafana/configmap-dashboard.yaml, charts/caasperli/templates/prometheus/podmonitor.yaml, charts/caasperli/templates/prometheus/servicemonitor.yaml, charts/caasperli/values.yaml
new `prometheus.extraAnnotations` and `grafana.extraAnnotations` values for doing [fun stuff like external links in argocd](https://argoproj.github.io/argo-cd/user-guide/external-url/).
=> feat(caasperli): extra annotations for prometheus-operator CRDs

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
[Argo CD Notifications](https://argocd-notifications.readthedocs.io/en/stable/) chart bump 1.5
- Add Pod label configuration for argocd-notifications
- No update to argocd-notifications
Fixes #332
=> feat(infra-apps): update argocd-notifications to 1.5

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Bump openshift-etcd-backup Helm chart to 1.4.3 to use latest application version v1.4.1.
=> chore(openshift-etcd-backup): bump to latest v1.4.1 appVersion

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates Security Apps to use the newest vault-helm release (0.16.0)
n/a
=> chore(sec-apps): use new vault 0.16.0 version

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Signed-off-by: Iago Santos <iago.santos.pardo@adfinis.com>
Adds extraVolumes and extraVolumeMounts feature
Don't merge until https://github.com/appuio/charts/issues/355 is closed
=> feat(misc-apps): Bump signalilo

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/cronjob-backend.yaml
Update deprecated CronJob version from Issue #369 
None
=> fix(timed): update deprecated CronJob version

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Change default namespace for vault as recommended in https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/#deployment-using-helm
=> fix(azure-apps): change default namespace for vault

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Signed-off-by: Iago Santos <iago.santos.pardo@adfinis.com>
- Upgrade argo-cd to 2.1.1
- fix: cluster filter popping out of box (https://github.com/argoproj/argo-cd/pull/7135)
- fix: gracefully shutdown metrics server when dex config changes (https://github.com/argoproj/argo-cd/pull/7138)
- fix: upgrade gitops engine version to v0.4.1 (https://github.com/argoproj/argo-cd/pull/7088)
- fix: repository name already exists when multiple helm dependencies (https://github.com/argoproj/argo-cd/pull/7096)
=> feat(infra-apps): upgrade argocd to 3.22.*

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
- bump jaeger-operator chart to 2.25
- `extraLabels` for jaeger-operator deployment
- `serviceAccount.annotations` and `service.annotations`
=> feat(tracing-apps): jaeger-operator 2.25

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
- upgrade loki-stack to 2.5.*
- updates loki chart to 2.3.0
- [release notes](https://github.com/grafana/loki/releases/tag/v2.3.0)
- watch: make queries use at least one equality matcher
- updates logstash chart to 7.8.0
- [release notes](https://www.elastic.co/guide/en/logstash/current/logstash-7-8-0.html)
- proxy support for monitoring and centralized managment component
=> chore(logging-apps): upgrade loki-stack to 2.5.*

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
- updates jaeger-operator and jaeger to  1.27.0 https://github.com/jaegertracing/helm-charts/pull/296
=> feat:(tracing-apps): jaeger-operator chart 2.26

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/templates/fluentBit.yaml, charts/logging-apps/values.yaml
* bump logging-apps appVersion to 0.14.0
* bump to fluentbit targetRevision 0.19.*
* fix fluentbit name
* fix template name
This is a review of https://github.com/adfinis-sygroup/helm-charts/pull/392
There were minor issues while creating the fluentbit app with Argo.
=> refactor(logging-apps): logging-apps 0.13.1

README.md, hack/config/update-readme/README.md.gotmpl
Hide deprecated charts from the README.md and gh-pages index.html.
=> feat: hide deprecated charts from docs

.gitattributes
Fixes this in the GitHub webui by boasting with Go
=> chore: hints for linguist

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
=> fix(infra-apps): cleanup copy paste error in values

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
- updates rbac-manager to v1.0.0 🥳 
- https://github.com/FairwindsOps/charts/pull/606
=> feat(infra-apps): rbac-manager chart 1.9.*

charts/huawei-csi-plugin/Chart.yaml, charts/huawei-csi-plugin/README.md, charts/huawei-csi-plugin/values.yaml
By default the `DaemonSet` shoud run as root to be able to mount newly created shares.
=> fix(huawei-csi-plugin): add runAUser to run huawei-csi-driver container as root

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update Jaeger-Operator (and Jaeger) to 1.28
- chart version 2.27.*
- jaeger-operator version 1.28.0
- https://github.com/jaegertracing/helm-charts/pull/316
=> feat(tracing-apps): bump jaeger-operator

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
!--
Thank you for your contribution. Please use this template to help guide
you towards preparing a PR that fullfills our merge requirements.
-->
Bump chartmuseum chart to 3.3.*
- Allow setting an ingress class name on the ingress https://github.com/chartmuseum/charts/pull/24
- Add loadBalancerIP option to service https://github.com/chartmuseum/charts/pull/14
=> feat(misc-apps): chartmuseum 3.3.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
- update gatekeeper to [3.7.0 release](https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.7.0)
=> feat(security-apps): gatekeeper 3.7.*

charts/back8sup/Chart.yaml, charts/back8sup/README.md, charts/back8sup/templates/cronjob.yaml
This PR fix `apiVersion` when having this error:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CronJob" in version "batch/v1"
```
=> fix(back8sup): use correct apiVersion and upgrade to lastest patch version

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/ci/default-values.yaml, charts/azure-apps/examples/promitor.yaml, charts/azure-apps/templates/NOTES.txt, charts/azure-apps/templates/promitor-resource-discovery.yaml, charts/azure-apps/templates/promitor-scraper.yaml, charts/azure-apps/values.yaml
Adds https://promitor.io/ to `azure-apps` chart.
=> feat(azure-apps): add promitor.io

README.md, charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/values.yaml
This value should be customizable as there are big projects that have a lot of tasks, tasks and project assignees. In such cases the amount of fields exceeds the default value of 1000, which makes saving any changes on that project impossible.
- https://github.com/adfinis-sygroup/timed-backend/pull/805
=> feat(timed): add DATA_UPLOAD_MAX_NUMBER_FIELDS to env

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
=> fix(azure-apps) promitor repoURL trailing slash

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
- Update to app version v1.2.0 https://github.com/argoproj/argo-helm/pull/1039
=> feat(infra-apps): argocd-notifications 1.6

CODEOWNERS
removes @sinicis from CODEOWNERS, adds @tongpu for `charts/huawei-csi-plugin`
=> fix(CODEOWNERS): removes sinicis, adds @tongpu

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates falco-exporter to version 0.6.*
Changelog:
* fix(falco): Only show non-zero rates in Grafana
* update: add rule tags to metrics + new deps
* Add Check availability of 'monitoring.coreos.com/v1' api version
* Add option the add annotations to the Daemonset
fixes #458
=> feat(security-apps): falco-exporter 0.6

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Updates Metallb to 0.11
* metallb controller & speaker version updated to 0.11-r27
* [extraDeploy feature added](https://github.com/bitnami/charts/pull/8164)
fixes #455
=> feat(misc-apps): metallb-0.11

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
* Removed support for deploying a leader-elector container with the [vault-k8s injector](https://github.com/hashicorp/vault-k8s) injector since vault-k8s now uses an internal mechanism to determine leadership [GH-649](https://github.com/hashicorp/vault-helm/pull/649)
* Vault image default 1.9.0
* Vault K8s image default 0.14.1
* Added templateConfig.staticSecretRenderInterval chart option for the injector [GH-621](https://github.com/hashicorp/vault-helm/pull/621)
fixes #457
=> feat(security-apps): vault-0.18

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
upgrade velero to version 2.27.*
CHANGELOG
- rename port `monitoring` to `http-monitoring`
- add value `defaultResticPruneFrequency`. Default: `168h`. Optional.
- add value `useScratchEmptyDir` Default: `true`
- will map `/scratch` to emptyDir
fix [#452 ](https://github.com/adfinis-sygroup/helm-charts/issues/452)
=> feat(infra-apps/velero): upgrade to 2.27

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
upgrade argocd to version 3.27.*
CHANGELOG
- **3.27.1** [Added]: Mention declarative set up for Argo CD in README.md
- **3.27.0** [Added]: Support for additional labels
- **3.26.12** [Added]: add custom initContainers support to all Deployments
- **3.26.11** [Changed]: add flag and labels for application labels
- **3.26.10** [Changed]: Update to app version 2.1.7
- **3.26.9** [Changed]: Update github ssh key fingerprint
- **3.26.8** [Added]: Signature keys for GPG in additionalProjects
- **3.26.7** [Fixed]: Added Openshift Route values that were previously included in Route.yaml directives.
- **3.26.5** [Changed]: README update to reflect correct helm install syntax
- **3.26.4** [Changed]: Update to app version 2.1.6
- **3.26.3** [Changed]: Update to app version 2.1.5
- **3.26.2** …
=> feat(infra-apps/argocd): upgrade to 3.27

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
upgrade kubePrometheusStack to version 23.1.*
**:exclamation: READ UPGRADE NOTES ❗**
1. [From 21.x to 22.x](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-21x-to-22x)
2. [From 22.x to 23.x](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-22x-to-23x)
- (kube-prometheus-stack-23.1.1) update grafana dependency to 6.18.2 ([#1570](https://github.com/prometheus-community/helm-charts/pull/1570))
- (kube-prometheus-stack-23.1.0) Add support for removing old datasources in values file ([#1528](https://github.com/prometheus-community/helm-charts/pull/1528))
- (kube-prometheus-stack-23.0.0) Use Istio service port naming convention ([#1407](https://github.com/prometheus-community/helm-charts/pull/1407))
- …
=> feat(infra-apps/kubePrometheusStack): upgrade to 23.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates Thanos chart to `v8.2` 
Closes #451
:exclamation:  Important Upgrading Notes :exclamation: 
* [to 8.0.0](https://github.com/bitnami/charts/tree/master/bitnami/thanos#to-800)
* [to 7.0.0](https://github.com/bitnami/charts/tree/master/bitnami/thanos#to-700)
* [to 6.0.0](https://github.com/bitnami/charts/tree/master/bitnami/thanos#to-600)
* [to 5.0.0](https://github.com/bitnami/charts/tree/master/bitnami/thanos#to-500)
* [to 4.0.0](https://github.com/bitnami/charts/tree/master/bitnami/thanos#to-400)
=> feat(infra/thanos): update to 8.2

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/values.yaml
Add customer-center email address to notify on order creation
=> feat(timed): add customer-center email

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/thanos.yaml
=> fix(infra-apps): removove trailing whitespace in thanos example

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
- add support for experimental extension controller (disabled by default) https://github.com/argoproj/argo-helm/pull/1050 https://github.com/argoproj/argo-helm/pull/1053
=> feat(infra-apps): argocd chart 3.28

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/values.yaml
Add CORS_ALLOWED_ORIGINS to env variables so we can configure it.
This is especially needed for the customer center.
[timed-backend PR](https://github.com/adfinis-sygroup/timed-backend/pull/821)
=> feat(timed): add cors_allowed_origins env variable

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update to v3.0.1

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update customer-center to v3.0.2

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update to v3.0.3

charts/customer-center/Chart.yaml, charts/customer-center/README.md, charts/customer-center/templates/configmap-frontend.yaml, charts/customer-center/values.yaml
This will also add a new ENV for configurable OIDC client
=> chore(customer-center): update customer-center to v3.0.4

charts/customer-center/Chart.yaml, charts/customer-center/README.md, charts/customer-center/templates/configmap-frontend.yaml
=> fix(customer-center): update metadata

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update customer-center to v3.0.7

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Added https://github.com/promitor/charts/releases/tag/Scraper-v2.7.0
=> feat(azure-apps): bump promitor resource discovery

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
- fix(customer-center): read config map from deployment
- chore(timed): update timed-backend 1.5.1
=> timed update

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Update to app version 2.2.1 https://github.com/argoproj/argo-helm/pull/1061
* add argocd-extensions resources support https://github.com/argoproj/argo-helm/pull/1050, https://github.com/argoproj/argo-helm/pull/1053
* clean up values.yaml by roudtripping it through ruamel (parts of prepping for automated PRs/the tool used to create this PR)
=> chore(infra-apps): update argo-cd from 3.28.* to 3.29.*

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update to v3.0.8

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update to v3.0.9

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/deployment.yaml, charts/barman/values.yaml
[Barman 2.17](https://github.com/EnterpriseDB/barman/releases/tag/release%2F2.17) was recently released, we should update! The image we use was kindly bumped to 2.17 and debian bullseye in https://github.com/ubc/barman-docker/commit/8336923226b7125909c1f1d2a2497fcad5bba859.
- barman container bump: https://github.com/ubc/barman-docker/issues/3
=> feat(barman): bump to 2.17

charts/customer-center/Chart.yaml, charts/customer-center/README.md
- chore(timed): update timed-backend 1.5.1
- chore(customer-center): update customer-center to v3.1.2
=> customer center update

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/certificate-psql.yaml
timed is still using the deprecated `cert-manager.io/v1alpha2` which will lead to an `ArgoAppNotSynced` warning down the line.
=> fix(timed): update certificate apiVersion

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/deployment.yaml
Fixes the barman deployment by re-adding default args for entrypoint.
=> fix(barman): fix entrypoint override by re-adding args

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
- bump to kured 1.9.0 : https://github.com/weaveworks/kured/releases/tag/1.9.0
- updates k8s compat to 1.21.x, 1.22.x, 1.23.x
- drops support for k8s 1.20.*
=> feat: kured 1.9.0 (chart version 2.11)

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
- adds a bunch of new scrapers
- updates dependecies and security patches
- contains .NET 3.1 to .NET 6.0 upgrade
- https://github.com/tomkerkhove/promitor/releases/tag/Scraper-v2.6.0
=> feat(azure-apps): promitor scraper 2.7

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update to v3.1.6

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed-backend): update to v1.5.4

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Update argo rollouts to chart version 2.9
* https://github.com/argoproj/argo-helm/pull/870
* https://github.com/argoproj/argo-helm/pull/1080
* https://github.com/argoproj/argo-helm/pull/1074
* https://github.com/argoproj/argo-helm/pull/1016
=> feat(argo-apps): argo-rollouts 2.9

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/falco-exporter.yaml, charts/security-apps/values.yaml
Adds the possibility to configure PrometheusRules that alert on falco events.
* https://github.com/falcosecurity/charts/pull/296
=> feat(security-apps): falco-event-exporter 0.7

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Fixes the fact that i bumped the wrong app in #514 
* #514
=> fix(security-apps): bump falco-exporter and not dex

charts/backup-apps/Chart.yaml, charts/backup-apps/README.md, charts/backup-apps/values.yaml
Bumps barman to 2.17 and adds the ability to not create secrets if you need/want to manage them externally.
* https://github.com/adfinis-sygroup/helm-charts/pull/509
* https://github.com/adfinis-sygroup/helm-charts/pull/502
* https://github.com/adfinis-sygroup/helm-charts/pull/497
=> feat(backup-apps): barman chart 0.5

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update to 3.1.8

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Argo CD chart 3.30.*. Adds google managed certs on GKE.
* https://github.com/argoproj/argo-helm/pull/1088
=> feat(infra-apps): argocd chart 3.30

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Contains a ton of updates, looks like kps was very active over the holidays.
* https://github.com/prometheus-community/helm-charts/pull/1593
* https://github.com/prometheus-community/helm-charts/pull/1614 (prometheus 
* https://github.com/prometheus-community/helm-charts/pull/1619
* https://github.com/prometheus-community/helm-charts/pull/1624
* https://github.com/prometheus-community/helm-charts/pull/1173 (so we don't need to disable a whole group if only one alert is broken)
* https://github.com/prometheus-community/helm-charts/pull/1646
* https://github.com/prometheus-community/helm-charts/pull/1653
* https://github.com/prometheus-community/helm-charts/pull/1662 (to 6.20.*)
* https://github.com/prometheus-community/helm-charts/pull/1657
* …
=> feat(infra-apps): kube-prometheus-stack 30.0

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Changing Version 3.5.0 of cephCsiRbd and cephCsiCephfs
- #532 
- #531
=> Changing Version 3.5.0 of cephCsiRbd and cephCsiCephfs

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Added ability to deploy extra K8s manifests.
* https://github.com/argoproj/argo-helm/pull/1094
=> feat(infra-apps): argo-cd chart 3.31

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/values.yaml
=> feat(timed): add tls option for email as env var

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/ingress.yaml
=> fix(timed): update ingress api version to v1

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Filebeat version update to 7.16
closes #529
=> filebeat version update

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/ingress.yaml, charts/timed/templates/service-backend.yaml, charts/timed/templates/service-frontend.yaml
Ingress template wasn't updated correctly for the api version v1.
=> fix(timed): fix ingress template for apiVersion v1

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/ingress.yaml
=> fix(timed): add missing `pathType` in ingress template

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/ci/default-values.yaml, charts/tracing-apps/examples/opentelemetryCollector.yaml, charts/tracing-apps/templates/opentelemetryCollector.yaml, charts/tracing-apps/values.yaml
Install the [OpenTelemetry Collector](https://opentelemetry.io/docs/collector/).
=> feat(tracing-apps): install opentelemetry-collector

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrade to Argo CD [2.2.5](https://github.com/argoproj/argo-cd/releases/tag/v2.2.5). This release contains a patch for  [CVE-2022-24348](https://apiiro.com/blog/malicious-kubernetes-helm-charts-can-be-used-to-steal-sensitive-information-from-argo-cd-deployments/) (from Argo CD [2.2.4](https://github.com/argoproj/argo-cd/releases/tag/v2.2.4)) and it is recommended you upgrade as soon as possible.
- https://github.com/argoproj/argo-helm/pull/1127
- **regression**: https://github.com/argoproj/argo-helm/pull/1128
- **CVE**: https://github.com/argoproj/argo-helm/pull/1124
- https://github.com/argoproj/argo-helm/pull/1110
=> feat(infra-apps): argo-cd 3.33.*

README.md, charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/values.yaml
Removes values that are not used in the chart, also removes the redundant `appVersion` setting in the chart.
=> fix(vault-monitoring): remove unused values

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Adds the possibility to configure as `securityContext` for the slack bot  https://github.com/argoproj/argo-helm/pull/1116
- Fixes #558
=> feat(argo-apps): argocd-notifications 1.8

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Updates lokiStack to target version `2.6.*`
closes #561
* uses now Grafana Chartversion `6.21.2`  (old `6.16.12`)
* uses Grafana version `8.3.5` (old `8.1.6`) https://github.com/grafana/helm-charts/pull/1028
* Features added & CVEs:
* https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v8-2
* https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v8-3
Changes in Grafana Chart
* https://github.com/grafana/helm-charts/pull/845
* https://github.com/grafana/helm-charts/pull/865
* https://github.com/grafana/helm-charts/pull/847
*  https://github.com/grafana/helm-charts/pull/986
*  https://github.com/grafana/helm-charts/pull/870
* https://github.com/grafana/helm-charts/pull/887
---
=> chore(lokiStack): update to 2.6.* #561

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
updates kubeEventExporter chart to target version 0.12.*
- https://github.com/bitnami/charts/pull/9011
deployed application  version is still 0.11.0, only the chart was updated
closes https://github.com/adfinis-sygroup/helm-charts/issues/560
=> feat(infra-apps): kubeEventExporter 1.4

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates Falco Chart Version to `1.17.*`
closes #565
* uses falco 0.31.0 
* https://github.com/falcosecurity/charts/pull/308 
* https://github.com/falcosecurity/charts/pull/302
* Update to falco 0.31.0 [changelog](https://github.com/falcosecurity/falco/blob/0.31.0/CHANGELOG.md)
=> chore(falco): update to 1.17.1 #565

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates FalcoExporter Chart to version 0.8.*
Closes #566
* uses falco-expoter `v0.7.0`
* https://github.com/falcosecurity/charts/pull/299
* [falco-exporter changelog](https://github.com/falcosecurity/falco-exporter/releases/tag/v0.7.0)
* https://github.com/falcosecurity/falco-exporter/pull/68
* https://github.com/falcosecurity/falco-exporter/pull/64
=> chore(falcoExporter): update to version 0.8.*

charts/customer-center/Chart.yaml, charts/customer-center/README.md
=> chore(customer-center): update to v3.2.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/examples/nginx-ingress-on-aks.yaml, charts/infra-apps/examples/nginx-ingress.yaml
Add the values needed to configure the ingress that is part of `infra-apps` as default. This should always be the default on cluster where only one ingress exists (which is the case in most deployments).
=> docs(infra-apps): document setting ingress as default class

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates kube-prometheus-stack to use version `33.1.*`
[From 32.x to 33.x](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-32x-to-33x)
> This upgrades the node exporter Chart to v3.0.0. Please review the changes to this subchart if you make customizations to hostMountPropagation.
* node-exporter Chart `v2.5.0 > v3.0.0`
> [From 2x to 3x](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter#from-2x-to-3x)
https://github.com/prometheus-community/helm-charts/pull/1583
* kube-state-metrics Chart `v4.4.3 > v4.7.0`
* grafana Chart `v6.21.2 > v6.22.0`
* prometheus-operator `v0.54.0 > v0.54.1`
---
=> chore(kube-prom-stack): update to 33.1

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Updates ArgoRollout to version `2.10.*`
* https://github.com/argoproj/argo-helm/pull/1138
=> chore(argoRollouts): update to v2.10.*

charts/rmd/Chart.yaml, charts/rmd/README.md, charts/rmd/templates/configmap.yaml, charts/rmd/values.yaml
=> feat(rmd): add tls option for email as env var

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates ArgoCD  to use `3.35.*`
* https://github.com/argoproj/argo-helm/pull/1131
* https://github.com/argoproj/argo-helm/pull/1098
=> chore(argoCD): update to 3.35.*

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/templates/prometheus-msteams.yaml
Fix missing template for promtheus-teams
=> fix(misc-apps): missing template for prometheus-msteams

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
The "Prometheus" and (if enabled) "Prometheus" datasources used to have a randomly generated uid. The chart has changed this to use a well known uid (`prometheus` and `prometheus-replica-[0-9]*`).
This will only affect dashboards that directly reference a datasource by uid. All of our included dashboards do not do this, they reference the "default" dashboard (which now has the uid `prometheus`).
Should you encounter dashboards that reference a hard-coded uid after deploying this then the dashboards should be refactored to reference the default datasource or use the new uid.
- https://github.com/prometheus-community/helm-charts/pull/1816
=> feat(infra-apps): kube-prometheus-stack 33.2.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates our `infra-apps` to use [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) version `34.0.*`
n/a
Run these commands to update the CRDs before applying the upgrade:
https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-33x-to-34x
* https://github.com/prometheus-community/helm-charts/pull/1873
* https://github.com/prometheus-operator/prometheus-operator/pull/4552
* https://github.com/prometheus-operator/prometheus-operator/pull/4566
* https://github.com/prometheus-operator/prometheus-operator/pull/4592
* https://github.com/prometheus-operator/prometheus-operator/pull/4535
* https://github.com/prometheus-operator/prometheus-operator/pull/4494
* …
=> chore(infra-apps): update kube-prometheus-stack to version 34.0.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates `infra-appaps` to use [rbac-manager](https://github.com/FairwindsOps/charts/tree/master/stable/rbac-manager) chart version `1.11.*`
n/a
* https://github.com/FairwindsOps/charts/pull/739
* https://github.com/FairwindsOps/rbac-manager/pull/251
* https://github.com/FairwindsOps/rbac-manager/pull/252
* https://github.com/FairwindsOps/rbac-manager/pull/253
* https://github.com/FairwindsOps/rbac-manager/pull/254
* https://github.com/FairwindsOps/rbac-manager/pull/255
* https://github.com/FairwindsOps/rbac-manager/pull/258
* https://github.com/FairwindsOps/rbac-manager/pull/262
* https://github.com/FairwindsOps/rbac-manager/pull/263
* https://github.com/FairwindsOps/rbac-manager/pull/266
* https://github.com/FairwindsOps/rbac-manager/pull/267
* …
=> chore(infra-apps): update rbac-manager to v1.11.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates `infra-apps` to deploy [thanos chart](https://github.com/bitnami/charts/tree/master/bitnami/thanos) version `10.1.*`
n/a
* https://github.com/bitnami/charts/commit/b1d6f97af442f721ff3e2356cc52ce870197c7f4
* https://github.com/bitnami/charts/pull/9322
* https://github.com/bitnami/charts/pull/9358
---
=> chore(infra-apps): update thanos to v10.1.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates `infra-appas` to use [kured chart](https://github.com/weaveworks/kured/tree/main/charts/kured) version `v2.12.*`
n/a
* https://github.com/weaveworks/kured/pull/505
---
=> chore(infra-apps): update kured to v2.12.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
I made the Argo CD notifications ServiceMonitor config more consistent and this merges that. It's tagged as a fix since it really is one for us (we canonically use `selector` for all of the Argo CD ServiceMonitors).
* https://github.com/argoproj/argo-helm/pull/1177
=> fix(infra-apps): bump argo-cd from 4.0.* to  4.1.*

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Argo Rollouts 1.2.0 supports K8s v1.22! See [release notes](https://github.com/argoproj/argo-rollouts/releases/tag/v1.2.0) for more features and fixes.
* https://github.com/argoproj/argo-rollouts/releases/tag/v1.2.0
* https://github.com/argoproj/argo-helm/pull/1135
* https://github.com/argoproj/argo-helm/pull/1163
=> feat(argo-apps): argo-rollouts v1.2.0 (chart 2.12)

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/_helpers.tpl
Removing a duplicate label in the barman chart: `app.kubernetes.io/managed-by: {{ .Release.Service }}`
=> barman: remove duplicate label

hack/chart-testing/ct-install.yaml, hack/chart-testing/ct.yaml
Fixes the target branch used by `chart-testing` to check for changes.
=> fix(chart-testing): update target branch

charts/argoconfig/Chart.lock, charts/argoconfig/Chart.yaml, charts/argoconfig/README.md
Update the `argoconfig` library chart to use the new `common` release done for #616. This is pretty much just housekeeping since the upstream chart does not contain any significant changes.
=> chore(argoconfig): update commons from 0.0.6 to 0.0.7

charts/argo-apps/Chart.lock, charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/azure-apps/Chart.lock, charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/backup-apps/Chart.lock, charts/backup-apps/Chart.yaml, charts/backup-apps/README.md, charts/infra-apps/Chart.lock, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/logging-apps/Chart.lock, charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/misc-apps/Chart.lock, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/security-apps/Chart.lock, charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/storage-apps/Chart.lock, charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/tracing-apps/Chart.lock, charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md
Update all `*-apps` charts to use the latest `argoconfig` chart. This is just housekeeping, i'm doing it now since today is a day of high churn anyway,
* #620
=> chore(*-apps): update argoconfig from 0.7.4 to 0.7.6

charts/rbac-definitions/Chart.lock, charts/rbac-definitions/Chart.yaml, charts/rbac-definitions/README.md, charts/rbac-definitions/tests/__snapshot__/rbacdefinitions_test.yaml.snap
Update the common dependency in rbac-definitions as part of todays springcleaning.
* #616
=> chore(rbac-definitions): update common from 0.0.6 to 0.0.7

charts/cert-manager-issuers/Chart.lock, charts/cert-manager-issuers/Chart.yaml, charts/cert-manager-issuers/README.md, charts/cert-manager-issuers/tests/__snapshot__/clusterissuers_test.yaml.snap, charts/cert-manager-issuers/tests/__snapshot__/issuers_test.yaml.snap
Update the common dependency in cert-manager-issuers as part of todays springcleaning.
* #616
=> chore(cert-manager-issuers): update common from 0.0.6 to 0.0.7

charts/csi-secret-provider-class/Chart.lock, charts/csi-secret-provider-class/Chart.yaml, charts/csi-secret-provider-class/README.md, charts/csi-secret-provider-class/tests/__snapshot__/dummydeployment_test.yaml.snap, charts/csi-secret-provider-class/tests/__snapshot__/secretproviderclass_test.yaml.snap
Update the common dependency in csi-secret-provider-class as part of todays springcleaning.
* #616
=> chore(csi-secret-provider-class): update common from 0.0.6 to 0.0.7

README.md, charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Updates `timed` to make it use the right versions ootb so we don't need to override them in the actual deployments.
Once this is merged we can enable auto-syncing for timed similar to how customer-center already works.
=> chore(timed): update image versions to latest published tags

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD to 2.3.3 and add a bunch more settings.
The included Dex update mainly updates the underlying alpine image to fix CVE-2021-36159 and CVE-2021-3711.
* Argo CD [2.3.3 releasenotes](https://github.com/argoproj/argo-cd/releases/tag/v2.3.3)
* Dex [2.30.2](https://github.com/dexidp/dex/releases/tag/v2.30.2) and [2.30.1](https://github.com/dexidp/dex/releases/tag/v2.30.1)
* https://github.com/argoproj/argo-helm/pull/1209
* https://github.com/argoproj/argo-helm/pull/1208
* https://github.com/argoproj/argo-helm/pull/1150
* https://github.com/argoproj/argo-helm/pull/1205
* https://github.com/argoproj/argo-helm/pull/1204
* https://github.com/argoproj/argo-helm/pull/1201
=> feat(infra-apps): bump argo-cd from 4.2 to 4.5

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update opentelemetry-collector to 0.47.0 and add a bunch of features to the chart.
* [opentelemetry-collector v0.47.0 releasenotes](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.47.0)
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/156
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/154
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/151
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/148
=> feat(tracing-apps): update opentelemetry-collector from 0.9 to 0.12

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
This update contains the update from velero 1.8.0 to 1.8.1
* [1.8.1 Release](https://github.com/vmware-tanzu/velero/releases/tag/v1.8.1)
* https://github.com/vmware-tanzu/velero/pull/4706
* https://github.com/vmware-tanzu/helm-charts/commit/9fc4000b3d64549d2a3c6941d1fd59fc78ffae24
=> feat(infra-apps): update velero chart from 2.28 to 2.29

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates kured to use Chart version 2.13.*
n/a
* https://github.com/weaveworks/kured/pull/524
=> chore(kured): update to use chart version 2.13.*

charts/rmd/Chart.yaml, charts/rmd/README.md, charts/rmd/templates/_helpers.tpl, charts/rmd/templates/configmap.yaml, charts/rmd/templates/cronjob.yaml, charts/rmd/templates/deployment-rmd.yaml, charts/rmd/templates/job-dbmigrate.yaml, charts/rmd/templates/secret-backend.yaml, charts/rmd/values.yaml
Remove secrets from ConfigMap
Add support for external secrets for database and mailserver password.
=> fix(rmd): move rmd secrets

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Mopsos 0.3.2 🥳  (contains a bunch of dep updates to gorm and otel)
* https://github.com/adfinis-sygroup/mopsos/releases/tag/v0.3.1
* https://github.com/adfinis-sygroup/mopsos/releases/tag/v0.3.2
=> chore(mopsos): bump from 0.3.0 to 0.3.2

charts/mopsos/Chart.lock, charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/ci/default-values.yaml, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap, charts/mopsos/tests/secret_basicauthusers_test.yaml, charts/mopsos/values.yaml, hack/chart-testing/ct-install.yaml, hack/chart-testing/ct.yaml
Deploys a Grafana instance complete with pre-configured postgres datasource.
I'm also tweaking some of the default values to clarify that it doesn't make sense to run mopsos with sqlite unless on test.
=> feat(mopsos): add Grafana deployment

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/dashboards/mopsos-data.json, charts/mopsos/templates/configmap-dashboard.yaml, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap, charts/mopsos/values.yaml
* Add a simple dashboard that allows querying data from the records table.
* Fix `s/jsonSecure/jsonSecureData/` "typo"
=> feat(mopsos): add default dashboard

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/dashboards/mopsos-data.json, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Uses `cluster_name IN (${cluster})` and `application_name IN (${application})` to allow selecting multiple clusters/apps at once.
=> feat(mopsos): allow selecting multiple clusters/apps

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap, charts/mopsos/values.yaml
Use the default dashboard as the home dashboard.
=> feat(mopsos): set default home dashboard

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Refactor so mopsos doesn't parse the event twice and more testing.
* mopsos release: https://github.com/adfinis-sygroup/mopsos/releases/tag/v0.3.3
=> fix(mopsos): update mopsos from 0.3.2 to 0.3.3

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap, charts/mopsos/values.yaml
The dashboards bit was added in the wrong place in #645
=> fix(mopsos): move misplaced grafana.ini section

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* update nginx-ingress from 1.1 to 1.2
I'm bumping the minor version since the bump also contains a bunch of changes. If y'all want as much security as possible and you can activate `SYS_CHROOT` on the Pod, the nginx-ingress can now run in a chrooted env.
* CVE-2021-25745
* CVE-2021-25746
=> feat(infra-apps): update nginx-ingress from 4.0 to 4.1

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/ci/default-values.yaml, charts/storage-apps/examples/minio.yaml, charts/storage-apps/templates/minio.yaml, charts/storage-apps/values.yaml
Add chart for minio in storage-apps
=> feat(storage-apps): add minio

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update dex to v0.8
Closes https://github.com/adfinis-sygroup/helm-charts/issues/666
n/a
- [Update dex version from v2.30.0 to v2.31.1](https://github.com/dexidp/helm-charts/commit/878f6ae5bf76520688c33e5829ee381fc8312202)
- Upstream dex has a huge amount of changes, check release notes before updating:
- https://github.com/dexidp/dex/releases/tag/v2.31.0
- https://github.com/dexidp/dex/releases/tag/v2.30.3
- Apart from a buch of bugfixes and updating to go 1.17, there are also several security bumps like underlying base image
- [Add serviceMonitor](https://github.com/dexidp/helm-charts/commit/26b40686a99ba14512cad63c5a91159f77fda2ba)
- [rename `ClusterRole` and `ClusterRoleBilding` to `Role` and `RoleBinding` to allow Deployments without …
=> feat(security-apps): Bump dex to 0.8

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Updates opentelemetry-collector to 0.19 (chart version 0.15.*). 
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/161
* https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.48.0
* Update OTLP to v0.15.0
* Lots of deprecations and removal of deprecations, check upstreams releasenotes
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/164
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/159
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/171
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/174
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/178
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/169
* …
=> feat(tracing-apps): update opentelemetry-collector from 0.12 to 0.15

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
This upgraded prometheus-operator to v0.56.0 and prometheus to v2.35.0
FFI: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#from-34x-to-35x
Closes https://github.com/adfinis-sygroup/helm-charts/issues/662
Update manually the CRDs before applying the changes as described in [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#from-34x-to-35x)
```
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.56.0/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.56.0/example/prometheus-operator-crd/monitor …
```
=> feat(infra-apps): Kube-prometheus-stack to 35.0.*

charts/infra-apps/Chart.lock, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/templates/argocd.yaml, charts/infra-apps/templates/cert-manager-monitoring.yaml, charts/infra-apps/templates/certmgr-issuers.yaml, charts/infra-apps/templates/certmgr.yaml, charts/infra-apps/templates/ingress.yaml, charts/infra-apps/templates/kubernetes-event-exporter.yaml, charts/infra-apps/templates/kured.yaml, charts/infra-apps/templates/monitoring.yaml, charts/infra-apps/templates/rbac.yaml, charts/infra-apps/templates/thanos.yaml, charts/infra-apps/templates/velero.yaml, charts/infra-apps/values.yaml
Adds the possibility to add annotations on all the apps deployed via infra-apps.
If this works out to my liking i'll add it to all the other `*-apps` charts as well.
=> feat(infra-apps): allow adding annotations at the app level

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates infra-apps to deploy thanos chart version 10.3.*
Closes https://github.com/adfinis-sygroup/helm-charts/issues/663
n/a
Changes:
- https://github.com/bitnami/charts/pull/9447 https://github.com/bitnami/charts/commit/7e3b2d2fdcd740a31fa3a1adffadf28eac03ee7c
- https://github.com/bitnami/charts/pull/9485 https://github.com/bitnami/charts/commit/30c773fef3a4948be87c7d7758cc055300b36cca
- https://github.com/bitnami/charts/pull/9590 https://github.com/bitnami/charts/commit/ebc73d5903e68e731ae3a3a651ccd9bc8cec8a1f
=> feat(infra-apps): Bump thanos to 35.0

charts/argo-apps/Chart.lock, charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/templates/argo-rollouts.yaml, charts/argo-apps/templates/argocd-notifications.yaml, charts/argo-apps/values.yaml
Update Argo Rollouts to 2.14 chart + some spring cleaning:
* update argoconfig dependency to 0.8.0
* implement annotation overriding support
* deprecate argocd-notifications deployment
* Argo Rollouts 2.14:
* https://github.com/argoproj/argo-helm/pull/1212
* https://github.com/argoproj/argo-helm/pull/1202
* Fixes #660 
* Fixes #651
=> feat(argo-apps): upgrade rollouts from 2.12 to 2.14 + spring cleaning

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates Falco to Chart Version `1.18.*`
Fixes #667
* https://github.com/falcosecurity/charts/pull/322
* https://github.com/falcosecurity/charts/pull/324
* https://github.com/falcosecurity/charts/pull/325
=> chore(falco): update to 1.18.*

charts/customer-center/Chart.yaml, charts/customer-center/README.md
This updates the Customer Center to its latest release v3.2.3
=> chore(customer-center): update to v3.2.3

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
updates vault-monitoring to use version `0.2.*`
https://github.com/adfinis-sygroup/helm-charts/pull/610
=> chore(sec-apps): update vaultMonitoring

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Updates both, ceph-csi-rbd / cephfs to version `3.6.1` (also appVersion)
#671 
#670
* BREAKING REMOVAL OF RBD THICK PROVISIONING https://github.com/ceph/ceph-csi/issues/2795
New Features:
* NFS based dynamic provisioner
* Fuse Mount recovery
* AWS KMS encryption
Several Enhancements / Bug Fixes listed here:
* https://github.com/ceph/ceph-csi/releases/tag/v3.6.0
* https://github.com/ceph/ceph-csi/releases/tag/v3.6.1
=> chore(update): ceph-csi to 3.6.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* add istio compatibility for metrics
* https://github.com/argoproj/argo-helm/pull/1270
=> feat(infra-apps): update argo-cd chart from 4.5 to 4.6

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* ensure kured on 1.24 gets the correct toleration
* https://github.com/weaveworks/kured/pull/539
=> feat(infra-apps): update kured from 2.13 to 2.14

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* add support for ingress.extraRules
* https://github.com/bitnami/charts/pull/10253
=> feat(infra-apps): update thanos from 10.3 to 10.4

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Adds a bunch of security updates for various deps.
Release notes: https://github.com/adfinis-sygroup/mopsos/releases/tag/v0.3.4
=> fix(mopsos): update mopsos from 0.3.3 to 0.3.4

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates the redis-ha chart dependency to 4.16.0.
* https://github.com/argoproj/argo-helm/pull/1296
=> feat(infra-apps): update argo-cd chart from 4.6 to 4.7

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/examples/neuvector.yaml, charts/security-apps/values.yaml
Adds the ability to deploy NeuVector based on their charts to our `security-apps` chart.
=> feat(security-apps): add neuvector core + monitor

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/templates/neuvector.yaml, charts/security-apps/templates/neuvectorMonitor.yaml
I forgot to add the templates :facepalm: and i'm gonna turn in my YAML license if this continues happening :roll_eyes:
=> fix(security-apps): add actual neuvector apps

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
updates chart-museum chart verison to `3.8.*`
fixes #665
* https://github.com/chartmuseum/charts/pull/26
* https://github.com/chartmuseum/charts/pull/40
* https://github.com/chartmuseum/charts/pull/35
=> chore(misc-apps): update chartmuseum to 3.8.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates gatekeeper to use version `3.8.*`
fixes #668
* https://github.com/open-policy-agent/gatekeeper/pull/2039
* https://github.com/open-policy-agent/gatekeeper/pull/2038
* [Release Notes of 3.8.0](https://github.com/open-policy-agent/gatekeeper/releases/tag/v3.8.0)
=> chore(security-apps): gatekeeper update to 3.8.*

charts/backup-apps/Chart.yaml, charts/backup-apps/README.md, charts/backup-apps/values.yaml
Updates barman to chart version `0.8.*`
fixes #661
* https://github.com/adfinis-sygroup/helm-charts/pull/615
* https://github.com/adfinis-sygroup/helm-charts/pull/616
* https://github.com/adfinis-sygroup/helm-charts/pull/618
* https://github.com/adfinis-sygroup/helm-charts/pull/631
* https://github.com/adfinis-sygroup/helm-charts/pull/635
* https://github.com/adfinis-sygroup/helm-charts/pull/691
* https://github.com/adfinis-sygroup/helm-charts/pull/697
=> chore(backup-apps): update barman to 0.8.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD to 2.4 :tada:
Contains a bunch of features:
* Web Terminal In Argo CD UI :computer: 
* Access Control For Pod Logs & Web Terminal :scroll: 
* OpenTelemetry Tracing Integration :eyes: 
* Power PC and IBM Z Support :nerd_face: 
* Secured Redis connection :lock: 
* ApplicationSet Gitea support :deciduous_tree: 
and more, checkout the [upstream releasenotes](https://github.com/argoproj/argo-cd/releases/tag/v2.4.0) and the [2.3 to 2.4 upgrade guide](https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/)
potential breaking changes for us are:
* Helm 2 support is removed (should not affect us)
* Support for private repo SSH keys using the SHA-1 signature hash algorithm is removed
* Environments with fine-tuned RBAC policies will want to have a closer look at …
=> feat(infra-apps): update argo-cd from 4.8 to 4.9

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/templates/_helpers.tpl, charts/mopsos/templates/deployment.yaml, charts/mopsos/templates/rollout.yaml, charts/mopsos/templates/service.yaml, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap, charts/mopsos/values.yaml
Add resources for continuous delivery using [Argo Rollouts](https://argoproj.github.io/argo-rollouts/). Also bump  mopsos to contain all dependency updates that i merged last week (all of them are basic bugfixes in pretty much not-important/unused code).
=> feat(mopsos): add argo rollouts config

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
* #718
Now uses Falco Version 0.32.0 ! See [Changelog](https://github.com/falcosecurity/falco/blob/0.32.0/CHANGELOG.md#v0320) 
* https://github.com/falcosecurity/charts/pull/340
* https://github.com/falcosecurity/charts/pull/344
* https://github.com/falcosecurity/charts/pull/347
* https://github.com/falcosecurity/charts/pull/349
* Audit Log is now supported via k8saudit plugin (when enabled, syscall instrumentation will be disabled)
* dynamicBackend support for Audit Log is now deprecated
=> feat(falco): update to 1.19.*

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Updates fluentD to `5.1.*`
* #714
* https://github.com/bitnami/charts/pull/10253
* https://github.com/bitnami/charts/commit/9ea06336a476d36fd290acb56b796e4f2346ee9c
* https://github.com/bitnami/charts/commit/df653ffda7b5a9953c37b3878a9089fdc4f2722c
* https://github.com/bitnami/charts/commit/ecf3f4c1708a18468391b37180c3ebb957b1912b
* https://github.com/bitnami/charts/pull/10332
* https://github.com/bitnami/charts/commit/88a54673f5ed20975dc6c065789851eac8b471d6
* https://github.com/bitnami/charts/pull/10523
* https://github.com/bitnami/charts/commit/2cada87ed4967d5cb578b0409a0bb1edee79029a
* https://github.com/bitnami/charts/commit/5db133a8b55bc29daa5b7d64c0cd1a0b888e4761
* https://github.com/bitnami/charts/pull/10600
* …
=> feat(fluentD): update to 5.11.*

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
For a detailed changelog please view https://fluentbit.io/announcements/v1.9.4.
Update fluent-bit image to 1.9.0.
* https://github.com/fluent/helm-charts/commit/c9a8016525a9b6f04c1430797795bb80eae89db0
* Fixes #715
=> feat(logging-apps): update fluentbit from 0.19 to 0.20

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates Dex from v0.8 to v0.9
- Bump application version from v2.31.1 to v2.32.0
* Closes #716
=> chore(security-apps): Dex upgrade to v0.9

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update thanos from v10.4 to v10.5
- Update [image tag for volumePermissions](https://github.com/bitnami/charts/commit/18f9389f3a6c96319597d0b77dad351a349b246f)
- Update [componente versions](https://github.com/bitnami/charts/commit/f47996b7385c08698cf89c636e616addbf676add)
Closes https://github.com/adfinis-sygroup/helm-charts/issues/712
n/a
=> chore(infra-apps): Update thanos to v10.5

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update opentelemetry-collector from `0.15.*` to `0.20.1`
* Fixes https://github.com/adfinis-sygroup/helm-charts/issues/721
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/226
* Update OpenTelemtry Collector to 0.53.0 https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.53.0
* Removes a lot of deprecation
* `pmetric.Exemplar.ValueType() `now returns new type `ExemplarValueType`
* Replace usage of `config.MapConverterFunc` with `config.MapConverter`
* Remove `AddCollectorVersionTag`
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/216
* removes the deprecated `agentCollector` and `standaloneCollector` sections from `values.yaml.` Instead, `mode` must be used.
* https://github.com/open-telemetry/opentelemetry-helm-charts/pull/184
* …
=> feat(tracing-apps): update opentelemetry-collector from 0.15.* to 0.20.1

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Mopsos merged a bunch of upstream library changes containing patches and released it as [v0.3.6](https://github.com/adfinis-sygroup/mopsos/releases/tag/v0.3.6).
* Release Notes: https://github.com/adfinis-sygroup/mopsos/releases/tag/v0.3.6
* https://github.com/adfinis-sygroup/mopsos/pull/78
* https://github.com/adfinis-sygroup/mopsos/pull/79
* https://github.com/adfinis-sygroup/mopsos/pull/74
=> fix(mopsos): update from 0.3.5 to 0.3.6

README.md, hack/config/update-readme/README.md.gotmpl
=> docs: add artifacthub badge

CODEOWNERS
Update CODEOWNERS to reflect changes.
=> chore: remove @michaelimfeld from CODEOWNERS

charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Update gorm and cobra dependencies.
* Release notes: https://github.com/adfinis-sygroup/mopsos/releases/tag/v0.3.7
=> fix(mopsos): update mopsos from 0.3.6 to 0.3.7

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/falco.yaml, charts/security-apps/values.yaml
Update falco to 2.0 version of the chart. The charts changelog says this about the v2 release
**Note**
*This release is a complete refactor of the Falco Helm Chart. Thus, it introduces some breaking changes.*
*Please, do not reuse values from previous chart installations.*
* Upgrade Falco to 0.32.1
* Massive refactoring of the chart implementation
* Add ability to use either a daemonset or a deployment (depeding on the installation scenario)
* Add ability to specify custom network services
* New settings for the drivers configuration
* New Makefile to generate helm documentation
* Add values-k8saudit.yaml preset for the k8saudit plugin
* Fix use `load_plugins` instead of `loadPlugins` in Falco configuration
* Update `containerSecurityContext` (former `securityContext`) now takes …
=> feat(security-apps): update falco from 1.19 to 1.20

charts/csi-secret-provider-class/Chart.yaml, charts/csi-secret-provider-class/README.md, charts/csi-secret-provider-class/tests/__snapshot__/dummydeployment_test.yaml.snap, charts/csi-secret-provider-class/tests/__snapshot__/secretproviderclass_test.yaml.snap, charts/csi-secret-provider-class/values.yaml
Updates the pause container and uses it from the new registry.k8s.io location that replaces gcr.io
=> fix(csi-secret-provider-class): update pause container from k8s.gcr.io/pause:3.4.1 to registry.k8s.io/pause:3.7

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/stackrox.yaml, charts/security-apps/templates/stackrox-central-services.yaml, charts/security-apps/templates/stackrox-secured-cluster-services.yaml, charts/security-apps/values.yaml
Add [StackRox](https://stackrox.io) to security app. Same arguments as to why we added NeuVector also apply to StackRox.
Also, this will allow us to compare the two in a similar setting.
=> feat(security-apps): add stackrox deployment

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/examples/mimir.yaml, charts/infra-apps/templates/mimir.yaml, charts/infra-apps/values.yaml
Adds mimir-distributed chart to infra-apps
n/a
=> feat(infra-apps): add mimir chart to infra

docs/argocd-app-of-apps.md
Documents our component deprecation policy for `-apps` charts.
=> docs: deprecation policy for app-of-apps components

charts/back8sup/Chart.yaml, charts/back8sup/README.md, charts/back8sup/templates/cronjob.yaml, charts/back8sup/values.yaml
The chart was not using the `securityContext` setup in the values file. Here is a fix.
n/a
=> feat(back8sup): add security contexts to cronjob

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update Jaeger Operator to 1.35.0. See [here](https://github.com/jaegertracing/jaeger-operator/blob/main/CHANGELOG.md#1350-2022-06-16) for release notes. Main highlight seems to be improved OpenShift suppport.
* https://github.com/jaegertracing/helm-charts/pull/380
=> feat(tracing-apps): update jaeger-operator from 2.32.2 to 2.33.0

CODEOWNERS
=> chore: remove @aziiee from CODEOWNERS

charts/back8sup/Chart.yaml, charts/back8sup/README.md, charts/back8sup/values.yaml, charts/caasperli/Chart.yaml, charts/caasperli/README.md, charts/caasperli/values.yaml, charts/customer-center/Chart.yaml, charts/customer-center/README.md, charts/customer-center/values.yaml, charts/huawei-csi-plugin/Chart.yaml, charts/huawei-csi-plugin/README.md, charts/huawei-csi-plugin/values.yaml, charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap, charts/mopsos/values.yaml
Fixes the imageref on several Charts.
Related to #762
=> fix(imagerefs): ghcr.io/adfinis is the new imagref

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md, charts/openshift-etcd-backup/values.yaml
=> fix imageref

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates StackRox to the new 3.71.0 version released 4 days ago.
A complete changelog is [here](https://github.com/stackrox/stackrox/blob/master/CHANGELOG.md#3710).
It doesn't look like anything is breaking for us.
=> feat(security-apps): update stackrox from 70.1.0 to 71.0.0

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Adds a `extraObjects` value that can be used to deploy raw manifests alongside Argo Rollouts.
* https://github.com/argoproj/argo-helm/pull/1366
=> feat(argo-apps): update argo-rollouts from 2.17 to 2.18

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Updates to the latest and greatest version. Notable change ist updating the base image.
* https://github.com/adfinis/openshift-etcd-backup/releases/tag/v1.6.4
=> fix(openshift-etc-backup): update from 1.6.0 to 1.6.4

charts/argoconfig/Chart.lock, charts/argoconfig/Chart.yaml, charts/argoconfig/README.md, charts/argoconfig/templates/_applicationSet.yaml
Adds ApplicationSet support to the `argoconfig` library chart in preparation for #768, also includes orga rename update from common.
* #768
=> feat(argoconfig): add ApplicationSet support

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
update loki-stack to version 2.7.*
https://grafana.com/docs/loki/latest/release-notes/v2-5/
https://grafana.com/docs/loki/latest/release-notes/v2-6/
Most notable changes are changes to the config `split_queries_by_interval` -parameter.
I haven't gathered any mention of that in our repos.
https://github.com/grafana/loki/blob/main/CHANGELOG.md
loki/promtail version:
2.4.2 -> 2.6.1
=> update loki-stack to version 2.7.*

charts/customer-center/Chart.yaml, charts/customer-center/README.md
* [ x] This PR contains a description of the changes I'm making
* [ x] I updated the version in Chart.yaml
* [x ] I updated applicable README.md files using  `pre-commit run`
* [ x] I documented any high-level concepts I'm introducing in `docs/`
* [x ] CI is currently green and this is ready for review
* [ x] I am ready to test changes after they are applied and released
=> chore(customer-center): update to v3.2.4

charts/misc-apps/Chart.lock, charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
upstream update to version 0.8.0 of the signalilo helm chart.
https://github.com/vshn/signalilo/releases/tag/v0.11.0
added feature: https://github.com/vshn/signalilo/pull/104
=> updated upstream chart version

charts/back8sup/Chart.yaml, charts/back8sup/README.md
Updates back8sup to use an image tag that was actually pushed to the ghcr registry.
* https://github.com/adfinis/back8sup/releases/tag/v0.7.10
=> fix(back8sup): update from 0.7.9 to 0.7.10

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Update to latest [promitor](https://promitor.io/) contains the following changes:
* Provide scraper for Azure Database for MySQL Servers
* Honor flag not to include timestamps in system metrics for Prometheus
* Improved performance for scraping large amoung of Azure resrouces to reduce CPU usage
* https://github.com/promitor/charts/pull/119
* https://github.com/tomkerkhove/promitor/releases/tag/Scraper-v2.7.0
* https://github.com/tomkerkhove/promitor/releases/tag/ResourceDiscovery-v0.8.0
=> feat(azure-apps): update promitor disco from 0.7 to 0.8 and scraper from 2.7 to 2.8

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates the Velero chart to 2.31. The main feature included here is the possibility to manage PrometheusRules directly using the chart as well as a small update to Velero and a bunch of new parameters.
Keep in mind that you  might also need to update any csi or storage integrations to match the new Velero 1.9.1 version.
* fixes #792 
* add dnsConfig parameter https://github.com/vmware-tanzu/helm-charts/pull/386
* add clientPageSize parameter https://github.com/vmware-tanzu/helm-charts/pull/389
* add storeValidationFrequency parameter https://github.com/vmware-tanzu/helm-charts/pull/391
* Velero 1.9.1 with csiSnapshotTimeout https://github.com/vmware-tanzu/helm-charts/pull/394
* add PrometheusRule https://github.com/vmware-tanzu/helm-charts/pull/397
* add support for container lifecycle …
=> feat(infra-apps): update velero from 2.30 to 2.31

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/ci/default-values.yaml, charts/misc-apps/examples/argocd-apps.yaml, charts/misc-apps/templates/argocd-apps.yaml, charts/misc-apps/values.yaml
The 5.0 version of the chart that was merged into infra-apps with #780 removes the ability to setup additionalProjects and additionalApplications. The `argocd-apps` Helm chart i'm introducing with this PR replaces them.
* #780
=> feat(misc-apps): add argocd-apps chart

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updated the Kured chart to the next major version.
This will probably break most of the installations:
>  The Helm chart labels have been realigned to conform with the [standard labels](https://helm.sh/docs/chart_best_practices/labels/#standard-labels) in the current Helm Chart Best Practices guide, so this upgrade will fail unless the DaemonSet is deleted and recreated. The only way that Helm supports delete and recreate is by uninstalling, so please uninstall the Kured Helm chart before installing again with v3.x.
https://github.com/adfinis/helm-charts/issues/793
=> feat(infra-apps): Update kured to 3.0.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updated the kured repo url as it changed due to them now being a CNCF project. Also updated to version 4.0.1; there was a new minor version introduced as the url changed.
https://github.com/kubereboot/kured/issues/633
=> fix(infra-apps): Update kured repo url

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updated the code comments with the new repo url for kured
=> patch(infra-apps): Update Comments with new URL

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/ci/default-values.yaml, charts/misc-apps/examples/keda.yaml, charts/misc-apps/templates/keda.yaml, charts/misc-apps/values.yaml
Adds [KEDA](https://keda.sh) to misc-apps
=> feat(misc-apps): add KEDA

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updated the  rbacManager Chart to 1.13.1, there is now a field for the `imageDigest`.
There are no breaking changes for the image, just minor feature additions (see [here](https://github.com/FairwindsOps/rbac-manager/releases))
https://github.com/adfinis/helm-charts/issues/790#event-7415947171
=> feat(infra-apps): Update rbacManager to 1.13.1

charts/backup-apps/Chart.yaml, charts/backup-apps/README.md, charts/backup-apps/values.yaml
Refactors the entrypoint script to be configurable via a ConfigMap and updates and references to the adfinis-sygroup github orga.
* https://github.com/adfinis/helm-charts/pull/708 (ConfigMap change)
* https://github.com/adfinis/helm-charts/pull/764
* fixes #787
=> feat(backup-apps): update barman from 0.8 to 0.9

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates the thanos chart to 11.5.* The main features included here are the ones described in the issues fixed and features.
- [Creates separate service for grpc port of query module](https://github.com/bitnami/charts/pull/11051)
- [Update default prometheusrule value](https://github.com/bitnami/charts/pull/10979)
- [Fix Deprecation Warning of thanos](https://github.com/bitnami/charts/pull/11178)
- [Updating components versions](https://github.com/bitnami/charts/commit/a49e56897c178ad4230f139fad2c21572cfb8934)
- [Update URLs to point to the new bitnami/containers monorepo](https://github.com/bitnami/charts/pull/11352)
- [Conditionally Set objstore arg and OBJSTORE_CONFIG for Thanos receive](https://github.com/bitnami/charts/pull/11274)
- [Add support for image digest apart from …
=> feat(thanos): Update thanos to 11.5.*

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Updates the loki chart to 2.8.* The main feature included here is the possibility to support configurable datasource URLs.
- [Support configurable datasource urls](https://github.com/grafana/helm-charts/pull/1374)
=> feat(loki): Update loki to 2.8.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates gatekeeper to use version `3.9.*`
fixes #801
* https://github.com/open-policy-agent/gatekeeper/pull/2113
* https://github.com/open-policy-agent/gatekeeper/pull/2092
* https://github.com/open-policy-agent/gatekeeper/pull/2116
* https://github.com/open-policy-agent/gatekeeper/pull/2130
* https://github.com/open-policy-agent/gatekeeper/pull/2121
* https://github.com/open-policy-agent/gatekeeper/pull/2110
* https://github.com/open-policy-agent/gatekeeper/pull/2127
* https://github.com/open-policy-agent/gatekeeper/pull/2054
* https://github.com/open-policy-agent/gatekeeper/pull/2078
* https://github.com/open-policy-agent/gatekeeper/pull/2077
* https://github.com/open-policy-agent/gatekeeper/pull/2017
* https://github.com/open-policy-agent/gatekeeper/pull/2034
* …
=> chore(gatekeeper): update to 3.9.*

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Remove superfluous whitespace in docs.
=> fix(security-apps): valid markdown for links in README

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update Stackrox to the latest version published a few days ago. Main changes seem to be changes in how searching for labels and annotations works
* https://github.com/stackrox/stackrox/releases/tag/3.72.0
=> feat(security-apps): update stackrox from 71.0.0 to 72.0.0

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
updates misc-apps/metallb to use chart version `0.13.x`
#798
Changes in behavior:
* the **biggest change** is the introduction of CRDs and removing support for the configuration via ConfigMap. In order to ease the transition to the new configuration, we provide a conversion tool from ConfigMap to resources (see the “Backward compatibility” section from the [main page](https://metallb.universe.tf/#backward-compatibility).
* the internal architecture was radically changed in order to accomodate CRDs, so please do not hesitate to file an issue.
* The AvoidBuggyIPs flag was removed in order to reduce the api surface a bit. The same result can be achieved using ranges of IPs instead of the CIDR annotation.
* The metallb images from dockerhub are deprecated. From this release, only the images …
=> chore(misc/metallb): update to 0.13.x

charts/infra-apps/Chart.lock, charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates grafana/mimir chart to 3.1.*
fixes #795
* https://github.com/grafana/mimir/pull/2219
* https://github.com/grafana/mimir/pull/2064
* https://github.com/grafana/mimir/pull/2297
* https://github.com/grafana/mimir/pull/2427
* https://github.com/grafana/mimir/pull/2117
* https://github.com/grafana/mimir/pull/2277
* [CHANGE] breaking change Make ConfigMap the default for configStorageType. This means that the Mimir (or Enterprise Metrics) configuration is now created in and loaded from a ConfigMap instead of a Secret. #2277
* Set to Secret to keep existing way of working. See related #2031, #2017, #2089.
* In case the configuration is loaded from an external Secret, useExternalConfig=true, then configStorageType must be set to Secret.
* Having the configuration in a ConfigMap means that …
=> chore(infra/mimir): update to 3.1.x

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Updated azureKvCsiProvider Version to ~~1.2.0~~ 1.3.0
* fixes #710
* fixes #786
=> feat(azure-apps): Update azureKvCsiProvider

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/examples/csi-driver-smb.yaml, charts/storage-apps/templates/csi-driver-smb.yaml, charts/storage-apps/values.yaml
Because it's handy for integrating with legacy storage services.
=> feat(storage-apps): add csi-driver-smb

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md
Update changelog because artifacthub is yelling at me:
> * invalid changes annotation. Please use quotes on strings that include any of the following characters: {}:[],&*#?|-<>=!%@
I might have to clean up our index to unbork it but that will be a problem for future (aka tommorow(ish)) me.
=> fix(infra-apps): proper strings in changelog annotations

hack/chart-testing/ct.yaml, hack/sh/deps/pluto.sh
well, well... turns out .tmp/bin was put into path by various wrapper :(
=> chore(ci): hacky fix for ci fail

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update with a bunch of changes made possible by recent 2.5 release. Namely support self-managed TLS certs and don't deploy unused CRDs.
* https://github.com/argoproj/argo-helm/pull/1596
* https://github.com/argoproj/argo-helm/pull/1534
* https://github.com/argoproj/argo-helm/pull/1477
* https://github.com/argoproj/argo-helm/pull/1579
* https://github.com/argoproj/argo-helm/pull/1532
* https://github.com/argoproj/argo-helm/pull/1532
=> feat(infra-apps): update argo-cd from 5.8 to 5.12

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD to 2.5.1 for SpookySSL patch and cleanup revisionHistoryLimit settings.
* CVE-2022-3602
* CVE-2022-3786
=> fix(infra-apps): Update argo-cd from 5.12 to 5.13

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Updates jaeger-operator all the way from v1.36.x to v1.38.x. Supports k8s v1.19 to v1.24.
=> feat(tracing-apps): Update jaeger-operator from 2.33.0 to 2.36.0

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Adds a bunch of features like Istio, Traefik, and InfluxDB support. Also fixes a bunch of issues across the board.
* https://github.com/argoproj/argo-rollouts/releases/tag/v1.3.0
* https://github.com/argoproj/argo-rollouts/releases/tag/v1.3.1
=> feat(argo-apps): Update Argo Rollouts from 2.20 to 2.21

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Update timed-backend image tag
=> chore(timed): update timed-backend image tag

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Fixes a bunch of Bugs:
* Because of a bug in RHACS 3.72.0, the Collector pods previously stopped responding and reach a segmentation fault after allocating a memory block for the protocol buffer heap under certain load conditions. The patch release 3.72.1 fixes this issue.
* In RHACS 3.72.0, scheduled vulnerability reports consistently reported zero vulnerabilities, even if there were images with CVEs within the clusters. The patch release 3.72.1 fixes this error and the reports show the correct CVEs.
* In RHACS 3.72.0, when you created a deployment bundle by using the roxctl CLI that explicitly disabled Pod Security Policies (PSP), the generated bundle still created manifests for the PSP. As a result, installing the deployment bundle failed when deploying on Kubernetes versions 1.25 or …
=> feat(security-apps): upgrade stackrox from 72.0 to 72.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Mark Thanos as DEPRECATED according to `docs/argocd-app-of-apps.md` 
n/a
<!--
Please open PRs as Draft while you make CI green and/or finalise
documentation. Your PR will be assigned to a CODEOWNER once you mark it
as "Ready for Review".
Once it is approved we will squash your changes onto the default branch
and our trusty bot account will release them to the repository.
--
=> chore(thanos): mark as DEPRECATED

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Update fluentd  to 5.5.*
- Update docker version
- Update analytics version
- Add support for image digest apart from tag
- Allow setting [hostNetwork and dnsPolicy](https://github.com/bitnami/charts/commit/9811472cdf40394eea54e54ed69c6453af7195fd)
- Use custom [probes if given](https://github.com/bitnami/charts/commit/689c3527cc6a39a19cadd377de3c4646f3dbb926)
n/a
=> chore(fluentd): Update to 5.5.*

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Deprecates `configs.gpgKeys` and `configs.gpgKeysAnnotations` replacing them with `configs.cm.gpg`.
* https://github.com/argoproj/argo-helm/pull/1609
=> feat(infra-apps): upgrade from argo-cd 5.13.* to 5.14.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bumps kured to [v1.11.0](https://github.com/kubereboot/kured/releases/tag/1.11.0), now supports K8s 1.23.x, 1.24.x and 1.25.x and has also finished the move to the kubereboot orga on github.
* https://github.com/kubereboot/charts/commit/c3656490312fb42ad79605cf3609ed0d55c9395e
* https://github.com/kubereboot/charts/pull/16
* https://github.com/kubereboot/charts/pull/17
* https://github.com/kubereboot/charts/pull/4
* Fixes #866
=> feat(infra-apps): upgrade kured from 4.0.1 to 4.1.0

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
* https://github.com/minio/minio/pull/16068
* https://github.com/minio/minio/pull/16064
* https://github.com/minio/minio/pull/15939
* https://github.com/minio/minio/pull/15660
* helm release v5.0.1 
* https://github.com/minio/minio/pull/15983
* https://github.com/minio/minio/pull/16055
* https://github.com/minio/minio/pull/15929
Fixes #877.
=> chore(storage-apps): update minio to 5.0.1

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Fixes https://github.com/adfinis/helm-charts/issues/873
- Add variable namespaceOverride to allow setting release namespace in values
- Change the grpc socket path from unix:///var/run/falco/falco.soc to unix:///run/falco/falco.sock.
- Bump Falco to 0.33.0
- Implicitly disable syscall source when not required
- Update values.yaml to reflect the new configuration options in Falco 0.33.0
- Mount /sys/module/falco when deployed using the kernel module
- Update rulesets for falco and plugins
[Change the grpc socket](https://github.com/falcosecurity/charts/blob/master/falco/CHANGELOG.md#v220) path from `unix:///var/run/falco/falco.soc` to `unix:///run/falco/falco.sock`. Please note that this change is potentially a breaking change if upgrading falco from a previous version and you have …
=> chore(security-apps): Update falco to v2.3.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
At first sight, nothing big. Mainly small changes.
- https://github.com/prometheus-community/helm-charts/pull/2692
- https://github.com/prometheus-community/helm-charts/pull/2691
- https://github.com/prometheus-community/helm-charts/pull/2693
- https://github.com/prometheus-community/helm-charts/pull/2687
- Fixes #862
=> feat(infra-apps): update kube-prometheus-stack to 42.0.0

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
-  Provide capability to use OpenTelemetry Collector metric sink
-  Provide capability to configure Azure Monitor integration configuration
-  Use Promitor Scraper agent v2.8.0 ([notes](https://github.com/tomkerkhove/promitor/releases/tag/Scraper-v2.8.0))
- Fixes #860
=> feat(azure-apps): update promitorScraper to 2.9.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrade kube-prometheus-stack to v42.1.0
- Prevent helm diff on monitoring.coreos.com/ServiceMonitor/monitoring/kube-prometheus-stack-kubelet [here](https://github.com/prometheus-community/helm-charts/commit/e438ead1685e9ea341ccb2fe4fb2fc34070cde81)
- Add missing upgrade to 42.x info [here](https://github.com/prometheus-community/helm-charts/commit/1daee72cce53f00c1b2dff3f81faeffc13512bff)
- Add local and global image registry support [here](https://github.com/prometheus-community/helm-charts/commit/f528fe820fa0f8d4eabada1b158854487e0563d8)
n/a
Signed-off-by: Iago Santos <iago.santos.pardo@adfinis.com>
=> chore(infra-apps): Update kube-prometheus-stack to v42.1.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/templates/oauth2-proxy.yaml, charts/security-apps/values.yaml
Added missing template for oauth2-proxy.
At the same time, I took the opportunity to bump the chart to 6.5.0 which include the following changes.
- https://github.com/oauth2-proxy/manifests/pull/95
- https://github.com/oauth2-proxy/manifests/pull/117
- https://github.com/oauth2-proxy/manifests/pull/118
- https://github.com/oauth2-proxy/manifests/pull/116
=> fix(security apps) : add template for oauth2-proxy

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> feat(timed): add cronjob for budget check

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates Secrets Store CSI Driver
fixes #876
Lots of changes from Release v1.2.0 to v1.2.4 nothing breaking.
Following Security Fixes:
* https://github.com/advisories/GHSA-q7pv-fjh6-6xq6
* https://github.com/advisories/GHSA-qjmp-vmxc-7p8r
* https://github.com/advisories/GHSA-jrpw-543v-8r62
* https://github.com/advisories/GHSA-jc36-42cf-vqwj
* https://github.com/advisories/GHSA-x3mh-jvjw-3xwx
* https://github.com/advisories/GHSA-ph2x-8239-7xc7
* https://github.com/advisories/GHSA-mfg4-w44m-wr4g
* https://github.com/advisories/GHSA-xj78-h3gx-cm6v
* https://github.com/advisories/GHSA-r48q-9g5r-8q2h
* https://github.com/advisories/GHSA-356p-pg27-x2cf
* https://github.com/advisories/GHSA-xjxr-x4h8-946x
* https://github.com/advisories/GHSA-p782-xgp4-8hr8
* …
=> chore(sec-apps/secrets-store-csi-driver): update to version 1.2.4

.github/pull_request_template.md
=> doc(github/pr): add info about example PR for artifacthub changes

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Implements updates to the chartmuseum helmchart.
resolves #872
=> feat(misc-apps): update chartmuesum-chart

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
updates falcoExporter to appVersion to 0.8.0.
Resolves #874
=> feat(security-apps): update falcoExporter to appVersion 0.8.0

CODEOWNERS, hack/chart-testing/ct-install.yaml
Cleanup last remnants of the huawei-csi-plugin chart
* ~~I updated the version in Chart.yaml~~
* ~~I updated the changelog according to the `artifacthub.io/changes` annotation in the Chart.yaml. See following [example](https://github.com/adfinis/helm-charts/pull/858/files).~~
* ~~I updated applicable README.md files using  `pre-commit run`~~
* ~~I documented any high-level concepts I'm introducing in `docs/`~~
* ~~CI is currently green and this is ready for review~~
* ~~I am ready to test changes after they are applied and released~~
=> chore(huawei-csi-plugin): remove last remnants of the chart

CODEOWNERS
getting rid of last trace of `charts/vault-csi-provider`
=> chore(vault-csi-provider): remove last remnants of the chart

charts/barman/Chart.yaml, charts/barman/README.md, charts/barman/templates/deployment.yaml, charts/barman/values.yaml
Added initContainers capability
For example waiting for postgresql instance(s)
=> feat: [barman] add init containers

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/values.yaml
add env var for redmine build project
=> feat(timed): add env var for redmine build project

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump Infra-apps to `0.136.0` to use Velero `1.9.4` with chart `2.32.4`.
Useful changes:
* https://github.com/vmware-tanzu/helm-charts/issues/365 
* https://github.com/vmware-tanzu/helm-charts/pull/424
Fixes #865.
=> chore(infra-apps): bump velero to 2.32.4

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/ci/default-values.yaml, charts/misc-apps/examples/grafana-agent-operator.yaml, charts/misc-apps/values.yaml
Added the grafana agent operator to `misc-apps`.
=> feat: add grafana agent operator

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
chart version bump to new minor version
=> chart version bump to new minor version

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/templates/grafana-agent-operator.yaml
Adds a template for the grafana-agent-operator
=> fix(grafana-agent-operator): Add template file

charts/customer-center/Chart.yaml, charts/customer-center/README.md
update customer center version to v3.2.5
=> chore(customer-center): update appVersion to v3.2.5

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* Updates Argo CD from 2.5.2 to 2.5.5 and fixes a bunch of stuff that is mainly UI related.
* Also updated bundle HA redis to match what argo recommends
Additionally there are also several fixes in the helm chart.
=> feat(infra-apps): update argo-cd from 5.14.1 to 5.16.10

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Contains a new version of kube-event-exporter from https://github.com/resmoio/kubernetes-event-exporter
=> feat(infra-apps): update kube-event-exporter chart from 2.1.1 to 2.1.4

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Fixes an issue where kube-downscaler didn't have enough rbac permissions to do keda related downscaling.
=> feat(misc-apps): update kube-downscaler chart from 0.6.0 to 0.7.0

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
update timed-frontend image tag for testing
=> chore(timed): update timed-frontend image tag to v3.0.0-rc1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD Chart from 5.16.10 to 5.16.13. Mostly getting rid of old apiVersions that are obsolete nowadays.
=> feat(infra-apps): upgrade argo-cd from 5.16.10 to 5.16.13

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
The initial [opsgenie](https://github.com/opsgenie/kubernetes-event-exporter) GitHub repository for kubernetes-event-exporter has been migrated to https://github.com/resmoio/kubernetes-event-exporter.
=> chore(k8s-event-exporter): update GH repo

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Update timed-backend image tag to v3.0.0-rc7
=> chore(timed): update timed-backend image tag to v3.0.0-rc7

.github/workflows/test.yaml
=> chore(ci): replace set-output with modern echo to $GITHUB_OUTPUT

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates Stackrox to the latest and greatest version. Most stuff in the release notes is just fixing small bug.
* https://github.com/stackrox/stackrox/releases/tag/3.73.0
* https://github.com/stackrox/stackrox/releases/tag/3.73.1
=> feat(security-apps): update Stackrox from 3.72.1 to 3.73.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Contains both the Argo CD 2.5.6 and 2.5.7 bump of which the former patches some low-hanging security patches and the latter fixes some regressions.
=> feat(infra-apps): update argo-cd from 5.15.13 to 5.17.4

.github/pull_request_template.md, README.md, docs/development.md, hack/config/update-readme/README.md.gotmpl
During my previous PR I've realized that the documentation for the `artifacthub.io` annotations could be improved.
=> Improve documentation regarding artifacthub.io annotations

charts/mopsos/Chart.lock, charts/mopsos/Chart.yaml, charts/mopsos/README.md, charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Mainly for PodSecurityPolicy deprecation support. The new version of the Grafana chart checks if ApiCapabilitites before creating PSPs.
=> fix(mopsos): update grafana from 6.25.* to 6.50.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
`v1.11.0` includes a drastic reduction in cert-manager's runtime memory usage, a slew of improvements to AKS integrations and various other tweaks, fixes and improvements.
See here for [Release Notes](https://cert-manager.io/docs/release-notes/release-notes-1.11/)
* https://github.com/cert-manager/cert-manager/releases/tag/v1.11.0
=> feat(infra-apps): update cert-manager from 1.10 to 1.11.0

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc5

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/ingress.yaml, charts/timed/values.yaml
Add the new ingressClassName field to the ingress as a replacement for the deprecated `kubernetes.io/ingress.class` annotation.
=> feat(timed): add ingress.ingressClassName value

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates the base image for security reasons and adds more read perms.
=> feat(infra-apps): update kube-event-exporter from 2.1.4 to 2.1.6

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates the kured version from 1.11.0 to 1.12.0 with the main features being updating a lot of dependencies and bringing it k8s support up to supporting 1.24.x, 1.25.x and 1.26.x K8s APIs.
* kured release: https://github.com/kubereboot/kured/releases/tag/1.12.0
=> feat(infra-apps): update kured from 4.1.0 to 4.2.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Main change is the update to Velero 1.10 which changes the repo backend from only supporting restic to also supporting kopia. If you are using restic then you'll most likely have to take care of the changes described in https://velero.io/docs/v1.10/upgrade-to-1.10/
* https://github.com/vmware-tanzu/velero/releases/tag/v1.10.0
* https://velero.io/docs/v1.10/upgrade-to-1.10/
=> feat(infra-apps): update velero chart from 2.32.4 to 3.1.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
prometheus-stack: update grafana chart from 6.48.2 to 6.50.2 to fix an issue where the sidecar failed to remove old resources
* https://github.com/prometheus-community/helm-charts/pull/2946
=> feat(infra-apps): update kube-prometheus-exported from 44.2.1 to 44.3.0

charts/backup-apps/Chart.yaml, charts/backup-apps/README.md, charts/backup-apps/values.yaml
Adds init containers to the barman deployment. This PR is mainly for housekeeping purposes since we don't currently use any initContainers.
* https://github.com/adfinis/helm-charts/pull/905
=> feat(backup-apps): update barman chart from 0.9.* to 0.10.0

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Contains the update to Argo Rollouts 1.4.0 which contains improvements for several downstream ingresses as well as a bunch of fixed things.
* https://github.com/argoproj/argo-rollouts/releases/tag/v1.4.0
=> feat(argo-apps): update argo-rollouts chart from 2.21.* to 2.22.2

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Update the chart to introduce a bunch of small features like being able to label the service.
=> feat(tracing-apps): update jaeger-operator chart from 2.37.0 to 2.39.0

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc6

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Contains a huge amount of changes to collector why collector itself slowly inches towards it's v1 release. Some of the changes might even be env in config file handling related :eyes:
=> feat(tracing-apps): update otel-collector from 0.39.3 to 0.47.3

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Update timed-backend image tag from v3.0.0-rc7 to v3.0.0-rc8
=> chore(timed): update backend image tag from v3.0.0-rc7 to v3.0.0-rc8

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Highlights:
* Introduce new CouchDB, Etcd & Loki scaler
* Introduce deprecation & breaking change policy (docs)
* Introduce off-the-shelf Grafana dashboard for application autoscaling
* Introduce improved operational metrics in Prometheus
* Introduce capability to cache metric values for a scaler during the polling interval (experimental feature)
=> feat(misc-apps): update keda from 2.8 to 2.9.3

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
update signalilo chart to 0.10.0 which adds [ingress support](https://github.com/appuio/charts/pull/451)
fixes #952
=> misc-apps/signalilo: update chart to 0.10.0

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
I used a broken version reference in #947 and this fixes that before i actually roll it out anywhere :grin:
=> fix(tracing-apps): use a properly published version of the otel-collector chart

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update backend image tag

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
update signalilo chart to 0.10.1 which fixes [ingress support](https://github.com/appuio/charts/pull/456)
fixes #956
=> feat(misc-apps/signalilo): update chart to 0.10.1

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/configmap-backend.yaml, charts/timed/values.yaml
add buildProject value for backend
=> feat(timed): add buildProject value for backend

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc7

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates Argo CD to include patches for CVE-2023-25163.
* https://github.com/argoproj/argo-cd/security/advisories/GHSA-mv6w-j4xc-qpfw
=> fix(infra-apps): Update Argo CD from 2.6.0 to 2.6.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update nginx-ingress to a version that supports K8s 1.26.
=> feat(infra-apps): Update nginx-ingress chart from 4.4.0 to 4.5.2

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
update backend image tag to v3.0.0-rc11
=> chore(timed): update backend image tag to v3.0.0-rc11

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/deployment-backend.yaml, charts/timed/templates/secret-backend.yaml, charts/timed/values.yaml
Adds the possibility to manage secrets externally with a new `backend.existingSecret` value. This makes it possible to leak much less info into our internal iac repo.
=> feat(timed): support unmanaged secret via backend.existingSecret value

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc9

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc10

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc11

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update due to CVE-2023-23947.
* https://github.com/advisories/GHSA-3jfq-742w-xg8j
=> feat(infra-apps): Update Argo CD from 2.6.1 to 2.6.2 (chart from 5.20.4 to 5.22.1)

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-backend image tag to v3.0.0-rc12

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update timed-frontend image tag to v3.0.0-rc.13

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update backend image tag to v3.0.0-rc13

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup to 1.6.11
* Updates `ubi8-minimal` base image to 8.7-1085
=> chore(openshift-etcd-backup): update to 1.6.11

.github/pull_request_template.md, README.md, hack/config/update-readme/README.md.gotmpl
Updates the docs to recommend/require an issue when adding new charts. The main idea being that we want to discuss adding new charts prior to any engineering work being put into them.
=> docs: hint at requiring an issue before adding new charts

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Update image tags:
Frontend: v3.0.0
Backend: v3.0.0
=> chore(timed): update backend and frontend image tags

charts/hedgedoc/Chart.yaml, charts/hedgedoc/README.md, charts/hedgedoc/templates/deployment.yaml
Makes persistent storage work as it wasn't even previously configured
=> fix(hedgedoc): Make persistent storage work

charts/hedgedoc/Chart.yaml, charts/hedgedoc/README.md, charts/hedgedoc/templates/pvc.yaml
Fixes the storageClass for hedgedoc
=> fix(hedgedoc): Fix storageClass

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Update images to:
Backend: v3.0.1-rc2
Frontend: v3.0.1
=> chore(timed): update frontend and backend image tags

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
update timed backend image tag
=> chore(timed): update timed backend image tag

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Update timed backend image to v3.0.2
=> chore(timed): update backend image tag to v3.0.2

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.0.2

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Fixes env var injection in the kube-downscaler chart. The fix is needed if you inject env variables in downscaler as the previous chart version was broken.
=> fix(misc-apps): update kube-downscaler from 0.7.0 to 0.7.1

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
This is the last StackRox release in the 3.x series before 4.x where StackRox will do stuff like switch to PostgreSQL as backing database (which will need some additional engineering on our side to get deployed).
=> feat(security-apps): update stackrox from 3.73.0 to 3.74.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Allow the new `kind: ConfigManagementPlugin` to be managed by the operator bits of Argo CD.
=> feat(infra-apps): update argo-cd chart from 5.25.0 to 5.26.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
=> fix(infra-apps): Update Argo CD from  2.6.4 to 2.6.5

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
Bump timed backend image to v3.0.3
=> chore(timed): bump timed backend to v3.0.3

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.1.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes some issues in the AppSets git files generator as well as making it possible to create project scoped clusters.
=> fix(infra-apps): update Argo CD from 2.6.5 to 2.6.6

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update dex Helm chart to 0.14.0, which in turns updates dex to 2.36.0
* https://github.com/dexidp/dex/releases/tag/v2.36.0
=> chore(security-apps): update dex chart to 0.14.0

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.1.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update to include CVE-2022-41354 fix.
=> fix(infra-apps): update Argo CD from 2.6.6 to 2.6.7

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
=> fix(infra-apps): update argo-cd chart from 5.27.2 to 5.27.3

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Rollouts: support setting pod annotations separately on controller and dashboard
=> feat(argo-apps): update argo rollouts chart from 2.22.3 to 2.23.0

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Gets rid of a bunch of now stable feature gates and some refactoring.
=> feat(tracing-apps): update opentelemetry-collector from 0.72.0 to 0.74.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
update Neuvector from 5.1.0 to 5.1.2
* Support cri-o 1.26+ and OpenShift 4.11+
* Enable auto scan in configMap
* improve controller and enforcer CPU and memory consumption
* fix various ui issues
* Make gravatar optional
* Hostname based egress network policy
* Display cluster namespace resource in UI
=> feat(security-apps): update neuvector from 5.1.0 to 5.1.2

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Updates Signalilo and makes service account name configurable.
=> feat(misc-apps): update signalilo from 0.12.0 to 0.13.0

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Here are some highlights from the KEDA release notes:
* New ArangoDB Scaler
* New (experimental) GitHub Actions Scaler
* New admission webhook for validating ScaledObjects
* Security enhancements thanks to certificate integrations
* Support for custom CAs
=> feat(misc-apps): update keda from 2.9.3 to 2.10.0

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup to the most recent release
=> chore(openshift-etcd-backup): update to 1.6.13

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.1.2

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
bump timed-backend image to v3.0.4
=> chore(timed): bump timed-backend image

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.1.3

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.1.5

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* fix: Change default value for global.tolerations, from object to array
* feat: Add support for custom Deployment strategy
* fix: Entrypoint can be configured now
* fix: Disable hostNetwork field when is set to false"
=> feat(infra-apps): Update argo-cd chart from 5.27.3 to 5.28.1

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Argo Rollouts adds more features in the chart, but nothing more.
=> feat(argo-apps): udpate Argo Rollouts from 2.23.0 to 2.26.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Contains some fixes and updates the underlying golang and base image to addresse some CVEs.
=> fix(infra-apps): update cert-manager from 1.11.0 to 1.11.1

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/ci/default-values.yaml, charts/misc-apps/examples/reloader.yaml, charts/misc-apps/templates/reloader.yaml, charts/misc-apps/values.yaml
Reloader helps us perform automatically a Rolling upgrade on the relevant DeploymentConfig, Deployment, Daemonset, Statefulset and Rollout if a ConfigMap or Secret used by it is changed. 
This would help us do rolling upgrades for some apps which need to be restarted upon secret change (Example Certificate is managed by cert-manager etc.)
n/a
=> feat(misc-apps/reloader): new chart addition

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Some fixes pertaining to namespace handling in namespace scoped resources and more configurability for dex.
=> feat(infra-apps): update argo-cd chart from 5.28.1 to 5.29.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates some exporters as well as the bundled grafana.
=> feat(infra-apps): update kube-prometheus-stack chart from 45.9.1 to 45.23.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update chart from 0.22.* to 0.24.1.
=> feat(security-apps): Update vault chart from 0.22.* to 0.24.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
:partying_face: :dancing_men: :dancing_women: :tada:
=> feat(infra-apps): update Argo CD from 2.6.7 to 2.7.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates chart to actually include CVE-2023-0464 updates.
=> feat(infra-apps): Update Argo CD from 2.7.0 to 2.7.1

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
=> feat(misc-apps): update argocd-apps chart from 0.0.9 to 1.0.0

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Adds missing permissions for argo rollouts dashboard cluster role.
=> fix(argo-apps): update argo-rollouts chart from 2.26.0 to 2.26.1

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Update promitor scraper to v2.10 & resource discovery to v0.9.0.
=> feat(azure-apps): update promitor scraper to v2.10 & resource discovery to v0.9.0

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/ci/default-values.yaml, charts/misc-apps/examples/opencost.yaml, charts/misc-apps/templates/opencost.yaml, charts/misc-apps/values.yaml
Initial OpenCost chart integration so we can rollout the release that welcomes MSFT to the community and adds support for the new [Azure Consumption Price Sheet API](https://www.opencost.io/docs/azure-prices).
=> feat(misc-apps): add OpenCost chart

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Updates the included bats image for CVE-2019-14697
=> fix(logging-apps): update loki-stack chart from 2.9.9 to 2.9.10

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Updates some deps and chart now allows configuring container security context for jaeger operator. Nothing huge from our pov.
=> feat(tracing-apps): update jaeger-operator from 1.42.0 to 1.43.0

.github/workflows/test.yaml
Make test wf only run on PR to not waste gh aceions minutes as suggested by @gianklug
=> ci(test):. Only run on PR 

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Given that this is the only exposed flag wrt Ingress, there needs to be a working way to at least not deploy it.
=> fix(keycloak-operator): allow disabling ingress

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump Velero to helm chart 4.0.2
The Velero CSI plugin now determines whether to restore Volume's data from snapshots on the restore's restorePVs setting. Before v1.11, the CSI plugin doesn't check the restorePVs parameter setting.
The `configuration.provider` is deprecated in the Helm chart values.
* Add PodMonitor for monitoring node-agents.
* Bump velero version v1.11.0
* Add support for multiple backupstoragelocations and volumesnapshotlocations
=> feat(infra-apps): bump velero to latest 4.0.2

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup to 1.6.14 which updates the base image to 8.8-860
=> Update openshift-etcd-backup to 1.6.14

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): bump backend image tag

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes several issues in how appsets and their generators interact and instroduces singed artefacts as part of SLSA level 3.
=> feat(infra-apps): update Argo CD from 3.7.1 to 3.7.3

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
activate updateProjectExpenditureFirst job
activate updateProjectExpenditureSecond job
=> feat(timed): activate update_project_expenditure job

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
bump backend image tag to v3.0.7
=> chore(timed): bump backend image tag to v3.0.7

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Patches some CVEs in golang that can have a security impact on Argo CD builds (SLSA Lvl 3 :call_me_hand:)
=> feat(infra-apps): Update argo-cd from 3.7.3 to 3.7.5

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/ci/default-values.yaml, charts/security-apps/examples/kyverno.yaml, charts/security-apps/templates/kyverno-policies.yaml, charts/security-apps/templates/kyverno.yaml, charts/security-apps/values.yaml
Add the [Kyverno](https://kyverno.io) Kubernetes policy management engine.
=> feat(security-apps): add kyverno and kyverno-policies deployments

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Contains a couple dependency bumps and changes to ACME external webhook library and fixes `cmctl check api`.
=> feat(infra-apps): Update cert-manager from 1.12.0 to 1.12.2

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update Dex chart to 0.14.2
* Support for adding annotations to deployment, pod and servicemonitor added: https://github.com/dexidp/helm-charts/pull/105
=> chore(security-apps): update Dex chart to 0.14.2

charts/hedgedoc/Chart.yaml, charts/hedgedoc/README.md, charts/hedgedoc/templates/deployment.yaml
Updated the hedgedoc chart to the latest image version. 
See https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.8 for the full changelog.
Also I switched to the new `_health` endpoint for the health probe.
=> feat(hedgedoc): Update to 1.9.8

charts/customer-center/Chart.yaml, charts/customer-center/README.md
[Update customer-center to v3.2.6](https://github.com/adfinis/customer-center/releases/tag/v3.2.6)
=> chore(customer-center): update to v3.2.6

CODEOWNERS
Update to allow devs to review charts to the customer-center chart on their own.
=> chore: update CODEOWNERS for customer-center

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bundles a bunch of upstream fixes in ApplicationSet generators as well as a bump to the bundled Dex installation.
Esp. the Dex update patches several low-level go dependencies and should be considered a security update.
=> feat(infra-apps): update Argo CD from 2.7.4 to 2.7.7

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Mostly housekeeping + some improved Istio compat and signed helm charts
=> feat(argo-apps): Update argo-rollouts from 2.26.1 to 2.31.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/examples/stackrox.yaml, charts/security-apps/values.yaml
The main change we're after is that StackRox now supports using an external PostgreSQL database instead of the previous  embedded one. This should also mark the first release where our Argo CD is modern enough to work properly with the helm hook based things the StackRox charts are doing.
=> feat(security-apps): update StackRox from 3.x to 4.x

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/templates/thanos.yaml, docs/argocd-app-of-apps.md
Make Thanos templating Fail
According to `docs/argocd-app-of-apps.md`:
> We will still keep the app available in the app-of-apps chart for at least 6 months so users can take time to replace it. During this time the component does not get regular updates unless there are egregious security issues that need addressing.
> Once we are ready to fully remove it we replace the components template with a fail template:
The [PR 854](https://github.com/adfinis/helm-charts/pull/854) keeping the app with just a DEPRECATION notice is from 8 months ago. So we make it fail now and wait for a year.
=> chore(thanos): make fail

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bundles a bunch of upstream bugfixes into this one update, most things that aren't on our critical path as well as some ui related fixes. The bundled Dex is also seeing an update and we should take care of those if anyof them are still running.
* replaces #1074
=> feat(infra-apps): Update Argo CD from 2.7.6 to 2.7.10

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Includes changes/fix to render the existingKey part properly in the "db" part.
=> fix(keycloak-operator): db secret indentation

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Contains some bc compat changes that shouldn't have any impact and fixes some datadog integration bits that doesn't affect us.
=> feat(argo-apps): Update from from 1.5.0 to 1.5.1

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Makes services created in icinga tempalteable and updates a bunch of signalilo's dependencies.
=> feat(misc-apps): update signalilo from 0.13.0 to 0.14.0

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
https://github.com/adfinis/timed-frontend/releases/tag/v3.2.2
=> chore(timed): update frontend image tag to v3.2.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
🥳
You want to run CronJobs once via a UI?  Argo CD has you covered!
You want to use docker hub as private OCI registry but are running into bugs? Argo CD has you covered!
You want a ton of new features (and bugfixes) in the ApplicationSet space? Argo CD has you covered!
A great summary is on the latest RC candidate's blog post: https://blog.argoproj.io/argo-cd-v2-8-release-candidate-be4443d974f
=> feat(infra-apps): Update Argo CD from 2.7.8 to 2.8.0 🥳

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Round 2 of rolling out Argo CD 2.8.0 :pleading_face:
=> fix(infra-apps): Update Argo CD from 2.7.11 to 2.8.0

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup to the most current image
=> chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.6.15

charts/hedgedoc/Chart.yaml, charts/hedgedoc/README.md
Updated the Hedgedoc Chart to **1.9.9**.
This mainly includes a security fix for [CVE-2023-38487](https://github.com/hedgedoc/hedgedoc/security/advisories/GHSA-7494-7hcf-vxpg). Full changelog [here](https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.9).
=> chore: Bump hedgedoc to 1.9.9

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/examples/opentelemetryCollector.yaml, charts/tracing-apps/values.yaml
Quite a few otel-collector version bumps. Makes configuring otel-collector easier because the templates now use `tpl` liberally. There is one change that we want to tack closely (i don't think it impacts us but am not 100% sure):
> The kubernetesAttributes preset now respects order of processors in logs, metrics and traces pipelines. This implicitly might break your pipelines if you relied on having the k8sAttributes processor rendered as the first processor but also explicitly listed it in the signal's pipeline somewhere else.
=> feat(tracing-apps): Update otel-collector from 0.75.0 to 0.82.0

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Update MinIO to the latest version, last bump is from Nov 2022 :/
=> feat(storage-apps): Update MinIO from RELEASE.2022-11-11T03-44-20Z to RELEASE.2023-04-13T03-08-07Z

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updated kube-prometheus-stack to newest version.
=> feat(infra-apps): update kube-prometheus-stack chart from 45.23.0 to 48.3.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes a bunch of low-hanging fruit as well as CVE-2023-40025.
=> feat(infra-apps): Update Argo CD from 2.8.0 to 2.8.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* fix an issue with comparing two IP addressees that affects ipv6
* update go to fix a security issue in crypto/tls (aka CVE-2023-29409)
=> feat(infra-apps): Update cert-manager from 1.12.3 to 1.12.4

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update for CVE-2023-40029 & CVE-2023-40584.
=> feat(infra-apps): Update Argo CD from 2.8.2 to 2.8.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
cert-manager 1.13 brings support for DNS over HTTPS, support for loading options from a versioned
config file for the cert-manager controller, and more. This release also includes the promotion of
the StableCertificateRequestName and SecretsFilteredCaching feature gates to Beta.
=> feat(infra-apps): update cert-manager from 1.12.4 to 1.13.0

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Argo Rollouts 1.6.0 brings us a refreshed UI and bumps a ton of dependencies.
=> feat(argo-apps): Update Argo Rollouts from 1.5.1 to 1.6.0

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Contains a bunch of bugfixes.
Full [CHANGELOG](https://github.com/minio/minio/compare/RELEASE.2023-04-13T03-08-07Z...RELEASE.2023-07-07T07-13-57Z)
=> feat(storage-apps): update MinIO from 5.0.8 to 5.0.13

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Makes the generated `kind: Keycloak` work even when using an `imagePullSecret'.
=> fix(keycloak-operator): proper indent for imagePullSecret in operand

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Improves templating of AppProjects and adds syncOptions for Applications. 
* fixes #1121
=> feat(misc-apps): Update argocd-apps chart from 1.0.0 to 1.4.1

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Changed Downscaler version from 0.7.1 to 0.7.3
Fixes #1119
=> chore(downscaler): Updated downscaler from 0.7.1 to 0.7.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Most importantly some security fixes for CVE-2022-48174 in the bundled redis instance as well as some small features elsewhere.
* fixes #1107
=> fix(infra-apps): Udpate Argo CD chart from 5.46.3 to 5.46.7

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Updates Promitor Resource Discovery to version 0.11.0.
Fixes #1106 
* Patch for CVE-2023-28260 (High | Base image)
* https://github.com/tomkerkhove/promitor/pull/2329
* Patch for CVE-2023-29331
*  https://github.com/tomkerkhove/promitor/pull/2368
* Patch for CVE-2023-33170 (High - CVE Report)
* Patch for CVE-2023-36799 (Medium - CVE Report)
* Patch for CVE-2023-36054 (Medium - CVE Report)
* Patch for CVE-2023-3817 (Medium - CVE Report)
* Patch for CVE-2023-2650 (Medium - CVE Report)
=> chore(promitorResourceDiscovery): update from 0.9.0 to 0.11.0

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Updates promitor scraper to version 2.11.0 (Chart Version 2.12.0)
Fixes #1105
=> chore(promitorScraper): update to version 2.12.0

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Update azureKvCsiProvider from 1.3.* to 1.4.1
- Update to [v1.4.0](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.4.0)
- Update to [v1.4.1](https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.4.1)
=> feat(azure-apps): Update azureKvCsiProvider from 1.3.* to 1.4.1 (#1104)

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Update KEDA from 2.10.1 to 2.12.0. There are some new features including new Scalers.
Fixes https://github.com/adfinis/helm-charts/issues/1122
=> feat(misc-apps): update KEDA chart from 2.10.1 to 2.12.0

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Update chartmuseum from 3.9.2 to 3.10.1
https://github.com/adfinis/helm-charts/issues/1120
=> feat(misc-apps): Update chartmuseum from 3.9.2 to 3.10.1

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Update fluentBit to newest version.
fixes #1118
=> chore(logging-apps): update fluentBit to 0.39.0

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Bumping Keycloak version to introduce patch-fixes.
Full release notes are not yet available as of writing: https://www.keycloak.org/docs/latest/release_notes/
Specifically this shall be fixed: https://github.com/keycloak/keycloak/issues/23327
=> chore(keycloak-operator): bump keycloak version to 22.0.5

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Changes:
Update vault helm-chart to 0.26.1 most important changes:
* Default vault version updated to 1.15.1
* Default vault-k8s version updated to 1.3.1
* Default vault-csi-provider version updated to 1.4.1
=> feat(security-apps): Update Vault Chart from 0.24.1 to 0.26.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Contains a bunch of fixes for multisource ApplicationSets and patches CVE-2022-48174 in the bundled redis containers.
=> feat(infra-apps): Update Argo CD from 2.8.4 to 2.8.5

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
It's Argo CD 2.9 and it might fix Helm icons :)
=> feat(infra-apps): Update Argo CD from 2.8.5 to 2.9.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
=> feat(infra-apps): Update Argo CD from 2.9.0 to 2.9.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes [CVE-2023-44487](https://github.com/advisories/GHSA-qppj-fm5r-hxr3) and [CVE-2023-39325](https://github.com/advisories/GHSA-4374-p667-p6c8) as well some other small fixes.
=> fix(infra-apps): Update cert-manager from 1.13.1 to 1.13.2

charts/kubernetes-etcd-backup/Chart.yaml, charts/kubernetes-etcd-backup/README.md, charts/kubernetes-etcd-backup/values.yaml
Use latest version `1.0.4`. For more information check the [changelog](https://github.com/adfinis/kubernetes-etcd-backup/releases/tag/v1.0.4).
None.
=> chore(etcd-backup): bump to latest release 1.0.4

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Bump Keycloak to 23.0.2.
Fixes: https://github.com/keycloak/keycloak/issues/25176
=> fix(keycloak-operator): Update keycloak from 23.0.1 to 23.0.2

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
update openshift-etcd-backup image to v1.7.1
=> chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.7.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes some cache misses and other small stuff, upstream has also updated quite a bit of the charts docs.
=> fix(infra-apps): Update Argo CD from 2.9.1 to 2.9.3

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md, charts/openshift-etcd-backup/templates/cronjob.yaml, charts/openshift-etcd-backup/values.yaml
To be able to use Velero PV backup with the node-agent we have to get annotations in the pod template.
https://velero.io/docs/v1.12/file-system-backup/#using-opt-in-pod-volume-backup
=> feat(cronjob): add annotations support in pod template

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bump Velero helm chart to 5.2.0 and Velero to 1.12.2
=> chore(infra-apps): bump Velero to helm chart 5.2.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Fixes CVE-2024-22424 and merges all ServiceAccounts and supports [argocd-extension-installer](https://github.com/argoproj-labs/argocd-extension-installer).
* fixes CVE-2024-22424
=> feat(infra-apps): Update Argo CD from 2.9.3 to 2.9.4

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Lots of small fixes and whatnot.
=> feat(argo-apps): Update Argo Rollouts from 1.6.0 to 1.6.4

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Update to OpenCost 1.108.0 (the first release with Cloud Cost for monitoring resources outside of K8s).
=> feat(misc-apps): Update OpenCost from 1.105.2 to 1.108.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update for security and features.
* Fixes GHSA-9763-4f94-gfch
* Fixes GHSA-2c7c-3mj9-8fqh 
* Fixes CVE-2023-48795 (Terrapin)
=> feat(security-apps): Update Kyverno from v1.10.0 to v1.11.4

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Support CronJobs in K8s >=1.25.
=> feat(misc-apps): Update downscaler chart from 0.7.3 to 0.7.4

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Bump to 1.49.x version of operator. Updates a ton of dependencies and introduces several new features.
=> feat(tracing-apps): Update jaeger-operator chart from 2.43.0 to 2.50.1

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update frontend image tag to v3.3.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
2.9.5 mostly fixes some GUI issues.
=> fix(infra-apps): Update Argo CD from 2.9.4 to 2.9.5

charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/templates/servicemonitor.yaml, charts/vault-monitoring/values.yaml
When using an unauthenticated access service for monitoring we don't need the bearerTokenFile.
=> feat(vault-monitoring): make bearerTokenFile optional

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
It's the "i herd you like server-side diffing" release :)
* https://github.com/argoproj/argo-cd/releases/tag/v2.10.0
=> feat(infra-apps): Update Argo CD from 2.9.5 to 2.10.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Fixes CVE-2023-48795 (aka Terrapin)
=> fix(security-apps): Update csi-secrets-driver from 1.4.0 to 1.4.1

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Update to latest version or operator+operand. Contains several small fixes.
=> fix(keycloak-operator): Update from 23.0.2 to 23.0.4

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Render values properly in charts README.md
=> chore(azure-apps): fix azureWorkloadIdentityWebhook values in README.md

charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/examples/values.yaml, charts/vault-monitoring/templates/configmap.yaml, charts/vault-monitoring/templates/servicemonitor.yaml, charts/vault-monitoring/values.yaml
Added a toggle for authentication
=> add optional authentication

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
updating timed frontend to version 3.4.0
=> chore(timed): update frontend image tag to v3.4.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update stackrox-central and stackrox-secured-cluster-services from 4.2.2 to 4.3.4
=> feat(security-apps): Update stackrox from 4.2.2 to 4.3.4

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update cert-manager to 1.14.3. Contains several security relevant changes.
=> feat(infra-apps): Update cert-manager from 1.13.2 to 1.14.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
rbac-manager mostly started testing their code against newer versions of K8s, also they rebased their base image onto a more modern one making this a security patch just as well.
=> feat(infra-apps): Update rbac-manager from 1.15.1 to 1.19.0

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md, charts/openshift-etcd-backup/templates/secret.yaml
* add missing secret item for `backup.sh` script to work
* remove whitespace in secret
* bump application to 1.8.1 due to [change](https://github.com/adfinis/openshift-etcd-backup/commit/048f27a9580da0ba9976274344cc809fe32297d0)
=> chore(etcd-backup): bump to 1.8.1

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md, charts/openshift-etcd-backup/templates/configmap.yaml, charts/openshift-etcd-backup/templates/secret.yaml
Fix unbound variable issue for `OCP_BACKUP_S3` due to `set -u` used in `backup.sh`.
=> fix(openshift-etcd-backup): fix issue while using either S3 or NFS

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update the openshift-etcd-backup image to v1.8.5
=> chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.8.5

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md, charts/openshift-etcd-backup/templates/ca-inject.yaml, charts/openshift-etcd-backup/templates/cronjob.yaml, charts/openshift-etcd-backup/values.yaml
In case of using a custom CA within OpenShift, we want to be able to use it with a S3 endpoint.
* https://docs.openshift.com/container-platform/4.14/security/certificates/updating-ca-bundle.html
* https://docs.openshift.com/container-platform/4.14/networking/configuring-a-custom-pki.html#certificate-injection-using-operators_configuring-a-custom-pki
=> feat(openshift-etcd-backup): add OpenShift CA inject support

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/templates/job-dbmigrate.yaml, charts/timed/values.yaml
=> chore(timed): update backend to v3.0.10

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update backend to v3.0.11

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update backend to v3.0.12

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
=> chore(timed): update backend to v3.0.16

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Lotsa updates incl. some security patches.
=> fix(infra-apps): Update Argo CD from 2.10.4 to 2.10.9

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
update openshift-etcd-backup to 1.8.6
=> chore(openshift-etcd-backup): update openshift-etcd-backup to 1.8.6

charts/timed/Chart.yaml, charts/timed/README.md, charts/timed/values.yaml
frontend :chart_with_upwards_trend:
=> chore(timed): update frontend to v3.6.0

README.md, charts/timed/Chart.yaml, charts/timed/README.md
Chart was migrated to OCI registry and we can mark this as such here.
=> chore(timed): mark chart as deprecated

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
This version updates NGINX to 1.25.
=> feat(infra-apps): Update nginx-ingress chart from 4.9.0 to 4.10.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
We can fully replace it with otel-collector nowadays and it is unmaintained so this marks it as deprecated as per out [policy](https://github.com/adfinis/helm-charts/blob/main/docs/argocd-app-of-apps.md#component-deprecation).
=> feat(infra-apps): Deprecate kube-event-exporter

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
It's about time to update KPS :roll_eyes:
=> feat(infra-apps): Update kube-prometheus-stack from 54.2.2 to 58.6.0

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Contains a breaking in how apps are specified. They are now a map and no longer a list.
Before:
```yaml
applications:
- name: example-app
project: default
```
After:
```yaml
applications:
example-app:
project: default
```
=> feat(misc-apps): Update argocd-apps from 1.4.1 to 2.0.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Enables auth for Redis in default installations.
=> feat(infra-apps): Update Argo CD from 2.11.0 to 2.11.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Some patches and regular feature and maintenance work on Velero.
=> feat(infra-apps): Update Velero from 1.12.2 to 1.13.2

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
[Loki 3.0](https://grafana.com/docs/loki/latest/release-notes/v3-0/) is nigh and supports native CiliumNetworkPolicies, native OTLP, as well as fixing several bugs.
=> feat(logging-apps): Update Loki from 2.9.3 to 3.0

README.md, charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Keycloak 24.x  now supports HA deployments!
=> feat(keycloak-operator): Update keycloak-operator and keycloak from 23.0.3 to 24.0.4

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Contains some smallish fixes that can help concurrent deployments not get stuck in race conditions.
* fixes #1236
=> feat(argo-apps): Update argo-rollouts from 1.6.4 to 1.6.6

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Update metallb to 0.14.5
No bug fixes relevant for our environment and no breaking changes in the [changelog of 0.14.5](https://metallb.universe.tf/release-notes/#version-0-14-5)
* fixes #1254
=> chore(misc-apps): update metallb to 0.14.5

charts/storage-apps/Chart.yaml, charts/storage-apps/README.md, charts/storage-apps/values.yaml
Please see latest version release [notes](https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v1.14.0).
=> chore(storage-apps): bump csi-driver-smb from 1.9.* to 1.14.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates us to the latest and greatest Argo CD release.
BREAKING CHANGE: cluster credentials are now represented as a map in values.
* fixes #1239
=> feat(infra-apps): Update Argo CD from 2.11.1 to 2.11.2

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
update openshift-etcd-backup image to v1.8.8
=> chore(openshift-etcd-backup): update image to v1.8.8

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates KPS to version 60.0.2 from 58.x
The main breaking change here is Grafana v11 which removes legacy alerting once and for all. will need to test this on the test instance and make sure all values work
https://grafana.com/docs/grafana/latest/breaking-changes/breaking-changes-v11-0/
=> chore(kps): update to 60.0.2

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup image to v1.8.9
=> chore(openshift-etcd-backup): update image to v1.8.9

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
This PR updates the chart versions in tracing-apps.
=> chore(tracing-apps): update chart versions

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
This PR updates the chart versions in security-apps.
=> chore(security-apps): update chart versions

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Fixes the following error:
> Error: YAML parse error on promtail/templates/service-metrics.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key
=> fix(logging-apps): Update promtail chart from 6.16.0 to 6.16.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Some moderate security bumps and a bugfix in [cert-manager 1.15.1](https://github.com/cert-manager/cert-manager/releases/tag/v1.15.1).
=> fix(infra-apps): Update cert-manager from 1.15.0 to 1.15.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
[Argo CD 2.11.4](https://github.com/argoproj/argo-cd/releases/tag/v2.11.4).
=> feat(infra-apps): Update Argo CD from 2.11.3 to 2.11.4

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup image to 1.8.10
=> chore(openshift-etcd-backup): update image to v1.8.10

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
See [the RC blog](https://blog.argoproj.io/argo-cd-v2-12-release-candidate-90793368bfb5) for a high level summary of 2.12.0.
=> feat(infra-apps): Update Argo CD from 2.11.4 to 2.12.0

charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/values.yaml
Add one more rule for vault monitoring
=> feat(vault): Add new alert for vault

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Bumps IngressNginx Chart to 4.11.2 and ingressNginx Appversion to 1.11.2
Fixes [CVE-2024-7646: Ingress-nginx Annotation Validation Bypass](https://github.com/kubernetes/kubernetes/issues/126744)
[Full changelog](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.11.2)
=> chore(ingressNginx): bump to 4.11.2

charts/vault-monitoring/Chart.yaml, charts/vault-monitoring/README.md, charts/vault-monitoring/values.yaml
=> fix(vault): prometheus rules

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Fix vault alerts and bump security-apps
=> fix(vault-monitoring): Remove labels security-apps

README.md, charts/caasperli/Chart.yaml, charts/caasperli/README.md
deprecates the chart with a last release.
=> chore(caasperli): publish deprecation release

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup image to v1.8.11
=> chore(openshift-etcd-backup): update image to v1.8.11

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap, charts/keycloak-operator/values.yaml
Enable operator Deployment by default.
=> fix(keycloak-operator): Deploy operator by default

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Update helm charts:
- loki from 6.6.3 to 6.12.0
- promtail from 6.16.3 to 6.16.5
=> chore(logging-apps): Update Loki from 3.0.0 to 3.1.1

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Upgrade Keycloak to [v25.0.5](https://github.com/keycloak/keycloak/releases/tag/25.0.5).
=> chore(keycloak): update to v25.0.5

README.md, charts/hedgedoc/Chart.yaml, charts/hedgedoc/README.md
Bump hedgedoc version to 1.10.0
None
=> chore(hedgedoc): Bump hedgedoc version to 1.10.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
The main change is that RBAC Manager artefacts are now signed with cosign.
=> feat(infra-apps): Update RBAC Manager from 1.8.0 to 1.9.0

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
=> chore: update keycloak to v25.0.6

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD from 2.12.0 to 2.12.4, contains several low prio security fixes like the ReDOS from CVE-2024-45296.
=> fix(infra-apps): Update Argo CD from 2.12.0 to 2.12.4

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup to v1.8.12
=> chore(openshift-etcd-backup): update image to v1.8.12

README.md, charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Update the operator and operand to Keycloak 26.0.0: https://www.keycloak.org/2024/10/keycloak-2600-released
=> feat(keycloak-operator): Update to 26.0.0

docs/argocd-app-of-apps.md
=> Fix typo in argocd-app-of-apps.md

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
=> feat(infra-apps): Upgrade Argo CD from 2.12.4 to 2.13.0

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
Update openshift-etcd-backup to v1.8.13
=> chore(openshift-etcd-backup): update image to v1.8.13

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD to [2.13.2](https://github.com/argoproj/argo-cd/releases/tag/v2.13.1).
=> feat(infra-apps): Update Argo CD from 2.13.0 to 2.13.1

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
There were several recent Keycloak updates that i'm bundling into this PR, some of them fix issues that might affect us.
=> fix(keycloak-operator): Update from 26.0.1 to 26.0.6

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
* Updates Stackrox central-services and secured-cluster-services from 4.4.3 to 4.5.5
=> chore: update stackrox from 4.4.3 to 4.5.5

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrading oauth2-proxy to 7.8.2 as part of our regular maintenance.
=> chore: upgrade oauth2-proxy to 7.8.2

_config.yml
This PR removes the obsolete twitter link.
Rel: https://github.com/adfinis/jekyll-theme-adfinis-ng/pull/1
=> fix: remove twitter link

README.md, adfinis-charts-repo.yaml, hack/ci/github/steps/update-page.sh, hack/config/update-readme/README.md.gotmpl
Adds a yaml resource for loading these charts into an openshift console.
=> feat: Add a HelmChartRepository for use with OpenShift

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/ci/default-values.yaml, charts/infra-apps/templates/kubernetes-event-exporter.yaml
We marked kube-event-exporter as deprecated >6 months ago, next we fail if users still need it.
=> chore(infra-apps): Add fail for kube-event-exporter deprecation

charts/azure-apps/Chart.yaml, charts/azure-apps/README.md, charts/azure-apps/values.yaml
Upgrades Promitor:
- Promitor Scraper to Chart version 2.14.0 (Application version 2.13.0)
- Promitor Resource Discovery to 0.13.0 (Application version 0.13.0)
=> feat(azure-apps): upgrade promitor scraper to 2.14.0 and rd to 0.13.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Updates Stackrox central-services and secured-cluster-services from 4.5.5 to 4.6.2
=> chore(security-apps): update stackrox from 4.5.5 to 4.6.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update nginx-ingress component due to CVE-2025-1974
* https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974/
* CVE-2025-1974
* CVE-2025-1098
* CVE-2025-1097
* CVE-2025-24514
=> feat(infra-apps): Update nginx-ingress from 1.11.1 to 1.12.1

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Bump OpenCollector from v0.93.3 to v0.119.0
n/a
=> chore(tracing-apps): Bump opencollector from 0.93 to 0.119

charts/hedgedoc/Chart.yaml, charts/hedgedoc/README.md
Bumped hedgedoc container image version from 1.10.0 to 1.10.2
n/a
=> chore(hedgdoc): Bump hedgdoc from 1.10.0 to 1.10.2

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update Kyverno to it's latest and greatest version, which is also a version that supports specifying a pull secret.
=> feat(security-apps): update Kyverno from 1.12.4 to 1.13.4

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
The security-apps chart tried to use an unreleased kyverno chart, this fixes that.
=> fix(security-apps): downgrade kyverno chart to 3.3.7

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
[Argo CD 2.14](https://blog.argoproj.io/argo-cd-v2-14-release-candidate-57a664791e2a) bings several preformance and other improvements. It also contains some security fixes in it's dependencies.
=> feat(infra-apps): update Argo CD from 2.13.1 to 2.14.8

charts/openshift-etcd-backup/Chart.yaml, charts/openshift-etcd-backup/README.md
* stop leaking secrets to stdout
* make s3 policy setup optional
=> fix: upgrade openshift-etcd-backup image to v1.9.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
* A helpful compliance change to RSA signatures on certificates
* An easier way to specify passwords for PKCS#12 and JKS keystores
* A few feature flag promotions (and a deprecation)
* Dependency bumps and other smaller improvements
* Fix issuing of certificates via DNS01 challenges on Cloudflare
=> feat(infra-apps): update cert-manager from 1.16.2 to 1.17.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates Kube-Prometheus-Stack from Version 65.5.0 to 67.11.0
**ATTENTION** this will update Prometheus to version 3.1 (from 2.55)
please read carefully through the migration guide of Prometheus:
https://prometheus.io/docs/prometheus/3.0/migration/
- https://github.com/prometheus-community/helm-charts/pull/4950
- https://github.com/prometheus-community/helm-charts/pull/4646
- https://github.com/prometheus-community/helm-charts/pull/4971
- https://github.com/prometheus-community/helm-charts/pull/4973
- https://github.com/prometheus-community/helm-charts/pull/4974
- https://github.com/prometheus-community/helm-charts/pull/4979
- https://github.com/prometheus-community/helm-charts/pull/4976
- https://github.com/prometheus-community/helm-charts/pull/4998
- …
=> chore(Kube-Prometheus-Stack): update to 67.11.0 - First release with Prometheus v3

README.md, charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Update Keycloak from 26.0.7 to 26.2.1 to get a bunch of new features and patches.
=> feat(keycloak-operator): Update Keycloak from 26.0.7 to 26.2.1

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Security updates for Keycloak: https://www.keycloak.org/2025/04/keycloak-2622-released
* [CVE-2025-3501](https://access.redhat.com/security/cve/CVE-2025-3501), CVSS 8.2: Keycloak hostname verification
* [CVE-2025-3910](https://access.redhat.com/security/cve/CVE-2025-3910), CVSS 5.4: Two factor authentication bypass
* [CVE-2025-2559](https://access.redhat.com/security/cve/CVE-2025-2559), CVSS 4.9: JWT token cache OOM
=> fix(keycloak-operator): update keycloak from 26.2.1 to 26.2.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Latest version of Argo CD 2.x.
We are aware that Argo CD 3.x is out, this changes comes before that (and while we clarify the upgrade path with affected users).
=> feat(infra-apps): upgrade Argo CD from 2.14.8 to 2.14.11

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
See the [release notes](https://www.keycloak.org/2025/05/keycloak-2623-released) for details.
=> fix(keycloak-operator): update keycloak and operator from 26.2.2 to 26.2.3

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
=> chore(security-apps): bump kyverno from 3.3.7 to 3.4.1

charts/customer-center/Chart.yaml, charts/customer-center/README.md, charts/customer-center/templates/_helpers.tpl
Removes a duplicate label generated by the helper template functions.
=> fix(customer-center): remove duplicate managed-by label

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Upgrade Kyverno Policies to 3.4.1
Implements https://github.com/adfinis/helm-charts/issues/1400
=> Bump security-apps/kyverno-policies to 3.4.1

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
=> feat(infra-apps): Update Argo CD from 2.x to 3.0.5

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
=> feat(argo-apps): Update Argo Rollouts from 1.7.2 to 1.8.3

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Upgrades `kube-prom-stack` from version 72.5.0 to 75.3.0
This upgrade includes multiple breaking changes as described here: 
- https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/UPGRADE.md
=> chore(infra-apps): upgrade kube-prom-stack to v75.3.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
=> chore(security-apps): upgrade oauth2-proxy to 7.9.0

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Pins the msteams alert forwarder to a version instead of wildcarding patch releases.
=> fix(misc-apps): pin prometheus-msteams version

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Mostly fixes in various parts of Kyverno.
=> fix(security-apps): Update Kyverno from 1.14.1 to 1.14.3

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
Contains several changes, e.g. a new metrics setup for otel-collector itself and a new location for container images that isn't affected by policy changes at Dockerk Inc.
=> feat(tracing-apps): Update otel-collector chart from 0.119.0 to 0.127.0

charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md, charts/tracing-apps/values.yaml
The 0.127.0 version of the chart seems to have been yoinked
=> fix(tracing-apps): Update otel-collector from 0.127.0 to 0.127.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
=> fix(infra-apps): update nginx-ingress from 1.12.1 to 1.12.3

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Update Vault Helm chart from 0.28.0 to 0.30.0
=> chore: bump Vault Helm chart from 0.28.0 to 0.30.0

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
The chart has been configured to fail since #1147 but we forgot to remove the values part.
* fixes https://github.com/adfinis/helm-charts/issues/1439
=> fix(infra-apps): Remove deprecated values from chart

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
Update Argo Rollouts Chart from 2.39.6 to 2.40.2
https://github.com/adfinis/helm-charts/issues/1429
=> chore: upgrade argoRollouts chart version  from 2.39.6 to 2.40.2

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Upgrading opencost chart version from 1.39.0 to 2.1.7.
This change was tested on a local dev cluster, since opencost is not deployed on aks int test
https://github.com/adfinis/helm-charts/issues/1450
=> chore: upgrade opencost chart version

README.md, charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/ci/operand-values.yaml, charts/keycloak-operator/crds/keycloakrealmimports.k8s.keycloak.org-v1.yml, charts/keycloak-operator/crds/keycloaks.k8s.keycloak.org-v1.yml, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/templates/keycloak/keycloakrealmimport.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap, charts/keycloak-operator/values.yaml
Update Keycloak to 36.3.2, includes updates to both the operator as well as the operand.
=> feat(keycloak-operator): update from 26.2.3 to 26.3.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Some bugfixes that most likely don't affect us:
> We fixed a bug in the CSR's name constraints construction (only applies if you have enabled the NameConstraints feature gate).
We dropped the new global.rbac.disableHTTPChallengesRole Helm option due to a bug we found, this feature will be released in v1.19 instead.
* fixes #1431
=> feat(infra-apps): Update cert-manager from 1.18.1 to 1.18.2

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
introduce critical severity for CertManagerCertExpirySoon alert
* fixes #1433
=> feat(infra-apps): Update cert-manager-monitoring from 0.1.* to 0.2.0

charts/argo-apps/Chart.yaml, charts/argo-apps/README.md, charts/argo-apps/values.yaml
This change upgrades the argo-Rollouts chart from version 2.40.2 to 2.40.3
=> chore: upgrade argoRollouts chart version from 2.40.2 to 2.40.3

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/ci/operand-values.yaml, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Fixes the following error when specifying Ingress annotations:
```
Error: template: keycloak-operator/templates/keycloak/keycloak.yaml:116:21: executing "keycloak-operator/templates/keycloak/keycloak.yaml" at <6>: wrong type for value; expected string; got map[string]interface {}
```
=> fix(keycloak-operator): allow configuring keycloak.ingress.annotations

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Fixes: https://github.com/adfinis/helm-charts/issues/1458
Bump secretsStoreCsiDriver chart from 1.4.4 to 1.5.3
n/a
=> chore(secretsStoreCsiDriver): Bump to 1.5.3

charts/misc-apps/Chart.yaml, charts/misc-apps/README.md, charts/misc-apps/values.yaml
Contains patches with dependency and security updates.
* fixes #1446
=> feat(misc-apps): Update ChartMuseum from 0.16.1 to 0.16.3

charts/security-apps/Chart.yaml, charts/security-apps/README.md
Marked the falco chart as deprecated since we no longer use it internally.
https://github.com/adfinis/helm-charts/issues/1454
=>  chore(security-apps): Mark falco as deprecated

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Updates Mimir-Distributed Chart Version to 5.8.0
#1438 
* Updates Mimir to 2.17.0
* Minor fixes in Helm Chart
=> chore(mimir): update to 5.8.0 chart

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
Bumping dex chart to 0.24.0.
Note: Upgrading Dex might require a restart of the kubeapi server.
Since we currently do not deploy this chart directly on AKS, I tested it on a local test cluster.
https://github.com/adfinis/helm-charts/issues/1452
=> chore(security-apps): Bumping dex chart to 0.24.0

README.md, charts/tracing-apps/Chart.yaml, charts/tracing-apps/README.md
The update to the otel collector removed the loki exporter, which breaks some of our otel - loki setups.
This makes the update as a breaking change and adds the migration instructions.
- [Breaking Release](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases)
- [Migration Instructions](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/release/v0.130.x/exporter/lokiexporter/README.md#migration-instructions)
- [Otel Exporter Docs](https://grafana.com/docs/loki/latest/send-data/otel/)
- [Otel exporter vs loki exporter](https://grafana.com/docs/loki/latest/send-data/otel/native_otlp_vs_loki_exporter/)
https://github.com/adfinis/helm-charts/issues/1469
=> fix(tracing-apps): Mark otel collector update a breaking change

charts/logging-apps/Chart.yaml, charts/logging-apps/README.md, charts/logging-apps/values.yaml
Fixes: https://github.com/adfinis/helm-charts/issues/1440
Bump loki to 6.38 
- kind: BREAKING
description: Removed tokengen job, kubectl dependency, and auto-creation of admin token secrets. Admin token secret must be created manually (#18803)
- kind: BREAKING
description: Zone-aware ingester StatefulSets require manual deletion before upgrade. PVCs preserved (#18558)
=> chore(logging-apps): Bump loki from 6.32.0 to 6.38.0

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
- Update VaultMonitoring from 0.4.2 to 0.6.0
- Fixes https://github.com/adfinis/helm-charts/issues/1457
=> chore(security-apps): Update vaultMonitoring from 0.4.2 to 0.6.0

charts/infra-apps/Chart.yaml, charts/infra-apps/README.md, charts/infra-apps/values.yaml
Update Argo CD
* CVE-2025-59538
* CVE-2025-59537
* CVE-2025-59531
* CVE-2025-55191
=> fix(infra-apps): update argo cd from v3.1.3 to v3.1.8

charts/keycloak-operator/Chart.yaml, charts/keycloak-operator/README.md, charts/keycloak-operator/ci/operand-values.yaml, charts/keycloak-operator/templates/keycloak/keycloak.yaml, charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap, charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
We were comparing false values using `with`, leading to settings like `startOptimized=false` getting removed instead of rendered.
This changes the check to just render them if available, even if the values are falsey.
=> fix(keycloak-operator): allow specifying false in ternary values

charts/security-apps/Chart.yaml, charts/security-apps/README.md, charts/security-apps/values.yaml
=> chore(security-apps): bump oauth2-proxy to 8.3.0
